main/iptables: save rules before pre-nft upgrade, don't overwrite rules if save fails
closes #15001

diff --git a/main/iptables/iptables.initd b/main/iptables/iptables.initd
--- a/main/iptables/iptables.initd
+++ b/main/iptables/iptables.initd
@@ -113,8 +113,19 @@ reload() {
 save() {
 	ebegin "Saving ${iptables_name} state"
 	checkpath -fm 0600 "${iptables_save}"
-	${iptables_bin}-save ${SAVE_RESTORE_OPTIONS} > "${iptables_save}"
-	eend $?
+	local exitcode tmp
+
+	tmp="$(mktemp)"
+	${iptables_bin}-save ${SAVE_RESTORE_OPTIONS} > "${tmp}"
+	exitcode=$?
+	if [ "$exitcode" -eq 0 ]; then
+		# command succeeded, so overwrite
+		mv "${tmp}" "${iptables_save}"
+	else
+		ewarn "${iptables_bin}-save failed!"
+		rm -f "${tmp}"
+	fi
+	eend $exitcode
 }
 
 panic() {
