testing/ghc-current: upgrade to 9.15_pre20251106
bump to rebased https://gitlab.haskell.org/ghc/ghc/-/merge_requests/14887

diff --git a/testing/ghc-current/APKBUILD b/testing/ghc-current/APKBUILD
--- a/testing/ghc-current/APKBUILD
+++ b/testing/ghc-current/APKBUILD
@@ -1,8 +1,8 @@
 # Maintainer: Celeste <cielesti@protonmail.com>
 maintainer="Celeste <cielesti@protonmail.com>"
 pkgname=ghc-current
-pkgver=9.15_pre20250925
-_gitrev=caee3d536a617f76635c296d62f0179b59281f55
+pkgver=9.15_pre20251106
+_gitrev=41d401340e603a60528e450d4c2e0f1c656a7dab
 pkgrel=0
 _pkgdate="${pkgver##*_pre}"
 _pkgver="${pkgver%%_pre*}.$_pkgdate"
@@ -37,6 +37,7 @@ makedepends_build="
 	clang$_llvmver
 	coreutils
 	ghc-bootstrap~$_bootstrapver
+	ghc-release-cabal
 	grep
 	libffi-dev
 	llvm$_llvmver
@@ -79,17 +80,19 @@ _libraries_ghc_internal_gmp_gmp_tarballs_commit=01149ce3471128e9fe0feca607579981
 _libraries_haskeline_commit=991953cd5d3bb9e8057de4a0d8f2cae3455865d8
 _libraries_hpc_commit=12675279dc5cbea4ade8b5157b080390d598f03f
 _libraries_mtl_commit=37cbd924cb71eba591a2e2b6b131767f632d22c9
-_libraries_os_string_commit=2e693aad07540173a0169971b27c9acac28eeff1
+_libraries_os_string_commit=c08666bf7bf528e607fc1eacc20032ec59e69df3
 _libraries_parsec_commit=552730e23e1fd2dae46a60d75138b8d173492462
 _libraries_pretty_commit=c3a1469306b35fa5d023dc570554f97f1a90435d
 _libraries_process_commit=ae50731b5fb221a7631f7e9d818fc6716c85c51e
 _libraries_semaphore_compat_commit=ba87d1bb0209bd9f29bda1c878ddf345f8a2b199
 _libraries_stm_commit=23bdcc2319965911af28542e76fc01f37c107d40
+_libraries_template_haskell_lift_commit=e0b2a7eefcd1b7247af63ab4a691d3161eada284
+_libraries_template_haskell_quasiquoter_commit=a47506eca032b139d9779fb8210d408c81d3fbd6
 _libraries_terminfo_commit=16db154e3e97e6bff62329574163851a7090f3b6
 _libraries_text_commit=5f343f668f421bfb30cead594e52d0ac6206ff67
 _libraries_time_commit=507f50844802f1469ba6cadfeefd4e3fecee0416
 _libraries_transformers_commit=cee47cca7705edafe0a5839439e679edbd61890a
-_libraries_unix_commit=c9b3e95b5c15b118e55522bd92963038c6a88160
+_libraries_unix_commit=60f432b76871bd7787df07dd3e2a567caba393f5
 _libraries_xhtml_commit=68353ccd1a2e776d6c2b11619265d8140bb7dc07
 _utils_hpc_commit=5923da3fe77993b7afc15b5163cffcaa7da6ecf5
 _utils_hsc2hs_commit=fe3990b9f35000427b016a79330d9f195587cad8
@@ -119,6 +122,8 @@ source="https://gitlab.haskell.org/ghc/ghc/-/archive/$_gitrev/ghc-$_gitrev.tar.g
 	https://gitlab.haskell.org/ghc/packages/process/-/archive/$_libraries_process_commit/process-$_libraries_process_commit.tar.gz
 	https://gitlab.haskell.org/ghc/semaphore-compat/-/archive/$_libraries_semaphore_compat_commit/semaphore-compat-$_libraries_semaphore_compat_commit.tar.gz
 	https://gitlab.haskell.org/ghc/packages/stm/-/archive/$_libraries_stm_commit/stm-$_libraries_stm_commit.tar.gz
+	https://gitlab.haskell.org/ghc/template-haskell-lift/-/archive/$_libraries_template_haskell_lift_commit/template-haskell-lift-$_libraries_template_haskell_lift_commit.tar.gz
+	https://gitlab.haskell.org/ghc/template-haskell-quasiquoter/-/archive/$_libraries_template_haskell_quasiquoter_commit/template-haskell-quasiquoter-$_libraries_template_haskell_quasiquoter_commit.tar.gz
 	https://gitlab.haskell.org/ghc/packages/terminfo/-/archive/$_libraries_terminfo_commit/terminfo-$_libraries_terminfo_commit.tar.gz
 	https://gitlab.haskell.org/ghc/packages/text/-/archive/$_libraries_text_commit/text-$_libraries_text_commit.tar.gz
 	https://gitlab.haskell.org/ghc/packages/time/-/archive/$_libraries_time_commit/time-$_libraries_time_commit.tar.gz
@@ -127,6 +132,8 @@ source="https://gitlab.haskell.org/ghc/ghc/-/archive/$_gitrev/ghc-$_gitrev.tar.g
 	https://gitlab.haskell.org/ghc/packages/xhtml/-/archive/$_libraries_xhtml_commit/xhtml-$_libraries_xhtml_commit.tar.gz
 	https://gitlab.haskell.org/hpc/hpc-bin/-/archive/$_utils_hpc_commit/hpc-bin-$_utils_hpc_commit.tar.gz
 	https://gitlab.haskell.org/ghc/hsc2hs/-/archive/$_utils_hsc2hs_commit/hsc2hs-$_utils_hsc2hs_commit.tar.gz
+
+	cabal.project.freeze
 
 	plan-bootstrap-from-9.8.2.json
 	plan-bootstrap-from-9.12.2.json
@@ -151,8 +158,11 @@ _hadrian_args="-j${JOBS:-1} --docs=none"
 if [ "$CBUILD" != "$CTARGET" ]; then
 	_hadrian_args="$_hadrian_args --flavour=quickest"
 else
-	_hadrian_args="$_hadrian_args --flavour=perf+no_profiled_libs+omit_pragmas --hash-unit-ids"
+	_hadrian_args="$_hadrian_args --flavour=perf+no_profiled_libs+omit_pragmas+hash_unit_ids"
 fi
+
+# Directory where cabal files are stored.
+export CABAL_DIR="${CABAL_DIR:-"$srcdir/cabal"}"
 
 _configure() {
 	# clang instead of llvm-as: https://gitlab.haskell.org/ghc/ghc/-/issues/24630
@@ -193,7 +203,9 @@ prepare() {
 		libraries/ghc-internal/gmp/gmp-tarballs libraries/haskeline \
 		libraries/hpc libraries/mtl libraries/os-string \
 		libraries/parsec libraries/pretty libraries/process \
-		libraries/semaphore-compat libraries/stm libraries/terminfo \
+		libraries/semaphore-compat libraries/stm \
+		libraries/template-haskell-lift \
+		libraries/template-haskell-quasiquoter libraries/terminfo \
 		libraries/text libraries/time libraries/transformers \
 		libraries/unix libraries/xhtml utils/hpc utils/hsc2hs
 
@@ -243,6 +255,10 @@ prepare() {
 		libraries/semaphore-compat
 	mv -v ../stm-$_libraries_stm_commit \
 		libraries/stm
+	mv -v ../template-haskell-lift-$_libraries_template_haskell_lift_commit \
+		libraries/template-haskell-lift
+	mv -v ../template-haskell-quasiquoter-$_libraries_template_haskell_quasiquoter_commit \
+		libraries/template-haskell-quasiquoter
 	mv -v ../terminfo-$_libraries_terminfo_commit \
 		libraries/terminfo
 	mv -v ../text-$_libraries_text_commit \
@@ -261,7 +277,11 @@ prepare() {
 		utils/hsc2hs
 
 	(
-		cd "$builddir"/hadrian/bootstrap/
+		cd "$builddir"/hadrian
+
+		ln -svf "$srcdir"/cabal.project.freeze .
+
+		cd bootstrap
 
 		python3 ./bootstrap.py \
 			-d "$srcdir"/plan-bootstrap-from-$_bootstrapver.json \
@@ -299,12 +319,24 @@ build() {
 	# See:
 	#   * https://gitlab.haskell.org/ghc/ghc/-/tree/master/hadrian/bootstrap
 	#   * https://www.haskell.org/ghc/blog/20220805-make-to-hadrian.html
-	cd "$builddir"/hadrian/bootstrap/
-	[ -x "$_hadrian" ] || python3 ./bootstrap.py \
-		-j ${JOBS:-1} \
-		-w /usr/bin/ghc \
-		--no-archive \
-		-d _build/tarballs/plan-bootstrap.json
+	local orig_hadrian=$_hadrian
+	cd "$builddir"/hadrian
+	if command -v cabal >/dev/null; then
+		cabal v2-update
+		cabal v2-build hadrian:exes -j \
+			--allow-newer --ghc-options="-j -H64m"
+		_hadrian="$(cabal list-bin --allow-newer hadrian:exes | head -1)"
+	fi
+
+	cd bootstrap
+	if [ ! -x "$_hadrian" ]; then
+		python3 ./bootstrap.py \
+			-j ${JOBS:-1} \
+			-w /usr/bin/ghc \
+			--no-archive \
+			-d _build/tarballs/plan-bootstrap.json
+		_hadrian=$orig_hadrian
+	fi
 
 	# NOTE: ghc build system requires host == build, and it ends up
 	# compiling the cross-compiler (stage1) and cross-compiling with
@@ -381,6 +413,38 @@ cmds() {
 	amove usr/bin
 }
 
+# Helper function for generating Hadrian's cabal.project.freeze
+freeze_hadrian() {
+	local repo="hackage.haskell.org"
+
+	# Default config uses HTTP, change it to HTTPS.
+	[ -f "$CABAL_DIR"/config ] || {
+		cabal user-config init
+		cabal user-config update -a \
+			"repository $repo {url: https://$repo/}"
+	}
+
+	cd "$startdir"
+	[ -d "$builddir" ] || abuild unpack
+	msg "Freezing Hadrian dependencies"
+
+	# Resolve deps and generate fresh cabal.project.freeze with version constraints.
+	(
+		cd "$builddir"/hadrian || {
+			error 'Is $builddir set correctly?'
+			return 1
+		}
+		cabal v2-update
+		cabal v2-freeze --allow-newer --shadow-installed-packages
+
+		mv -v cabal.project.freeze "$startdir"/
+	)
+
+	if ! abuild checksum; then
+		die "Failed to update checksum, run 'abuild checksum' manually"
+	fi
+}
+
 # Helper function, requires curl and jq to run
 print_submodules() {
 	local submodules="$(
@@ -399,9 +463,10 @@ print_submodules() {
 		libraries/haskeline libraries/hpc \
 		libraries/mtl libraries/os-string \
 		libraries/parsec libraries/pretty \
-		libraries/process libraries/semaphore-compat \
-		libraries/stm libraries/terminfo \
-		libraries/text libraries/time \
+		libraries/process libraries/semaphore-compat libraries/stm \
+		libraries/template-haskell-lift \
+		libraries/template-haskell-quasiquoter \
+		libraries/terminfo libraries/text libraries/time \
 		libraries/transformers libraries/unix \
 		libraries/xhtml utils/hpc utils/hsc2hs
 	do
@@ -415,7 +480,7 @@ print_submodules() {
 }
 
 sha512sums="
-51b04940da8fc7d09f2fb9bb8b0183a8a0644775b4f35c3e55ab57ade84ab47675dd63f0d04421b61eb7c1e819c72e058d5aac5be92b995ca11b846872ea88ae  ghc-caee3d536a617f76635c296d62f0179b59281f55.tar.gz
+42d416d4ec7b302c7b81889f6de73003c67efead84360cd6faf90b7b13f1ebdbf954d9f2973755dd6cd546620e71df485b3b94b04dcdcbfbb6d1b46cd553817b  ghc-41d401340e603a60528e450d4c2e0f1c656a7dab.tar.gz
 a2ff6a1778884de22f4900a22b8a451ed5dc8a8e66020ce9e186a03068257748a3810c63b56f1efa0b646d99fe637f87178983f387d4c49bc33b82613877ec48  happy-1.20.1.1.tar.gz
 a1d935e2c95078c41d6900f723bfd3fca87170298dd1e890f272002cbb295865d48e48beb3bae35172511f0967ae777addba0b51025d8e2027e340d497351f8c  libffi-tarballs-7c51059557b68d29820a0a87cebfa6fe73c8adf5.tar.gz
 f03a0a6a38d0dd53f2ca7eaa8c3b9a0c1e073fad768b66018ee646e7f0befccc7a837cd7aac02608edba5383a915dacd5317cb58f116400eaa553b2686dc4213  nofib-b7391df4540ac8b11b35e1b2e2c15819b5171798.tar.gz
@@ -434,23 +499,26 @@ c1f582db4b9d7e41359cdca24846c34dee8845a404a26aedf6e69cb8b1355ed11eee43b399de3910
 f341799dee1761556c1a7179c6adc830e9f80a6ef5fed8d4ac593128f9d1bfc828913d20bb62749d9d2db9f6836fcc2af7a99855be1dcb6c43ff35350361daf0  haskeline-991953cd5d3bb9e8057de4a0d8f2cae3455865d8.tar.gz
 cd53d6edb381c66535e57a6de323e24868dce2a05b0c09be179f20e3a87d54efd0488344e72f0955e2a56bc9fe24ff1e6c58a28daf8f1cdbc9ea7ef528114a73  hpc-12675279dc5cbea4ade8b5157b080390d598f03f.tar.gz
 c5e5fc0a165ee886612cbedd912744d7f4fb71424a15ba7c645a013ef6e35941736b9e9d695807d929227a3fc7f6cc8b8b59f62692cf413fbe2c6594ee504594  mtl-37cbd924cb71eba591a2e2b6b131767f632d22c9.tar.gz
-57213a9b9f79f5e317d59e8dfc6d2fb8de3601ff3fd59a100e81d9c9806c1c5cc248279e820bd053c3b0f7e841bcdf46ea67c0309eb0ff518966821f6f2e0e17  os-string-2e693aad07540173a0169971b27c9acac28eeff1.tar.gz
+c904f8f5e313d6fb18f445c917e2db36fef2415299bd297be98790a21b65d8a6075db1e186060619ce535f0019cf675c738eee16cfa9e1e53045bbdbfa651769  os-string-c08666bf7bf528e607fc1eacc20032ec59e69df3.tar.gz
 868f8b54461f16dc7db2669a98c342fdc5030170ad1df21c01ee6097cbd4e35a5a4adf22a8b7a67b862260f807558483f006822824a5bf0e868ba78a2cc720fa  parsec-552730e23e1fd2dae46a60d75138b8d173492462.tar.gz
 1aebabc2620194459bfca5aa203767175447464922af4764c9ef4080775ee7c3adecc6f5d3adfa6545f77f48d9e548db013deaf9f1f529862a99c3d78b3037ad  pretty-c3a1469306b35fa5d023dc570554f97f1a90435d.tar.gz
 901f31e369ed275bda75ddf97f087d007f0b54435222ebd07cf129d0302eac8e7b7efb0e0c1e129b74869cc284b055bb3191785703768e953efc1c55311ec51a  process-ae50731b5fb221a7631f7e9d818fc6716c85c51e.tar.gz
 b36947c913dbf41ba0ff39414bdd53517804b0d6b9a4c6d555456fc025c15a540602b773bcaf267f71f4f899ade74fe2893addd4777652140a8ac601699fd1cb  semaphore-compat-ba87d1bb0209bd9f29bda1c878ddf345f8a2b199.tar.gz
 1d5ac68c593f69c49c6ae7ba4b54e9c36725fecdffc1757a9577b094645749385beea884458b497118c6cf993a03b6ac98245019b15dc2f99b9afe1e17a786d5  stm-23bdcc2319965911af28542e76fc01f37c107d40.tar.gz
+850f5a712b6b6837de2601c4cb438aaf1bcb895b3ca4b2bf90d4ec6601c1fc32fd3dc6686a1a2e103cbd3eedd67866a7886b7287e757735fa771ad2acc9c2ac8  template-haskell-lift-e0b2a7eefcd1b7247af63ab4a691d3161eada284.tar.gz
+3e34b0bbd059fc0bb028adc767ccfa261074c7c003ccd3595a0c6f445145c66f009830f0b182212931b97ec7a1ede0a1163e46df807cdf5ee4ef9d2b4e8bf7e6  template-haskell-quasiquoter-a47506eca032b139d9779fb8210d408c81d3fbd6.tar.gz
 aa591c8ab0a1d4e05d2bd9aa4d9b4881f4a240a39a9998ba76c5e0d4ca5b7b17faa6541cdac79e3a8d4775c27325c4fef77a309496871379913cb20866588c6b  terminfo-16db154e3e97e6bff62329574163851a7090f3b6.tar.gz
 521d632a24307d1a0488de8a652cd7c3c958409468a2ab37f0194cd0e1afff57ae6c66003abecbd2029321b82e6a9b80b97688331cd4e0246dd39df795ff3d38  text-5f343f668f421bfb30cead594e52d0ac6206ff67.tar.gz
 a4b31e317a872d243034ccf91dd34e9504587a86390a421eaa09ad35cd6f0777f53dd53c2738d639b15ba8ca4baf5ae41a23989d0bdb94a1300bc7158ecdd5fc  time-507f50844802f1469ba6cadfeefd4e3fecee0416.tar.gz
 3cd763e7d4a38324756dcc5135abcb95aa5bb2ba8dea340ba2a771a210804dc477536ef42c3dec0818e299fbbe354c03609be06aa769d84e589da0f6a70fbf70  transformers-cee47cca7705edafe0a5839439e679edbd61890a.tar.gz
-63b2d4b742e0e9ba336afe1dd0750563330736fe40c22b0fe0393c4ae924e5f89ec57a9d6f2128dbf079333c9d13240ff8a1b48fa92a3deba0eca1851a2b5f48  unix-c9b3e95b5c15b118e55522bd92963038c6a88160.tar.gz
+61f8f8d148b3611123cf277745d4a7ffaa43385e357cfc5904311507dad7e55ada42790aa8679d9d99ba009fc1af732be1f503b1184eb4a2ce3c04db70774edf  unix-60f432b76871bd7787df07dd3e2a567caba393f5.tar.gz
 cc14d9e0e25031a05a6bd6006f5ed3b0db716c1c96e1a0d2973b5e4d43c9a3944cb41a5248578e98d843dbbea1ac6b6c3046654eaa6337a66f9832c4f644ac6c  xhtml-68353ccd1a2e776d6c2b11619265d8140bb7dc07.tar.gz
 bb761665eaaeb1adf2825bd5e00ea3ee1c9b3f9e3054ede00b3c26f13b452f96878e5aef3b76632fb40ee4b613af93c980b36b4a8a9222e790a7628618302060  hpc-bin-5923da3fe77993b7afc15b5163cffcaa7da6ecf5.tar.gz
 54cce8463de88aa71a87d1632c312712c99eadc0bdd4361f1f9cff1f9088dcd677b57ee6ab7ba1cb1159ea849b8a28f798a68fcaa866990bd6563146f5dcd20d  hsc2hs-fe3990b9f35000427b016a79330d9f195587cad8.tar.gz
+1955e967723c7db07c754d05f7eadde54464596d70bb82508642207b48c0dfb21d8e4e6947e4a2c1d1d4136eeb7cd630af03002f925d3eba111d874c3ca7538a  cabal.project.freeze
 1321f2c6bc21d17ec1f2a8d5a00465ae5c8fbb18c77aa13e11cc1ebac4d2556a60c070887c5aa20dfd40e8293be85bdc1e2741e8dd141607eb9d69d9934e1a9b  plan-bootstrap-from-9.8.2.json
 41d3dc50bba6c66d508a3f0e4d9a88671c9aa9609248b70e20a3fec56f724b0bf681aec90f44be7a56e74624f7b8e9b92dc409933ad236e6956a4f3d7654efee  plan-bootstrap-from-9.12.2.json
-3f5e9d07b64e7bf762e8fe85788736e52c9b6e45a8433286e65b0e12413e3798a553bd1b7deebade2e941c30891e06bf5cc8059601a17c779c8ffaa8663bfe72  plan-bootstrap-from-9.14.1.json
+62407e64c106e6b8843d150b2e5a790876908bf965846d5e9742be70b06975b31f1ec62aabaac1ccd0703431b548395099a1cea5168d0d1ee286c91285f18d16  plan-bootstrap-from-9.14.1.json
 0e59d1c39e1e51ed697edc3aa87f219212a0e19312f5cdfd30b8d219b1bf8e64b36495acf7bc75920dadab8eee04ca66e022e61842152668b0daf4d597010b58  parallel-hadrian-bootstrap.patch
 254b30a68498f52e502d6d6fcfb6d2ae6192d0086a4710c76fd63319ae286680f4dee1b1fcbb5bad57d7737d5d6a6c2a99250670e23a53f68b42291d8b0afc6b  plan-9.14.1-allow-newer.patch
 "
