main/syslog-ng: improvements and fixes (replaces main/eventlog) * libevtlog is a part of syslog-ng since 3.11.1 (provides eventlog{,-dev}) * add Linux capabilities support (run syslog-ng as non-root) * auto-gen conf version number on init service "update" action * add support and subpkgs for geoip2 and mongodb, sql, & http dests * move redis, amqp, & python modules to subpkgs * move extra utilities and files to -extra subpkg * create -dev subpkg * build man pages and create -doc subpkg

diff --git a/main/syslog-ng/syslog-ng.initd b/main/syslog-ng/syslog-ng.initd
--- a/main/syslog-ng/syslog-ng.initd
+++ b/main/syslog-ng/syslog-ng.initd
@@ -58,7 +58,16 @@ update() {
 	do
 		[ -f /etc/syslog-ng/syslog-ng-${ng_std}.std ] || exit 1
 	done
+
+	local cfgver="$(/usr/sbin/syslog-ng -V \
+	    | awk -F':' -v key='Config version' '$1==key && $2~/^\s*\d.\d{2}\s*$/ {gsub(/\s+/, "", $2); print $2}')"
+	[ -n "$cfgver" ] || {
+		>&2 echo "ERROR: Couldn't parse config (API) version from output of 'syslog-ng -V'"
+		return 1
+	}
+
 	{
+		echo "@version: ${cfgver}"
 		# create options entries
 		grep_syslog_conf_entries plugins
 		echo "options {"
@@ -73,6 +82,7 @@ update() {
 		# create log entries
 		grep_syslog_conf_entries log
 	} > $f_tmp
+
 	cp -p $f_tmp $fname
 	rm -f $f_tmp
 }
