community/tcpreplay: upgrade to 4.5.1

diff --git a/community/tcpreplay/skip-tests-require-root.patch b/community/tcpreplay/skip-tests-require-root.patch
--- a/community/tcpreplay/skip-tests-require-root.patch
+++ b/community/tcpreplay/skip-tests-require-root.patch
@@ -1,9 +1,8 @@
 These tests require root to run. Disable them so that we can still run the other tests
-diff --git a/test/Makefile.in b/test/Makefile.in.new
-index d325ee2dd6..68ee3c3628 100644
+
 --- a/test/Makefile.in
-+++ b/test/Makefile.in.new
-@@ -790,16 +790,10 @@ include_dest:
++++ b/test/Makefile.in
+@@ -833,10 +833,7 @@
  	if [ $? ] ; then $(PRINTF) "\t\t%s\n" "FAILED"; else $(PRINTF) "\t\t%s\n" "OK"; fi
  
  replay_basic:
@@ -12,6 +11,11 @@ index d325ee2dd6..68ee3c3628 100644
 -	$(TCPREPLAY) $(ENABLE_DEBUG) -i $(nic1) -t $(TEST_PCAP) >> test.log 2>&1
 -	if [ $? ] ; then $(PRINTF) "\t\t\t%s\n" "FAILED"; else $(PRINTF) "\t\t\t%s\n" "OK"; fi
 +	$(PRINTF) "%s\t\t\t\t%s\n" "[tcpreplay] Basic test:" "[SKIP]"
+ 
+ replay_nano_timer:
+ 	$(PRINTF) "%s" "[tcpreplay] Nano timer test: "
+@@ -845,10 +842,7 @@
+ 	if [ $? ] ; then $(PRINTF) "\t\t\t%s\n" "FAILED"; else $(PRINTF) "\t\t\t%s\n" "OK"; fi
  
  replay_cache:
 -	$(PRINTF) "%s" "[tcpreplay] Cache test: "
@@ -22,7 +26,7 @@ index d325ee2dd6..68ee3c3628 100644
  
  replay_accurate:
  	$(PRINTF) "%s" "[tcpreplay] Accurate test: "
-@@ -808,10 +802,7 @@ replay_accurate:
+@@ -857,10 +851,7 @@
  	if [ $? ] ; then $(PRINTF) "\t\t\t%s\n" "FAILED"; else $(PRINTF) "\t\t\t%s\n" "OK"; fi
  
  replay_stats:
@@ -34,8 +38,8 @@ index d325ee2dd6..68ee3c3628 100644
  
  rewrite_portmap:
  	$(PRINTF) "%s" "[tcprewrite] Portmap test: "
-@@ -1028,40 +1019,22 @@ rewrite_l7fuzzing:
- 	if [ $? ] ; then $(PRINTF) "\t\t\t%s\n" "FAILED"; else $(PRINTF) "\t\t\t%s\n" "OK"; fi
+@@ -1144,40 +1135,22 @@
+ 	if [ $? ] ; then $(PRINTF) "\t\t\t%s\n" "FAILED"; else $(PRINTF) "\t%s\n" "OK"; fi
  
  replay_pps:
 -	$(PRINTF) "%s" "[tcpreplay] Packets/sec test: "
@@ -81,7 +85,7 @@ index d325ee2dd6..68ee3c3628 100644
  
  datadump_mode:
  	$(PRINTF) "%s" "[tcpreplay] Data dump test: "
-@@ -1070,22 +1046,13 @@ datadump_mode:
+@@ -1186,22 +1159,13 @@
  	if [ $? ] ; then $(PRINTF) "\t\t\t%s\n" "FAILED"; else $(PRINTF) "\t\t\t%s\n" "OK"; fi
  
  replay_config:
@@ -105,5 +109,5 @@ index d325ee2dd6..68ee3c3628 100644
 -	if [ $? ] ; then $(PRINTF) "\t\t%s\n" "FAILED"; else $(PRINTF) "\t\t%s\n" "OK"; fi
 +	$(PRINTF) "%s\t\t\t%s\n" "[tcpreplay] Maximum sleep test:" "[SKIP]"
  
- clean:
- 	rm -f *1 test.log core* *~ primary.data secondary.data
+ # the following write to a file
+ replay_include:
