testing/stack: upgrade to 2.15.7 & take over maintainership

diff --git a/testing/stack/APKBUILD b/testing/stack/APKBUILD
--- a/testing/stack/APKBUILD
+++ b/testing/stack/APKBUILD
@@ -1,7 +1,7 @@
 # Contributor: gay <gay@disroot.org>
-# Maintainer: gay <gay@disroot.org>
+# Maintainer: Celeste <cielesti@protonmail.com>
 pkgname=stack
-pkgver=2.7.5
+pkgver=2.15.7
 pkgrel=0
 pkgdesc="The Haskell Tool Stack"
 url="https://haskellstack.org/"
@@ -12,27 +12,78 @@ makedepends="
 	ghc
 	gmp-dev
 	sqlite-dev
+	uusi
 	zlib-dev
 	"
 checkdepends="ncurses-dev"
+subpackages="
+	$pkgname-bash-completion
+	$pkgname-fish-completion
+	$pkgname-zsh-completion
+	"
 source="https://hackage.haskell.org/package/stack-$pkgver/stack-$pkgver.tar.gz
-	cabal.config
-	aeson.patch
-	ghc9.0.x.patch
-	persistent.patch
+	cabal.project.freeze
 	"
 
-export CABAL_DIR="$srcdir"/cabal
+export CABAL_DIR="${CABAL_DIR:-"$srcdir/cabal"}"
+
+cabal_relax() {
+	# Following what Homebrew does
+	cat > "$builddir"/cabal.project <<-'END'
+		packages: .
+		constraints: tar < 0.6
+	END
+
+	uusi -u directory -u filepath "$builddir"/$pkgname.cabal
+}
+
+cabal_update() {
+	local repo="hackage.haskell.org"
+
+	# Default config uses HTTP, change it to HTTPS.
+	[ -f "$CABAL_DIR"/config ] || {
+		cabal user-config init
+		cabal user-config update -a \
+			"repository $repo {url: https://$repo/}"
+	}
+
+	[ -d "$builddir" ] || abuild unpack
+	msg "Freezing $pkgname dependencies"
+
+	# Resolve deps and generate fresh cabal.project.freeze with version constraints.
+	(
+		cd "$builddir" || {
+			error 'Is $builddir set correctly?'
+			return 1
+		}
+		cabal_relax
+
+		cabal v2-update
+		cabal v2-freeze --shadow-installed-packages
+
+		mv -v cabal.project.freeze "$startdir"/
+	)
+
+	if ! abuild checksum; then
+		die "Failed to update checksum, run 'abuild checksum' manually"
+	fi
+}
 
 prepare() {
+	cabal_relax
 	default_prepare
-	cp "$srcdir"/cabal.config .
-	cabal update
-	cabal configure --prefix=/usr
+
+	ln -svf "$srcdir"/cabal.project.freeze "$builddir"/
 }
 
 build() {
-	cabal build --jobs=${JOBS:-1} --enable-relocatable
+	cabal v2-update
+	cabal v2-build stack:exes \
+		--jobs=${JOBS:-1} \
+		--prefix=/usr \
+		--docdir=/usr/share/doc/$pkgname \
+		--sysconfdir=/etc \
+		--enable-relocatable
 }
 
 check() {
@@ -41,13 +92,17 @@ check() {
 
 package() {
 	cd dist-newstyle/build/*-linux/ghc-*/$pkgname-$pkgver/build/$pkgname
-	install -Dm755 $pkgname "$pkgdir"/usr/bin/$pkgname
+	install -Dvm755 $pkgname -t "$pkgdir"/usr/bin/
+
+	./stack --bash-completion-script stack | install -Dm644 /dev/stdin \
+		"$pkgdir"/usr/share/bash-completion/completions/$pkgname
+	./stack --fish-completion-script stack | install -Dm644 /dev/stdin \
+		"$pkgdir"/usr/share/fish/vendor_completions.d/$pkgname.fish
+	./stack --zsh-completion-script stack | install -Dm644 /dev/stdin \
+		"$pkgdir"/usr/share/zsh/site-functions/_$pkgname
 }
 
 sha512sums="
-fd51f990d3ccec6103c8699a8e39c970a0233a1185587a519eda659d2b45bc4496c4f261f6897c06781d0f76d2b1d526d5acdfb502fe1494f8cf048c78ba1a8d  stack-2.7.5.tar.gz
-a54c0790e154105f3e96d19289a905b2b3666d61849ad69d6ed81b00a01ea30c7733ead989c02f1f782a95bcc7f0f2dff41ae1ffdd8eb0995fbbd5f54db232d7  cabal.config
-818547d3d63b243daad11f2c8b811701b4b8a778196e1d69d73a4fd4829f4ad9f4134451153c80b8504f1c18fbc2ee8bca329f6c5eff9ee3c435af7a1947077d  aeson.patch
-209348bd04d1cdce333e71a0570ba3781aeb36a0a5ad8a0e5f08ab9aca8f4d49f681b63cab4b7f4f1ddcc79cbf850d5cb1fc79f7a099b0bb65038774ed0a0820  ghc9.0.x.patch
-73d9291ade690db1838b8dbd7b132d9e808781e5419684c04008b9e967c56d3e66eb64df8ef997d74301d92a76d4071956c5593c42841ef035c39c82ac68892d  persistent.patch
+0a0e2fca52b17e3fbc5091da9fc7dd639a50c37519ae8ea27954536381d63bda4e1f20ca047e061dc898cac35a0551c996ced6f8d87184fe8e5be03e03d3cb82  stack-2.15.7.tar.gz
+bbc0b3a3aa65412e053a0a580c139872c74e3446fdcb46bbcfe0f37b773d54ee0527d8ff6dad46b19c881c0aed459ff298cbd2d81888064362cef226c09dcf14  cabal.project.freeze
 "
