community/arti: upgrade to 1.5.0
- bump rustix crate to build on loongarch64
- use CHOST instead of target triple from rustc output
- run proper tests on all architectures
  - skip tor-memquota tests on 32bit architectures (usize being too small)
  - patch out time conversion test dates that are OutOfRange on 32bit
  - enable and, for now, allow tests to fail on riscv64
- update example config for arti-openrc subpackage

diff --git a/community/arti/APKBUILD b/community/arti/APKBUILD
--- a/community/arti/APKBUILD
+++ b/community/arti/APKBUILD
@@ -1,7 +1,7 @@
 # Contributor: omni <omni+alpine@hack.org>
 # Maintainer: omni <omni+alpine@hack.org>
 pkgname=arti
-pkgver=1.4.5
+pkgver=1.5.0
 pkgrel=0
 pkgdesc="An implementation of Tor, in Rust"
 url="https://tpo.pages.torproject.net/core/arti/"
@@ -11,10 +11,13 @@ arch="all !s390x"
 makedepends="cargo openssl-dev>3 sqlite-dev zstd-dev xz-dev cargo-auditable"
 subpackages="$pkgname-doc $pkgname-openrc"
 source="$pkgname-$pkgver.tar.gz::https://gitlab.torproject.org/tpo/core/arti/-/archive/arti-v$pkgver/arti-arti-v$pkgver.tar.gz
-	32b_arti_example_config_patch
-	disable_system_time_conversion_patch
+	arti-example-config.patch
+	bump_rustix_crate.patch
 	disable-access_symlink-test.patch
 	no-journald-build.patch
+	32b_arti_example_config_patch
+	32b_time_conversion_tests_patch
+	32b_tor-memquota_patch
 	arti.initd
 	"
 builddir="$srcdir/$pkgname-$pkgname-v$pkgver"
@@ -31,26 +34,26 @@ esac
 
 prepare() {
 	default_prepare
-	cargo fetch --target="$CTARGET" --locked
-
-	# Rust target triple.
-	local target=$(rustc -vV | sed -n 's/host: //p')
-
-	# Build against system-provided libs
-	mkdir -p .cargo
-	cat >> .cargo/config.toml <<-EOF
-		[target.$target]
-		zstd = { rustc-link-lib = ["zstd"] }
-	EOF
 
 	case "$CARCH" in
 	arm*|x86)
 		patch crates/arti/src/arti-example-config.toml \
-		"$srcdir"/32b_arti_example_config_patch
+			"$srcdir"/32b_arti_example_config_patch
 		patch crates/tor-hsservice/src/time_store.rs \
-		"$srcdir"/disable_system_time_conversion_patch
+			"$srcdir"/32b_time_conversion_tests_patch
+		patch crates/tor-memquota/src/config.rs \
+			"$srcdir"/32b_tor-memquota_patch
 		;;
 	esac
+
+	cargo fetch --target="$CTARGET" --locked
+
+	# Build against system-provided libs
+	mkdir -p .cargo
+	cat >> .cargo/config.toml <<-EOF
+		[target.$CHOST]
+		zstd = { rustc-link-lib = ["zstd"] }
+	EOF
 }
 
 build() {
@@ -59,13 +62,20 @@ build() {
 
 check() {
 	case "$CARCH" in
-	aarch64|loongarch64|x86*)
-		# the only architectures supported by the criterion-cycles-per-byte
-		# crate, https://gitlab.torproject.org/tpo/core/arti/-/issues/2029
-		cargo test --frozen
+	arm*|x86)
+		# https://gitlab.torproject.org/tpo/core/arti/-/issues/2084
+		cargo test --frozen --workspace --exclude tor-memquota -- \
+			--skip "cfg::test::memquota" \
+			--skip "time_store::test::system_time_conversions"
+		;;
+	riscv64)
+		# https://gitlab.torproject.org/tpo/core/arti/-/issues/1398
+		cargo build --tests --frozen --keep-going
+		RUST_BACKTRACE=full cargo test --tests --frozen --no-fail-fast || true
+		# NOTE: we're currently allowing tests to fail here
 		;;
 	*)
-		./target/release/arti --version
+		cargo test --frozen
 		;;
 	esac
 }
@@ -92,10 +102,13 @@ package() {
 }
 
 sha512sums="
-ab76f0d4f293fa31db368d32a2f72a7cdc1b9180b28dc998690246c385f3416e76af6139113f7fb46d1d20c60f07a7a2c248f21a478a1fd3b6dd632ea3d3a9d9  arti-1.4.5.tar.gz
-0734521b50b43db382cb895788683a47434db563d970ab2f17687d289e50cf6e9fa8db8515e87d73f34f7353869a99ef8076ebce2b2137f71d36eb71c0c2aa02  32b_arti_example_config_patch
-a68d7c99b1d1d73b4c8c725d7c69486bb732b3b2c28df339f2e56f842c17417aa89fe8ba41f1017bd4c7e550e1e8a2b886071b8f96c0e2863855698cb8767810  disable_system_time_conversion_patch
+8ce71d9d1c12611c9c0ef4ac652299fa2e0724beac8aded48accf5cf9dadfc5807f53e8dc146705d1793f7fcc8cc74f647e4b2e1ef2c4bbaf7391b8740503991  arti-1.5.0.tar.gz
+921aefe7501ef60c1854d8ad23d820fef939fad6a4fc312a09cc91d0c979abd006d03a39956654c9852ffe00255a1bca675072861ab11f0c56381ad13f8f1b26  arti-example-config.patch
+0143eb57b6155cfdfdce73e8f9b6afb08e6d7fa673afa8d46a0b7bb1074c38fa53c1ba71cc691814f78af74b21ebb86731212d4e6338a43d58e38b65607401b3  bump_rustix_crate.patch
 a95b255dfd3624d4d543def7da88c266b2451dd78290bfd02f6ec7bc125c2aef17f89f8dc20b93b630cb886b8397d3c6980704a93efe5697381f0c6c6ac7d47c  disable-access_symlink-test.patch
 beb28ae96d01978c26112cd72d745fb146daeca73183350530e7bbd2a8c7bbc7ca89ca8c31e37fad2e6ac41043fe6524ac6c860e2bea3beaa90265daf3c0f8b1  no-journald-build.patch
+36cb4e29637466c4ecf39dab48f397f3baa2a1e701b313b5f49b46a9206c911bb10969455a9bc1ef7c91e3687ed1554e5b3e788cd91fd51110f6f3cd4871dac4  32b_arti_example_config_patch
+995dea23df8212c04fde61f402a10ba15a0b4796b8dded7935e362c70601e71654d71a79ef071f5ebe9c6d4b21e7ad448ce8361ef6fdb7c5c4bbfd42c8216a5e  32b_time_conversion_tests_patch
+2b1723a1678f13c6463295427a939e496a8368358bb407f5a502b667c379f7180f734099d812e0e71a4cedf59fe1ddc589b0e13c4bc3f847e984ee60d783856d  32b_tor-memquota_patch
 c6e214875455b1101aaade6a3ec2d9d0653abd1cf49b3b562da1c8ebc7b3a6bee708540cfa1c5a60c1b3bfb6921bc064504baba2dde50010e896c708a0a8f352  arti.initd
 "
