testing/linux-sophgo: upgrade to 6.1.88
- re-apply 3 reverted commits for HIGHMEM
- merge in 6.1.88
- refactor to use patch, simiar to what we do with rpi kernel

ref: https://github.com/sophgo/linux-riscv/issues/117

diff --git a/testing/linux-sophgo/APKBUILD b/testing/linux-sophgo/APKBUILD
--- a/testing/linux-sophgo/APKBUILD
+++ b/testing/linux-sophgo/APKBUILD
@@ -2,8 +2,11 @@
 
 _flavor=sophgo
 pkgname=linux-$_flavor
-pkgver=6.1.80_git20240328
-_commit=83ab3eda46e651464f2715455ae66711882be116
+pkgver=6.1.88
+case $pkgver in
+	*.*.*)	_kernver=${pkgver%.*};;
+	*.*)	_kernver=$pkgver;;
+esac
 pkgrel=0
 arch=riscv64
 pkgdesc="Linux Sophgo kernel"
@@ -15,11 +18,56 @@ makedepends="$_depends_dev sed installkernel bc linux-headers linux-firmware-any
 	diffutils findutils zstd pahole python3 gcc>=13.1.1_git20230624"
 options="!strip	!check"
 license="GPL-2.0-only"
-source="$pkgname-$pkgver.tar.gz::https://github.com/sophgo/linux-riscv/archive/$_commit.tar.gz
+source="https://cdn.kernel.org/pub/linux/kernel/v${pkgver%%.*}.x/linux-$_kernver.tar.xz
+	https://cdn.kernel.org/pub/linux/kernel/v${pkgver%%.*}.x/patch-$pkgver.xz
+	https://dev.alpinelinux.org/archive/sophgo-patches/sophgo-$pkgver-alpine.patch
 	sophgo.riscv64.config
 	"
-builddir="$srcdir"/linux-riscv-$_commit
-arch=riscv64
+builddir="$srcdir"/linux-$_kernver
+
+prepare() {
+	local _patch_failed=
+	cd "$srcdir"/linux-$_kernver
+	if [ "${pkgver%.0}" = "$pkgver" ]; then
+		msg "Applying patch-$pkgver.xz"
+		unxz -c < "$srcdir"/patch-$pkgver.xz | patch -p1 -N
+	fi
+
+	# first apply patches in specified order
+	for i in $source; do
+		case $i in
+		*.patch)
+			msg "Applying $i..."
+			if ! patch -s -p1 -N -i "$srcdir"/${i##*/}; then
+				echo $i >>failed
+				_patch_failed=1
+			fi
+			;;
+		esac
+	done
+
+	if ! [ -z "$_patch_failed" ]; then
+		error "The following patches failed:"
+		cat failed
+		return 1
+	fi
+
+	# remove localversion from patch if any
+	rm -f localversion*
+
+	local flavor=
+	for flavor in $_flavors; do
+		local _builddir="$srcdir"/build-$flavor.$CARCH
+		mkdir -p "$_builddir"
+		echo "-$pkgrel-$flavor" > "$_builddir"/localversion-alpine
+		_genconfig $flavor
+		make -C "$srcdir"/linux-$_kernver \
+			O="$_builddir" \
+			ARCH="$_carch" \
+			olddefconfig
+		_verifyconfig $flavor
+	done
+}
 
 build() {
 	unset LDFLAGS CFLAGS CPPFLAGS CXXFLAGS
@@ -145,6 +193,8 @@ dev() {
 		"$subpkgdir"/lib/modules/"$_abi_release"/build
 }
 sha512sums="
-24a4f4ec9857fcca62b43b0bc62a0ec3b4fb361308fd98075a9f8ba976c10f43add551482a03d27a381b688698fc0a7435d307b015d024c7c18f13d4d040de05  linux-sophgo-6.1.80_git20240328.tar.gz
+6ed2a73c2699d0810e54753715635736fc370288ad5ce95c594f2379959b0e418665cd71bc512a0273fe226fe90074d8b10d14c209080a6466498417a4fdda68  linux-6.1.tar.xz
+a21407510b7e4e82e31080f893ae3b2cba883052602ca2db816be7b1e0ffdcb04f9aa8f75d691ef49f1e25833cca5d2068c04e7558e9cff857029918929bcba5  patch-6.1.88.xz
+032f539fc2f296a838697cfa331135e084c2a4eb839d310d099b4ee755105d6861982c027863084855b46cc68cf806c6cef154a5eb8c7404e383ed0379ac0ca1  sophgo-6.1.88-alpine.patch
 c06c0822898247a247bdb6cc9ebe954c1edd15376fe8ffc2c595dfd1cb2e7b63cf52b7a25fc0227b6f9681d546d690134b43e2d3bfb972e6b65696b0ff45e188  sophgo.riscv64.config
 "
