testing/dotnet6-build: add testsuite, patch update

diff --git a/testing/dotnet6-build/APKBUILD b/testing/dotnet6-build/APKBUILD
--- a/testing/dotnet6-build/APKBUILD
+++ b/testing/dotnet6-build/APKBUILD
@@ -9,10 +9,36 @@
 
 pkgname=dotnet6-build
 pkgver=6.0.103
-pkgrel=1
+pkgrel=2
 
 # Tag of tarball generator. This may change from usual due to mistakes from upstream
 _installertag=v$pkgver-source-build
+
+# Test suite tags
+_testtag=6207e217336d4f9c92add85b310c8a4b1ac0e6b1
+_turkeytag=v11
+
+# Test suite disable flags
+# following tests can only work after packaging step
+_disabled_tests="man-pages distribution-package bash-completion"
+# test broken: no musl release for omnisharp
+_disabled_tests="$_disabled_tests omnisharp"
+# test broken: permission issue on lxc / pipelines
+_disabled_tests="$_disabled_tests createdump-aspnet workload"
+# liblttng-ust_sys-sdt.h: no 'NT_STAPSDT' on Alpine's lttng-ust package
+# lttng: known issue, see https://github.com/dotnet/runtime/issues/57784
+_disabled_tests="$_disabled_tests liblttng-ust_sys-sdt.h lttng"
+# {bundled,system}-libunwind: use system version on all but aarch64/armv7, as broken
+# see https://github.com/redhat-developer/dotnet-regular-tests/issues/113
+case $CARCH in
+	aarch64|armv7)_disabled_tests="$_disabled_tests system-libunwind";;
+	*)_disabled_tests="$_disabled_tests bundled-libunwind";;
+esac
+# publish-ready-to-run: broken due to crossgen2 nupkg on musl-arm64 / musl-arm platform being broken
+# should be fixed with https://github.com/dotnet/runtime/pull/66814
+case $CARCH in
+	aarch64|armv7)_disabled_tests="$_disabled_tests publish-ready-to-run publish-ready-to-run-linux";;
+esac
 
 # this should match what is sourced by source-build's ./prep.sh script
 # and, at the very least, the artifacts version sourced, as defined in
@@ -29,21 +55,24 @@ _patches="
 	build_arm-build.patch
 	build_copy-sbrp.patch
 	build_musl-build-fix.patch
+	check_alpine-support.patch
 	command-line-api_fix-musl-build.patch
 	command-line-api_use-work-tree-with-git.patch
 	fsharp_use-work-tree-with-git.patch
 	installer_arm-build.patch
 	installer_forgotten-MicrosoftAspNetCoreAppRuntimePac.patch
 	installer_musl-build-fix.patch
+	installer_portable-runtime-id.patch
 	installer_reprodicible-tarball.patch
-	runtime_aarch64-armv7-armhf-lld-fix.patch
 	runtime_detect-armv8.patch
 	runtime_disable-package-validation.patch
-	runtime_force-microsoftnetcoreilasmpackageruntimeid-as-musl.patch
+	runtime_lld-fix.patch
 	runtime_non-portable-distrorid-fix-alpine.patch
 	runtime_rid-alpine-316.patch
-	sdk_telemetry-optout.patch
+	runtime_x86-64-use-system-libunwind.patch
 	sdk_add-zsh-compdef-completion-script.patch
+	sdk_portable-runtime-id.patch
+	sdk_telemetry-optout.patch
 	vstest_use-work-tree-with-git.patch
 	xliff-tasks_use-work-tree-with.git.patch
 	"
@@ -62,6 +91,21 @@ arch="x86_64 aarch64 armv7"
 url=https://www.microsoft.com/net/core
 license="MIT"
 _bootstrappkg="bootstrap"
+checkdepends="
+	babeltrace
+	binutils
+	coreutils
+	file
+	gawk
+	jq
+	lttng-tools
+	npm
+	procps
+	sed
+	strace
+	util-linux-misc
+	which
+"
 makedepends="
 	bash
 	clang
@@ -80,7 +124,9 @@ makedepends="
 	libxml2-dev
 	libxml2-utils
 	linux-headers
+	lldb
 	lldb-dev
+	lld
 	lld-dev
 	llvm-dev
 	lttng-ust-dev
@@ -91,10 +137,16 @@ makedepends="
 # packages artifacts if building bootstrap
 [ "$_bootstrappkg" = "stage0" ] && subpackages="$pkgname-artifacts:artifacts:noarch"
 
-options="!check" # No test suite
-source="source-build-tarball-$pkgver.tar.gz::https://tarball $_patches"
+source="
+	source-build-tarball-$pkgver.tar.gz::https://tarball
+	source-build-testssuite.tar.gz::https://github.com/redhat-developer/dotnet-regular-tests/archive/$_testtag.tar.gz
+	source-build-turkey.tar.gz::https://github.com/redhat-developer/dotnet-bunny/archive/refs/tags/$_turkeytag.tar.gz
+	$_patches
+	"
 builddir="$srcdir"/source-build-tarball-$pkgver
 _artifactsdir="/usr/share/dotnet/artifacts/${_bootstrapver%-*}"
+_checkdir="$srcdir/dotnet-bunny-${_turkeytag/v}"
+_testdir="$srcdir"/dotnet-regular-tests-$_testtag
 _cli_root="$srcdir"/bootstrap
 
 # custom function that converts Alpine arch syntax to dotnet arch syntax
@@ -129,12 +181,17 @@ _patch() {
 				unset arch_spec
 				for j in ${arch/_/-}; do [ -z "${i##*"$j"*}" ] && local arch_spec=true; done
 				# if arch specific, checks if patch is applicable to this exact arch
-				if [ -n "${i##*"$CARCH"*}" ] && [ "$arch_spec" ]; then continue; fi
+				if [ -n "${i##*"${CARCH/_/-}"*}" ] && [ "$arch_spec" ]; then continue; fi
 
 				msg "Applying $i to $package"
 				cd "$builddir"
-				[ "$package" = "build" ] || { cd src/$package.* || { echo "$package does not exist for patch"; failed=$failed $i; continue; }; }
+				case $package in
+					check*)cd "$_testdir" || { echo "$_testdir does not exist"; failed=$failed $i; continue; };;
+					build*)cd "$builddir";;
+					*) cd src/$package.* || { echo "$package does not exist for patch"; failed=$failed $i; continue; };;
+				esac
 				patch -Np1 -i "$srcdir/$(filename_from_uri $i)" || failed="$failed $i"
+				cd "$builddir"
 			;;
 		esac
 	done
@@ -323,6 +380,45 @@ build() {
 		-- $args | tee -a "$builddir"/build.log
 }
 
+check() {
+	msg "Unpacking produced dotnet"
+	export DOTNET_ROOT="$_checkdir/release"
+	if [ ! -d "$DOTNET_ROOT" ]; then
+		mkdir -p "$DOTNET_ROOT"
+		tar -xzf "$builddir"/artifacts/$_dotnet_arch/Release/dotnet-sdk-$_pkgver_macro*.tar.gz -C "$DOTNET_ROOT" --no-same-owner
+	fi
+	export PATH="$DOTNET_ROOT:$PATH"
+	# some files either should or should not have executable bits
+	# (done again during packaging - this is for tests)
+	_fix_executable "$DOTNET_ROOT"
+
+	msg "Building turkey test suite"
+	if [ ! -d "$_checkdir"/turkey ]; then
+		cd "$_checkdir"/Turkey
+		dotnet publish \
+			-f netcoreapp3.1 \
+			-c Release \
+			-p:VersionPrefix=${_turkeytag/v} \
+			-p:VersionSuffix="$(git rev-parse --short HEAD)" \
+			-o "$_checkdir"/turkey
+	fi
+
+	msg "Running test suite"
+	cd "$_testdir"
+	for i in $_disabled_tests; do
+		[ -d "$i" ] && sed -i 's|"enabled": true|"enabled": false|' $i/test.json
+	done
+	dotnet "$_checkdir"/turkey/Turkey.dll || local ERROR=true
+	if [ $ERROR ]; then
+		msg "Check error reported, dumping logs"
+		for i in *.log; do
+			msg "Dumping $i"
+			cat "$i"
+		done
+		return 1
+	fi
+}
+
 package() {
 	local subdir=${pkgname/*-}
 	local targetdir="$pkgdir"/usr/share/dotnet/$subdir/$pkgver
@@ -369,25 +465,30 @@ artifacts() {
 
 sha512sums="
 a64dd7ff11e1f757320c6f59aaef9f0d2025da8dd4e701aded988d3bcbb01ad7130373b9307a194b3a180330a0daa07f7f2b7947d3411a57c3c5ad22a5351e73  source-build-tarball-6.0.103.tar.gz
+b5072009d5d1639645a78fef61643ed7db981fdc9e1c99f8bdcdabb49a9210c64c67a3cb02af4eaded4bf92fce4e418c50c4d5567cedbe7773d27307905e210c  source-build-testssuite.tar.gz
+5890ef0edc5b6f5e020cedc71be438039c8a2e19c5e71aa538c7fe4046560eea521a621d52638ff1312a398847414fefe311f2f9ac520765472517fab542c419  source-build-turkey.tar.gz
 a2b21c38ed739f9bd18b39a28ef21b940ae32beeb2c8f99575289111e5ecaae40e017a500b3b452ef5df7c7e12dff2f8385acada92ca7507d1ed351c6aa9e311  aspnetcore_musl-build-fix.patch
 e81cd08bd87bcacb9037959c29cb8457ce010a3bce3127eaeaabbd56552d5817b824949320ad4f9bdc582f5edf9e0f8072017b94e40f7606181c51bc93298190  build_arm-build.patch
 bbb72fd61156611c0dd87f3d46e7cb36e0d506da84ea466c5e26513e49abf6b5523c87421bcdef85f06a50488cfed5d73b618e1212b35aad82fe2d43b19da3d9  build_copy-sbrp.patch
-731003042fa864227520126d617b867e7ccfc89ae468fde5563d429b93f46e791ef1c7fd785a72fe739ec3c09c8f7a8fd20dbdc3e4a12f1857eacde376dd0520  build_musl-build-fix.patch
-7806bc888295dbc127b43384511719ef19b0a9b032b4efdd6ea619c0ba105eb7aadf6fa35ba0cb43a4cd98f2267e9f0905f9d574fa3666b634efd5591b6e8212  command-line-api_fix-musl-build.patch
+8812aa5c60d20737a5b2a808e6ac7f72bcb3c7810bb28c6c1714b62c286f8ceb24c2ab5745b09367208850feb600edf94a22a2288d5b5a1d1aca9575fb63aefc  build_musl-build-fix.patch
+c2e4f232f049e3e29b11f751b59bb2750be9d265f3cd93be5a767cdd1c35cc9630a4ca77cfc0c8d23deb913f1d16f2668dde40c5ae6f5e22e41da317aaf045fb  check_alpine-support.patch
+ce36d0233d33cdc96888a64ab83a4099f877413269bcb5602704cedfb6aa89bf6d86157545f6f6243c226b2d714acf66a2bcfb65576afd0c6cda345b76bb5c07  command-line-api_fix-musl-build.patch
 71612ac1d9933335583cf722dc5ecfb37739f662a165cd2afb62bf342e83946955269370da57d3295fa4f781683a2fb6027068584b996efcb33d71e18f7191e2  command-line-api_use-work-tree-with-git.patch
 06ed5091e461c160930746768a1f296bdf7f876b0578cdeb93077e623212c0c535b24e406f9408c402e83eac361a33dba2d7dda7ce7140dd23061ebd8a4a466d  fsharp_use-work-tree-with-git.patch
 f198924d1c9cf22288fb99072e06bc5ce1eccac5cb7361e8f7b3973e6399db50f141aaa8a2dda07c0153208e74819c082a7a74d58785caa0cb2c1efcef28f21b  installer_arm-build.patch
 9724b8b4cb52ac41e7d7a49a0dd2c9937ecf5dc096a123f8cbc5302bbb256ccf440cfa12bfba8295070d7eaac25406fa054e2dce8023257da4d2aeb3c54fe6f3  installer_forgotten-MicrosoftAspNetCoreAppRuntimePac.patch
-d4ab53d241163e83986895f9abd0faf5a35182791057074b3bc446004aa67845aaf1952a69f7f40a835a5858d6018d30418237d29bc2df7ff02da9bf603655b8  installer_musl-build-fix.patch
+f1f10017830e941ff42c28c2f764e489ab02800b528ec89c23c7cf5145225e2956a8db044bc7bac08fc87fa5bd3700ba49df952df09d3e46705dec6bcecb40f5  installer_musl-build-fix.patch
+f4c164256adab18dad187243041416ab612af566501db96069a4c14e4a35ae2fe81f07ec8535b4ff132625423b03ab4dfe3892aefa59fa0494eba6723ba72929  installer_portable-runtime-id.patch
 fe85d6ee786b74c90d69fe3fed03352570f96613ab03cf15d12530da6b98dffaff8cc9ece3044679486b97841481ece4359b80f81b82e7c96fe1dfc8fb6e2945  installer_reprodicible-tarball.patch
-dda6b463af8e0c8342b9c0d1a584f6d6410fb48df9fb0ef3c07d5ee7eb4abf2a29a01bf7a39fc70c2f5986c0b24c7bfe602cbfbeb1157cb0e0fb0eaa7fb03d1c  runtime_aarch64-armv7-armhf-lld-fix.patch
 2e79e27b201a3e4423d63666b3dd575d0cb5ddbe258af24d9a2d0f9eb4cc8d177070249cfd08536fa7c3c6debdf939239a7e2c1aadd692d3e903bbb168f241b5  runtime_detect-armv8.patch
 79dacbaeb9af252e515028f800efc5c1628be9290007418bf4a219f49d4264b2abab2a89af6cd9ff3c74451fe40d6811f7d3c13b9237da187c419295f4ba1280  runtime_disable-package-validation.patch
-cb946dfb27eace2cd5204c77fc7e459c40fac8af364635f543284819856b479470839fa0da8e175c0c75268f219e1dfc4d9fb3d0f707553b67d8b80bbe18d3c4  runtime_force-microsoftnetcoreilasmpackageruntimeid-as-musl.patch
+dda6b463af8e0c8342b9c0d1a584f6d6410fb48df9fb0ef3c07d5ee7eb4abf2a29a01bf7a39fc70c2f5986c0b24c7bfe602cbfbeb1157cb0e0fb0eaa7fb03d1c  runtime_lld-fix.patch
 adb7537feb742f9b838323336e891b6e92c017215628ab2742841b6ec5945987d76082c6d42746f84062f0e537bb1d74cfa3989866fb105b9608af23abf17753  runtime_non-portable-distrorid-fix-alpine.patch
 1c737579bbc8152cb376632781188e543f4b64920adfa537d313366d55f23c896ecd61e366b5e801cd85441aadab8e61b9b775532e829cb347749279c8028902  runtime_rid-alpine-316.patch
-678d13b75a4839a6bfbfd9cdfa057b724fd82c28561b015dfba0d34509b32ad9a2d0946e6b657d7e5d4d1bcea96aafc51f91a4749186895f50d3aba34a4c4954  sdk_telemetry-optout.patch
+e8fba8748c600696a529dd9b861b2e4bffed9f6a56c1e6ec58c1444b567b92a00e6c310f835eb7915db5f924409782d6ec3d7ae98082bde22401ce7836ee7acb  runtime_x86-64-use-system-libunwind.patch
 55afa9c74be6f5a87f1ff5aa44caad094cf620eb4388f6407218acf3d58a878f5565a0e875e95c3dbe0efca1879c120ee4b8076c521bfc9d6069a652c4a4fdd8  sdk_add-zsh-compdef-completion-script.patch
+532534ed88fda70b5088b655af00a7218c72f99a65b35194ebcd960b354b24f043c4b63e72b915aaf69ba847f7befa7d650495a0741d7526accb58b425f74a26  sdk_portable-runtime-id.patch
+2d651813c6a46e885636fe141d90a33c92d0fa450611cadd944b45ec6929a169e49a6cba18afdd708e3359d5ee204f1c1f6e3bfce2ba9d1bdb083edf78d0337e  sdk_telemetry-optout.patch
 d41ed2c7f4b81be2770d1c6b4bba17cea0772131bee994ebce9ca7acc302b2c15cc1adac6a814b866af04728cd4beb0ca411d218d113922fe32001c485b89c67  vstest_use-work-tree-with-git.patch
 4d85a411c4add10072c8b411e05b9ece4696c9409c9a363a0f5ecf2adc6ccb815d868c96941da31a6c4e9d981cede144222155eadac1fbed851989086835d101  xliff-tasks_use-work-tree-with.git.patch
 "
