testing/keepassxc-proxy-static: build with our rustc...
...and enable on more arches.

diff --git a/testing/keepassxc-proxy-static/APKBUILD b/testing/keepassxc-proxy-static/APKBUILD
--- a/testing/keepassxc-proxy-static/APKBUILD
+++ b/testing/keepassxc-proxy-static/APKBUILD
@@ -1,32 +1,30 @@
 # Contributor: Jakub Jirutka <jakub@jirutka.cz>
 # Maintainer: Jakub Jirutka <jakub@jirutka.cz>
-#
-# CAUTION: Don't move this to the community repository until #12941 is fixed,
-# so it can be built with cargo+rustc from aports!
 pkgname=keepassxc-proxy-static
 _projname=keepassxc-proxy-rust
 pkgver=0_git20220628
 _gitrev=bf4e913100bf4373ce207bc8c371de09b5be38ab
-pkgrel=0
+pkgrel=1
 pkgdesc="A statically linked proxy between Native Messaging browser extension and KeePassXC (for use with Flatpak)"
 url="https://github.com/varjolintu/keepassxc-proxy-rust"
-arch="x86_64"  # limited by rustup, fails to build on aarch64
+arch="x86_64"
+# armhf, armv7, s390x: fails to build
+# riscv64: blocked by rust/cargo
+arch="all !armhf !armv7 !riscv64 !s390x"
 license="GPL-3.0-or-later"
-makedepends="rustup"
+makedepends="cargo"
 install="$pkgname.post-install"
 source="https://github.com/varjolintu/keepassxc-proxy-rust/archive/$_gitrev/$_projname-$_gitrev.tar.gz
+	update-deps.patch
 	keepassxc-proxy-install.in
 	"
 builddir="$srcdir/$_projname-$_gitrev"
-options="net !check"  # no tests provided
-
-export CARGO_HOME="$srcdir/.cargo"
-export RUSTUP_HOME="$srcdir/.rustup"
 
 export CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1
 export CARGO_PROFILE_RELEASE_LTO="true"
 export CARGO_PROFILE_RELEASE_OPT_LEVEL="z"
 export CARGO_PROFILE_RELEASE_PANIC="abort"
+export RUSTFLAGS="-C target-feature=+crt-static"
 
 prepare() {
 	default_prepare
@@ -34,14 +32,21 @@ prepare() {
 	sed "s/@@VERSION@@/$pkgver/" "$srcdir"/keepassxc-proxy-install.in \
 		> "$srcdir"/keepassxc-proxy-install
 
-	# TODO: This is a workaround for https://gitlab.alpinelinux.org/alpine/aports/-/issues/12941.
-	# Remove it and build with cargo+rustc from aports (using `-C target-feature=+crt-static`)
-	# after it's fixed.
-	rustup-init --target "$CARCH-unknown-linux-musl" --profile minimal --no-modify-path -y
+	cargo fetch --locked
 }
 
 build() {
-	PATH="$CARGO_HOME/bin:$PATH" cargo build --locked --release
+	cargo build --frozen --release
+}
+
+check() {
+	local bin='target/release/keepassxc-proxy'
+
+	if ! file $bin | grep -Fqw 'static-pie linked'; then
+		file $bin
+		error "$bin is not a static binary!"
+		return 1
+	fi
 }
 
 package() {
@@ -51,5 +56,6 @@ package() {
 
 sha512sums="
 cfb0229566c81df6604f91af6340684e6ff5877474b40e3247aedd37c21d5ab7121bb70dc38b68640848b7f0b11890f9b6c9e81ad316aa26adf9a26b21223ba4  keepassxc-proxy-rust-bf4e913100bf4373ce207bc8c371de09b5be38ab.tar.gz
+2643b73e433fd49f4e3156f071f0d320e5192362fc4b6ecc743d64ef72ad8eeff2e21f6ecd1a3c99864cfb9cbe496867fcd61978e3e8dca5ac8dfdd6ef5a56d8  update-deps.patch
 3d31ed8d2a430f1e61960990128a9b7277106fcf74c16952ccefdeca3a3ba5cb9e6917d08d801bff1d4d354566689bda8f54d10f3711b03063d01374913c0387  keepassxc-proxy-install.in
 "
