community/py3-rpy2: upgrade to 3.6.0

diff --git a/community/py3-rpy2/APKBUILD b/community/py3-rpy2/APKBUILD
--- a/community/py3-rpy2/APKBUILD
+++ b/community/py3-rpy2/APKBUILD
@@ -2,8 +2,9 @@
 # Maintainer: Antoine Martin (ayakael) <dev@ayakael.net>
 pkgname=py3-rpy2
 _pyname="rpy2"
-pkgver=3.5.17
-pkgrel=1
+pkgver=3.6.0
+_gittag=RELEASE_${pkgver//./_}
+pkgrel=0
 pkgdesc="A very simple, yet robust, Python interface to the R Programming Language"
 url="https://pypi.python.org/project/rpy2"
 # riscv64, loongarch64: R missing
@@ -27,32 +28,44 @@ makedepends="
 	"
 checkdepends="
 	py3-pytest
+	ipython
+	py3-pandas
 	"
-source="$pkgname-$pkgver.tar.gz::https://pypi.io/packages/source/r/rpy2/rpy2-$pkgver.tar.gz
-	r-4.5.0.patch
-	"
-builddir="$srcdir"/$_pyname-$pkgver
+source="$pkgname-$_gittag.tar.gz::https://github.com/rpy2/rpy2/archive/refs/tags/$_gittag.tar.gz"
+builddir="$srcdir"/$_pyname-$_gittag
 subpackages="$pkgname-pyc"
+# version 3.6.0 split the package in two
+provides="py3-rpy2-rinterface=$pkgver-r$pkgrel py3-rpy2-robjects=$pkgver-r$pkgrel"
 
 build() {
-	gpep517 build-wheel \
-		--wheel-dir .dist \
-		--output-fd 3 3>&1 >&2
+	for i in ./ rpy2-rinterface rpy2-robjects; do
+		cd "$builddir"/$i
+		gpep517 build-wheel \
+			--wheel-dir "$builddir"/.dist \
+			--output-fd 3 3>&1 >&2
+	done
 }
 
 check() {
 	python3 -m venv --clear --without-pip --system-site-packages .testenv
-	.testenv/bin/python3 -m installer .dist/*.whl
-	# test_rendertofile | test_rendertobytes_plit: Segfaults in build server
-	# test_find_onlyfromloadedlibrary:  Error in detach("package:survival") : invalid 'name' argument
-	.testenv/bin/python3 -m pytest -v -k 'not test_rendertofile and not test_rendertobytes_plot and not test_find_onlyfromloadedlibrary'
+	for i in rpy2-rinterface rpy2-robjects; do
+		cd "$builddir"/$i
+		../.testenv/bin/python3 -m installer "$builddir"/.dist/${i/-/_}*.whl
+		# test_find_onlyfromloadedlibrary:  Error in detach("package:survival") : invalid 'name' argument
+		../.testenv/bin/python3 -m pytest -v \
+			--deselect src/rpy2/rinterface/tests/test_environment.py::test_find_onlyfromloadedlibrary
+	done
 }
 
 package() {
-	python3 -m installer --destdir="$pkgdir" .dist/*.whl
+	for i in .dist/*; do
+		python3 -m installer --destdir="$pkgdir" $i
+	done
+	for i in rinterface/tests robjects/tests ipython/tests; do
+		rm -R "$pkgdir"/usr/lib/python*/site-packages/rpy2/$i
+	done
 }
 
 sha512sums="
-77cd6b821bd26d392e4a46346c31c5caeb4e75a312f671fa9031e1695a5b986c6b48a1ebcd4a3d3445e596ff2c1287fed393d51811545868eb6b08ec7c6c347a  py3-rpy2-3.5.17.tar.gz
-128c5cd230e8c7dc807100bf73f904aca6bc6df4c81bf221ddd303d8232bfebae769a9ecadb48a76f0b33a04fdc615fd352a1b93dfdad763b7cb07aa7f496a43  r-4.5.0.patch
+2084c23dc3f9240082214563b534698cc5d7a6f7e3df1f5256a36dcf5752e4de84fb33caa8ed571d764b7eae198335fe0d81d81ff1a355d567cec758426a6b8c  py3-rpy2-RELEASE_3_6_0.tar.gz
 "
