just moved the checksum func

diff --git a/abuild b/abuild
--- a/abuild
+++ b/abuild
@@ -424,6 +424,16 @@ builddeps() {
 	done
 }
 
+checksum() {
+	local s files
+	fetch
+	for s in $source; do
+		files="$files ${s##*/}"
+	done
+	md5sums="$(cd "$srcdir" && md5sum $files)" || die "md5sum failed"
+	echo "md5sums=\"$md5sums\""
+}
+
 usage() {
 	echo "$(basename $0) $abuild_ver"
 	echo "usage: $0 [options] [cmd] ..."
@@ -450,16 +460,6 @@ usage() {
 	echo "  up2date     Compare target and sources dates"
 	echo ""
 	exit 0
-}
-
-checksum() {
-	local s files
-	fetch
-	for s in $source; do
-		files="$files ${s##*/}"
-	done
-	md5sums="$(cd "$srcdir" && md5sum $files)" || die "md5sum failed"
-	echo "md5sums=\"$md5sums\""
 }
 
 APKBUILD="${APKBUILD:-./APKBUILD}"
