Rename "md5" variable to "md5sums" so its more like PKGBUILD.

diff --git a/abuild b/abuild
--- a/abuild
+++ b/abuild
@@ -56,7 +56,7 @@ checkdeps() {
 }
 
 checkmd5() {
-	( cd "$SRCDEST" && echo "$md5" | awk '$2 == "'$1'" { print $0 } ' \
+	( cd "$SRCDEST" && echo "$md5sums" | awk '$2 == "'$1'" { print $0 } ' \
 		| md5sum -c )
 }
 
@@ -92,7 +92,7 @@ fetch() {
 # unpack the sources
 unpack() {
 	local u
-	[ -z "$md5" ] && die "Use 'abuild checksum >>$APKBUILD' to generate a checksum"
+	[ -z "$md5sums" ] && die "Use 'abuild checksum >>$APKBUILD' to generate a checksum"
 	mkdir -p "$srcdir"
 	for u in $source; do
 		local s="$SRCDEST/${u##*/}"	# $(basename $s)
@@ -274,8 +274,8 @@ checksum() {
 	for s in $source; do
 		files="$files ${s##*/}"
 	done
-	md5="$(cd "$SRCDEST" && md5sum $files)" || die "md5sum failed"
-	echo "md5=\"$md5\""
+	md5sums="$(cd "$SRCDEST" && md5sum $files)" || die "md5sum failed"
+	echo "md5sums=\"$md5sums\""
 }
 
 APKBUILD="${APKBUILD:-./APKBUILD}"
