various: s/echo/msg/, s/echo/error/, tweak error messages

diff --git a/abuild-sign.in b/abuild-sign.in
--- a/abuild-sign.in
+++ b/abuild-sign.in
@@ -37,10 +37,8 @@ do_sign() {
 		rm -f "$tmptargz" "$sig"
 		chmod 644 "$tmpsigned"
 		mv "$tmpsigned" "$i"
-		if [ -z "$quiet" ]; then
-			echo "Signed $i"
-		fi
-		) || die "Failed to sign $i"
+		msg "Signed $i"
+		) || die "failed to sign $i"
 	done
 }
 
diff --git a/abump.in b/abump.in
--- a/abump.in
+++ b/abump.in
@@ -35,11 +35,11 @@ do_bump() {
 		# verify APKBUILD
 		(
 		. "$a" || exit 1
-		[ "$pkgname" = "$name" ] || die "$name: APKBUILD has different \$pkgname"
-		type package | grep -q function || die "$name: missing package()"
+		[ "$pkgname" = "$name" ] || die "APKBUILD has different \$pkgname for $name"
+		type package | grep -q function || die "missing package() for $name"
 		case $(apk version --test "$pkgver" "$ver") in
-		'=') die "$pkgname: already at version $pkgver";;
-		'>') die "$pkgname: already at newer version $pkgver";;
+		'=') die "$pkgname is already at version $pkgver";;
+		'>') die "$pkgname is already at newer version $pkgver";;
 		'<') exit 0;;
 		*) exit 1;;
 		esac
@@ -59,7 +59,7 @@ do_bump() {
 fixes #${fixes#\#}
 "
 		fi
-		echo "$message"
+		msg "$message"
 
 		sed -i -e "s/^pkgver=.*/pkgver=$ver/" \
 			-e "s/^pkgrel=.*/pkgrel=0/" \
diff --git a/checkapk.in b/checkapk.in
--- a/checkapk.in
+++ b/checkapk.in
@@ -36,14 +36,14 @@ if ! [ -f "$abuild_conf" ] && ! [ -f "$abuild_userconf" ]; then
 fi
 
 if ! [ -f APKBUILD ]; then
-	die 'This must be run in the directory of a built package.'
+	die 'must be run in the directory of a built package'
 fi
 
 . ./APKBUILD
 
 startdir="$PWD"
 tmpdir=$(mktemp -d -t checkpkg-script.XXXXXX)
-cd "$tmpdir" || die "Failed to create temp dir"
+cd "$tmpdir" || die "failed to create temp dir"
 
 for i in $pkgname $subpackages; do
 	_pkgname=${i%:*}
@@ -57,19 +57,19 @@ for i in $pkgname $subpackages; do
 			break
 		fi
 	done
-	[ -f "$filepath" ] || die "could not find $pkgfile"
+	[ -f "$filepath" ] || die "can't find $pkgfile"
 
 	# generate a temp repositories file with only the http repos
 	grep ^http: /etc/apk/repositories > $tmpdir/repositories
 
 	oldpkg=$(apk fetch --repositories-file $tmpdir/repositories --simulate 2>&1 | sed 's/^Downloading //')
 	if [ "${oldpkg}" = "${pkg}" ]; then
-		die "The built package ($_pkgname) is the one in the repo right now!"
+		die "the built package ($_pkgname) is already in the repo"
 	fi
 
 	apk fetch --repositories-file $tmpdir/repositories --stdout $_pkgname \
 		| tar -zt | grep -v '^\.SIGN\.' | sort > filelist-$_pkgname-old \
-		|| die "Failed to download old pkg. Maybe run 'apk update'?"
+		|| die "failed to download old pkg, maybe run 'apk update'?"
 
 	tar -ztf "$filepath" | grep -v '^\.SIGN\.' | sort > "filelist-$_pkgname"
 
