abuild: use new apk-tools (2.x)

diff --git a/abuild b/abuild
--- a/abuild
+++ b/abuild
@@ -8,7 +8,7 @@
 # Depends on: busybox utilities, fakeroot, 
 #
 
-abuild_ver=1.2
+abuild_ver=1.3
 
 # read config
 MAKEAPK_CONF=${MAKEAPK_CONF:-/etc/abuild.conf}
@@ -49,7 +49,7 @@ set_xterm_title() {
 cleanup() {
 	set_xterm_title ""
 	if [ -z "$install_after" ] && [ -n "$uninstall_after" ]; then
-		sudo apk_delete $uninstall_after
+		sudo apk delete $uninstall_after
 	fi
 }
 
@@ -438,7 +438,7 @@ deptrace() {
 	( 	depparse_aports 
 		if [ -z "$upgrade" ]; then
 			# list installed pkgs and prefix with 'i '
-			apk_info | sed 's/-[0-9].*//; s/^/i /'
+			apk info | sed 's/-[0-9].*//; s/^/i /'
 		fi
 	) | awk -v pkgs="$BUILD_BASE $depends $makedepends" '
 
@@ -471,7 +471,7 @@ builddeps() {
 	deps="$BUILD_BASE $depends $makedepends"
 	if [ -z "$recursive" ]; then
 		for i in $deps; do
-			apk_info -e $i || die "Missing dependency $i. Use -r to build recursively"
+			apk info -e $i || die "Missing dependency $i. Use -r to build recursively"
 		done
 		return 0
 	fi
@@ -602,7 +602,7 @@ while [ $# -gt 0 ]; do
 done
 
 for i in $install_after; do
-	sudo apk_add -s -u $PKGDEST/$i-$pkgver-r$pkgrel.apk \
+	sudo apk add $PKGDEST/$i-$pkgver-r$pkgrel.apk \
 		|| die "Failed to install $i"
 done
 
