rename datadir -> sharedir
abuild uses datadir as local variable in various functions. Rename the
global datadir to sharedir to avoid confusion.

diff --git a/abuild.in b/abuild.in
--- a/abuild.in
+++ b/abuild.in
@@ -8,16 +8,16 @@
 #
 
 program_version=@VERSION@
-datadir=@datadir@
+sharedir=@sharedir@
 
 abuild_path=$(readlink -f $0)
 git=$(command -v git) || git=true
 
-if ! [ -f "$datadir/functions.sh" ]; then
-	echo "$datadir/functions.sh: not found" >&2
+if ! [ -f "$sharedir/functions.sh" ]; then
+	echo "$sharedir/functions.sh: not found" >&2
 	exit 1
 fi
-. "$datadir/functions.sh"
+. "$sharedir/functions.sh"
 
 # defaults
 : ${FAKEROOT:="fakeroot"}
@@ -608,7 +608,7 @@ update_config_sub() {
 	find . -name config.sub | (local changed=false; while read f; do
 		if ! ./$f armv6-alpine-linux-muslgnueabihf 2>/dev/null; then
 			msg "Updating $f"
-			cp "$datadir"/${f##*/} "$f" || return 1
+			cp "$sharedir"/${f##*/} "$f" || return 1
 			changed=true
 		else
 			msg "No update needed for $f"
@@ -623,7 +623,7 @@ update_config_guess() {
 			msg "No update needed for $f"
 		else
 			msg "Updating $f"
-			cp "$datadir"/${f##*/} "$f" || return 1
+			cp "$sharedir"/${f##*/} "$f" || return 1
 			changed=true
 		fi
 	done; $changed)
diff --git a/apkgrel.in b/apkgrel.in
--- a/apkgrel.in
+++ b/apkgrel.in
@@ -7,13 +7,13 @@
 #
 
 program_version=@VERSION@
-datadir=@datadir@
+sharedir=@sharedir@
 
-if ! [ -f "$datadir/functions.sh" ]; then
-	echo "$datadir/functions.sh: not found" >&2
+if ! [ -f "$sharedir/functions.sh" ]; then
+	echo "$sharedir/functions.sh: not found" >&2
 	exit 1
 fi
-. "$datadir/functions.sh"
+. "$sharedir/functions.sh"
 
 
 show_plain() {
diff --git a/newapkbuild.in b/newapkbuild.in
--- a/newapkbuild.in
+++ b/newapkbuild.in
@@ -7,13 +7,13 @@
 #
 
 program_version=@VERSION@
-datadir=@datadir@
+sharedir=@sharedir@
 
-if ! [ -f "$datadir/functions.sh" ]; then
-	echo "$datadir/functions.sh: not found" >&2
+if ! [ -f "$sharedir/functions.sh" ]; then
+	echo "$sharedir/functions.sh: not found" >&2
 	exit 1
 fi
-. "$datadir/functions.sh"
+. "$sharedir/functions.sh"
 
 
 is_url() {
@@ -246,10 +246,10 @@ newaport() {
 
 	# Copy init.d scripts if requested
 	if [ -n "$cpinitd" ]; then
-		cp "$datadir"/sample.initd $pkgname.initd
-		cp "$datadir"/sample.confd $pkgname.confd
-		cp "$datadir"/sample.pre-install $pkgname.pre-install
-		cp "$datadir"/sample.post-install $pkgname.post-install
+		cp "$sharedir"/sample.initd $pkgname.initd
+		cp "$sharedir"/sample.confd $pkgname.confd
+		cp "$sharedir"/sample.pre-install $pkgname.pre-install
+		cp "$sharedir"/sample.post-install $pkgname.post-install
 		install="\$pkgname.pre-install \$pkgname.post-install"
 		source="$source
 	$pkgname.initd
