abuild: dont check md5sum if there are no sources. fix depends_has

diff --git a/abuild b/abuild
--- a/abuild
+++ b/abuild
@@ -78,13 +78,17 @@ sanitycheck() {
 	[ -z "$url" ] && die "Missing url in APKBUILD"
 	[ -z "$license" ] && die "Missing license in APKBULID"
 
-	for i in $source; do
-		md5sums_has ${i##*/} || die "${i##*/} is missing in md5sums"
-	done
+	if [ -n "$source" ]; then
+		for i in $source; do
+			md5sums_has ${i##*/} || die "${i##*/} is missing in md5sums"
+		done
+	fi
 
-	for i in $(echo "$md5sums" | awk '{ print $2 }'); do
-		source_has $i || die "$i is missing in source"
-	done
+	if [ -n "$md5sums" ]; then
+		for i in $(echo "$md5sums" | awk '{ print $2 }'); do
+			source_has $i || die "$i is missing in source"
+		done
+	fi
 
 	# common spelling errors
 	[ -n "$depend" ] && die "APKBUILD contains 'depend'. It should be depends"
@@ -542,6 +546,7 @@ builddeps() {
 # replace the md5sums in the APKBUILD
 checksum() {
 	local s files
+	[ -z "$source" ] && return 0
 	fetch
 	msg "Updating the md5sums in APKBUILD..."
 	for s in $source; do
@@ -605,6 +610,10 @@ list_has() {
 
 options_has() {
 	list_has "$1" $options
+}
+
+depends_has() {
+	list_has "$1" $depends
 }
 
 md5sums_has() {
