abuild: allow help (-h) even if there is no APKBUILD

diff --git a/abuild b/abuild
--- a/abuild
+++ b/abuild
@@ -536,7 +536,7 @@ usage() {
 	echo " -u  Recursively build and upgrade dependencies (using sudo)"
 	echo ""
 	echo "Commands:"
-	echo "  checksum    Generate checksum to be included in $APKBUILD"
+	echo "  checksum    Generate checksum to be included in APKBUILD"
 	echo "  fetch       Fetch sources to \$SRCDEST and verify checksums"
 	echo "  sanitycheck Basic sanity check of APKBUILD"
 	echo "  md5check    Check md5sums"
@@ -555,12 +555,7 @@ usage() {
 	exit 0
 }
 
-
-# source the buildfile
 APKBUILD="${APKBUILD:-./APKBUILD}"
-[ -f "$APKBUILD" ] || die "Could not find $APKBUILD (PWD=$PWD)"
-. "$APKBUILD"
-
 unset force
 unset recursive
 while getopts "fhi:kip:qrs:u" opt; do
@@ -578,6 +573,10 @@ while getopts "fhi:kip:qrs:u" opt; do
 	esac
 done
 shift $(( $OPTIND - 1 ))
+
+# source the buildfile
+[ -f "$APKBUILD" ] || die "Could not find $APKBUILD (PWD=$PWD)"
+. "$APKBUILD"
 
 # If we are handling a sub package then reset subpackages
 if [ -n "$subpkgname" ]; then
