run md5sum creation from $srcdir rather than $SRCDEST

diff --git a/abuild b/abuild
--- a/abuild
+++ b/abuild
@@ -458,7 +458,7 @@ checksum() {
 	for s in $source; do
 		files="$files ${s##*/}"
 	done
-	md5sums="$(cd "$SRCDEST" && md5sum $files)" || die "md5sum failed"
+	md5sums="$(cd "$srcdir" && md5sum $files)" || die "md5sum failed"
 	echo "md5sums=\"$md5sums\""
 }
 
