abuild: improve sanitycheck
- check that md5sums correspond to source
- warn if maintainer is missing

diff --git a/abuild b/abuild
--- a/abuild
+++ b/abuild
@@ -71,6 +71,7 @@ die() {
 
 # check if apkbuild is basicly sane
 sanitycheck() {
+	local i
 	msg "Checking sanity of $APKBUILD..."
 	[ -z "$pkgname" ] && die "Missing pkgname in APKBUILD"
 	[ -z "${pkgname##* *}" ] && die "pkgname contains spaces"
@@ -82,24 +83,30 @@ sanitycheck() {
 	[ -z "$url" ] && die "Missing url in APKBUILD"
 	[ -z "$license" ] && die "Missing license in APKBULID"
 
-	if [ "$(echo $source | wc -l)" -ne "$(echo $md5sums | wc -l)" ]; then
-		die "Number of md5sums does not correspond to number of sources"
-	fi
+	for i in $source; do
+		md5sums_has ${i##*/} || die "${i##*/} is missing in md5sums"
+	done
+
+	for i in $(echo "$md5sums" | awk '{ print $2 }'); do
+		source_has $i || die "$i is missing in source"
+	done
 
 	# common spelling errors
 	[ -n "$depend" ] && die "APKBUILD contains 'depend'. It should be depends"
 	[ -n "$makedepend" ] && die "APKBUILD contains 'makedepend'. It should be makedepends"
+
+	grep '^# Maintainer:' $APKBUILD >/dev/null || warning "No maintainer"
 	return 0
 }
 
 md5check() {
+	local dummy f
 	if [ -z "$source" ]; then
 		return 0
 	fi
 	if [ -z "$md5sums" ]; then
 		die "Use 'abuild checksum' to generate/update the checksum(s)"
 	fi
-
 	if [ "$(echo $source | wc -l)" -ne "$(echo $md5sums | wc -l)" ]; then
 		die "Number of md5sums does not correspond to number of sources"
 	fi
@@ -550,6 +557,14 @@ listpkg() {
 	done
 }
 
+source_has() {
+	local i
+	for i in $source; do
+		[ "$1" = "${i##*/}" ] && return 0
+	done
+	return 1
+}
+
 subpackages_has() {
 	local i
 	for i in $subpackages; do
@@ -571,6 +586,10 @@ list_has() {
 
 options_has() {
 	list_has "$1" $options
+}
+
+md5sums_has() {
+	list_has "$1" $md5sums
 }
 
 # install package after build
