abuild: print a message if aborting due to architecture mismatch.

diff --git a/abuild.in b/abuild.in
--- a/abuild.in
+++ b/abuild.in
@@ -1764,7 +1764,11 @@ uninstalldeps() { undeps; }
 
 all() {
 	if ! [ -n "$force" ]; then
-		check_arch || return 0
+		check_arch
+		if [ $? -ne 0 ]; then
+			echo "Package not available for the target architecture ($CARCH). Aborting."
+			return 0
+		fi
 		check_libc || return 0
 	fi
 	if up2date && [ -z "$force" ]; then
