abuild: improve sanitycheck to check sanity of all checksums

diff --git a/abuild.in b/abuild.in
--- a/abuild.in
+++ b/abuild.in
@@ -190,18 +190,24 @@ default_sanitycheck() {
 				warning "You should not have \$install in source"
 				continue
 			fi
-			md5sums_has ${i##*/} || die "${i##*/} is missing in md5sums"
+			list_has ${i##*/} $md5sums $sha256sums $sha512sums \
+				|| die "${i##*/} is missing in checksums"
 			case "$i" in
 				https://*) makedepends_has wget && warning "wget no longer need to be in makedepends when source has https://" ;;
 			esac
 		done
 	fi
 
-	if [ -n "$md5sums" ]; then
-		for i in $(echo "$md5sums" | awk '{ print $2 }'); do
-			source_has $i || die "$i exists in md5sums but is missing in source"
+	# verify that things listed in checksum also is listed in source
+	local algo=
+	for algo in md5 sha256 sha512; do
+		eval set -- \$${algo}sums
+		while [ $# -gt 1 ]; do
+			local file="$2"
+			shift 2
+			source_has $file || die "$file exists in ${algo}sums but is missing in source"
 		done
-	fi
+	done
 
 	# common spelling errors
 	[ -n "$depend" ] && die "APKBUILD contains 'depend'. It should be depends"
