abuild: move functions to a shared lib

diff --git a/abuild b/abuild
--- a/abuild
+++ b/abuild
@@ -14,6 +14,20 @@ abuild_ver=0.9
 MAKEAPK_CONF=${MAKEAPK_CONF:-/etc/abuild.conf}
 [ -f "$MAKEAPK_CONF" ] && . "$MAKEAPK_CONF"
 
+# source functions
+# if abuild was not run from PATH, then look for func lib at same location
+if [ -z "$FUNCLIB" ]; then
+	FUNCLIB="${0##/*}/functions.sh"
+	[ -f "$FUNCLIB"	] || FUNCLIB=/usr/share/abuild/functions.sh
+fi
+
+if ! [ -f "$FUNCLIB" ]; then
+	echo "$FUNCLIB: not found" >&2
+	exit 1
+fi
+. "$FUNCLIB"
+	
+
 startdir="$PWD"
 srcdir=${srcdir:-"$startdir/src"}
 pkgdir=${pkgdir:-"$startdir/pkg"}
@@ -24,39 +38,6 @@ SRCDEST=${SRCDEST:-$startdir}
 PKGDEST=${PKGDEST:-$startdir}
 
 default_cmds="sanitycheck builddeps clean fetch md5check unpack rootpkg"
-
-#colors
-if [ -n "$USE_COLORS" ]; then
-	NORMAL="\033[1;0m"
-	STRONG="\033[1;1m"
-	RED="\033[1;31m"
-	GREEN="\033[1;32m"
-	YELLOW="\033[1;33m"
-	BLUE="\033[1;34m"
-fi	
-	
-
-# functions
-msg() {
-	local prompt="$GREEN>>>${NORMAL}"
-	local fake="${FAKEROOTKEY:+${BLUE}(fakeroot)${NORMAL} }"
-	local name="${STRONG}${subpkgname:-$pkgname}${NORMAL}"
-	[ -z "$quiet" ] && printf "${prompt} ${fake}${name}: $@\n" >&2
-}
-
-warning() {
-	local prompt="${YELLOW}>>> WARNING: ${NORMAL}"
-	local fake="${FAKEROOTKEY:+${BLUE}(fakeroot)${NORMAL} }"
-	local name="${STRONG}${subpkgname:-$pkgname}${NORMAL}"
-	printf "${prompt} ${fake}${name}: $@\n" >&2
-}
-
-error() {
-	local prompt="${RED}>>> ERROR: ${NORMAL}"
-	local fake="${FAKEROOTKEY:+${BLUE}(fakeroot)${NORMAL} }"
-	local name="${STRONG}${subpkgname:-$pkgname}${NORMAL}"
-	printf "${prompt} ${fake}${name}: $@\n" >&2
-}
 
 set_xterm_title() {
 	if [ "$TERM" = xterm ]; then
