abuild-sign: wrap cd in a subshell, use set -e

diff --git a/abuild-sign.in b/abuild-sign.in
--- a/abuild-sign.in
+++ b/abuild-sign.in
@@ -25,9 +25,11 @@ do_sign() {
 		i=$(readlink -f $f)
 		[ -d "$i" ] && i="$i/APKINDEX.tar.gz"
 		repo="${i%/*}"
-		cd "$repo" || die "Failed to sign $i"
+		(
+		set -e
+		cd "$repo"
 		sig=".SIGN.RSA.$keyname"
-		openssl dgst -sha1 -sign "$privkey" -out "$sig" "$i" || die "Failed to sign $i"
+		openssl dgst -sha1 -sign "$privkey" -out "$sig" "$i"
 		tmptargz=$(mktemp)
 		tar -c "$sig" | abuild-tar --cut | gzip -9 > "$tmptargz"
 		tmpsigned=$(mktemp)
@@ -38,6 +40,7 @@ do_sign() {
 		if [ -z "$quiet" ]; then
 			echo "Signed $i"
 		fi
+		) || die "Failed to sign $i"
 	done
 }
 
