abuild: wait 30 seconds for apk lockfile. improve error reporting

diff --git a/abuild.in b/abuild.in
--- a/abuild.in
+++ b/abuild.in
@@ -811,7 +811,13 @@ builddeps() {
 
 	uninstall_after=".makedepends-$pkgname $uninstall_after"
 	if [ -n "$install_deps" ] && [ -z "$recursive" ]; then
+		# make a --simluate run first to detect missing deps
+		# apk-tools --virtual is no goot at reporting those.
 		$SUDO apk add --repository "$apkcache" \
+			--wait 30 \
+			--simulate --quiet $deps || return 1
+		$SUDO apk add --repository "$apkcache" \
+			--wait 30 \
 			--virtual .makedepends-$pkgname $deps \
 			&& return 0
 	fi
@@ -834,6 +840,7 @@ builddeps() {
 		cd "$dir" && $0 -k -r apkcache || return 1
 	done
 	$SUDO apk add -u --repository "$apkcache" \
+		--wait 30 \
 		--virtual .makedepends-$pkgname $deps
 }
 
@@ -945,12 +952,13 @@ post_add() {
 			post_add $i || return 1
 		fi
 	done
-	$SUDO apk add -u "$pkgf" || die "Failed to install $1"
+	$SUDO apk add --wait 30 -u "$pkgf" || die "Failed to install $1"
 }
 
 installdeps() {
 	local deps i
-	sudo apk add --repository "$apkcache" --virtual .makedepends-$pkgname \
+	sudo apk add --wait 30 --repository "$apkcache" \
+		--virtual .makedepends-$pkgname \
 		$makedepends
 }
 
