abuild: verify that the pkgconf version is valid

diff --git a/abuild.in b/abuild.in
--- a/abuild.in
+++ b/abuild.in
@@ -1092,6 +1092,7 @@ prepare_pkgconfig_provides() {
 		local f=${i##*/}
 		local v=$(PKG_CONFIG_PATH="$dir"/usr/lib/pkgconfig PKG_CONFIG_MAXIMUM_TRAVERSE_DEPTH=1 pkg-config \
 			--modversion ${f%.pc})
+		$APK version --check --quiet $v || die "$i: pkgconf version $v is invalid"
 		echo "$pcprefix${f%.pc}=${v:-0}" >> "$controldir"/.provides-pc
 	done
 }
