abump: print what packages failed

diff --git a/abump.in b/abump.in
--- a/abump.in
+++ b/abump.in
@@ -18,7 +18,7 @@ fi
 
 # version bump packages
 do_bump() {
-	local p rc=0 name ver section message
+	local p rc=0 errors=0 failed= name ver section message
 	local upgrade="${cvelist:+security }upgrade"
 	local a
 	for p; do
@@ -64,9 +64,15 @@ fixes #${fixes#\#}
 		git add APKBUILD
 		git commit -m"$message"
 		)
-		rc=$(( $rc + $? ))
+		if [ $? -ne 0 ]; then
+			errors=$(( $errors + 1 ))
+			failed="$failed $p"
+		fi
 	done
-	return $rc
+	if [ -n "$failed" ]; then
+		error "Failed: $failed"
+	fi
+	return $errors
 }
 
 usage() {
