abump, functions: refactor (and verify) calculation of APKBUILD path

diff --git a/abump.in b/abump.in
--- a/abump.in
+++ b/abump.in
@@ -20,14 +20,22 @@ fi
 do_bump() {
 	local p rc=0 pkgname pkgver section message
 	local upgrade="${cvelist:+security }upgrade"
+	local a
 	for p; do
 		pkgname=${p%-[0-9]*}
 		pkgver=${p#${pkgname}-}
 
+		# calculate APKBUILD's path
+		if [ "${pkgname#*/}" != "$pkgname" ] && ! [ -d "$APORTSDIR/${pkgname%/*} ]; then
+			error "'$p' should be of form 'foo-1.2.3' or 'main/foo-1.2.3'"
+			rc=1; continue
+		fi
+		a=$(aports_buildscript "$pkgname" || die "can't find APKBUILD for $pkgname") || { rc=1; continue; }
+
 		(
 		set -e
 
-		cd $HOME/aports/*/$pkgname
+		cd "${a%/*}"
 		section=${PWD%/*}
 		section=${section##*/}
 
@@ -74,6 +82,8 @@ keep=
 recursive="-r"
 cvelist=
 fixes=
+
+[ -n "$APORTSDIR" ] || error "can't locate \$APORTSDIR"
 
 args=`getopt -o s:Rkqh --long security:,recursive,keep,quiet,help -n "$prog" -- "$@"`
 if [ $? -ne 0 ]; then
