add .editorconfig and fix code formatting

diff --git a/buildlab.in b/buildlab.in
--- a/buildlab.in
+++ b/buildlab.in
@@ -15,32 +15,32 @@ ABUILD_CONF=${ABUILD_CONF:-"$sysconfdir/abuild.conf"}
 [ -f "$ABUILD_CONF" ] && . "$ABUILD_CONF"
 
 default_colors() {
-        NORMAL="\033[1;0m"
-        STRONG="\033[1;1m"
-        RED="\033[1;31m"
-        GREEN="\033[1;32m"
-        YELLOW="\033[1;33m"
-        BLUE="\033[1;34m"
+	NORMAL="\033[1;0m"
+	STRONG="\033[1;1m"
+	RED="\033[1;31m"
+	GREEN="\033[1;32m"
+	YELLOW="\033[1;33m"
+	BLUE="\033[1;34m"
 }
 
 default_colors
 
 is_local() {
-        case "$1" in
-                http://*|ftp://*|https://*|saveas-*://*)
-                        return 1;;
-        esac
-        return 0
+	case "$1" in
+		http://*|ftp://*|https://*|saveas-*://*)
+			return 1;;
+	esac
+	return 0
 }
 
 msg() {
 	local prompt="$GREEN>>>${NORMAL}"
-        [ -z "$quiet" ] && printf "${prompt} $@\n" >&2
+	[ -z "$quiet" ] && printf "${prompt} $@\n" >&2
 }
 
 error() {
 	local prompt="$RED>>>${NORMAL}"
-        printf "${prompt} $@\n" >&2
+	printf "${prompt} $@\n" >&2
 }
 
 die() {
@@ -49,9 +49,9 @@ die() {
 }
 
 runpart() {
-        local part=$1
+	local part=$1
 	msg "Running part $part"
-        $part || die "$part failed"
+	$part || die "$part failed"
 }
 
 is_vserver() {
@@ -161,9 +161,9 @@ prepare_chroot() {
 
 	msg "Generating buildlab signing keys..."
 	do_chroot_action "$path" su abuild -c "'abuild-keygen -ai'"
-	
+
 	msg "Setting up repository symlink..."
-	mkdir -p "$path"/home/abuild/.cache/apks	
+	mkdir -p "$path"/home/abuild/.cache/apks
 	do_chroot_action "$path" chown abuild:abuild /home/abuild/${src}
 	do_chroot_action "$path" ln -sf .cache/apks /home/abuild/repo
 
@@ -256,8 +256,8 @@ while getopts "chqCkp:v:m:a:b:u" opt; do
 	case $opt in
 		'c') default_colors
 		     color_opt="-c";;
-                'h') usage;;
-                'q') quiet="-q";;
+		'h') usage;;
+		'q') quiet="-q";;
 		'C') create="-c";;
 		'p') buildpath="$OPTARG";;
 		'm') buildmirror="$OPTARG";;
@@ -266,7 +266,7 @@ while getopts "chqCkp:v:m:a:b:u" opt; do
 		'k') enablecache=1;;
 		'b') buildpkg="$OPTARG";;
 		'u') update="-u";;
-        esac
+	esac
 done
 shift $(( $OPTIND - 1 ))
 
