checkapk: sanity check that we have CARCH set

diff --git a/checkapk.in b/checkapk.in
--- a/checkapk.in
+++ b/checkapk.in
@@ -39,6 +39,10 @@ if ! [ -f APKBUILD ]; then
 	die 'must be run in the directory of a built package'
 fi
 
+if ! [ -n "$CARCH" ]; then
+	die "failed to detect CARCH"
+fi
+
 . ./APKBUILD
 
 startdir="$PWD"
