main/aports-build: bail out if $arch is empty
If '$arch' is empty, the `rsync` invocation to upload the packages for
the current repo targets the wrong directory, resulting in the
repositories for all other architectures to be removed.

Because it's not known yet what caused the `abuild -A` invocation to
fail, we detect and log it and then bail out before it can do any
damage.

See alpine/infra/infra#10831

diff --git a/main/aports-build/aports-build b/main/aports-build/aports-build
--- a/main/aports-build/aports-build
+++ b/main/aports-build/aports-build
@@ -30,6 +30,11 @@ if [ -z "$rel" ]; then
 fi
 
 arch=$(abuild -A)
+if [ -z "$arch" ]; then
+	log "failed to determine arch"
+	printf "%s: could not determine arch" "$(date -Iseconds)" >>/tmp/aports-build.log
+	exit 1
+fi
 
 aports=${APORTS:-$HOME/aports}
 packages=${REPOSDIR:-$HOME/packages}
