main/aports-build: upload each repo when built
we dont want prevent to upload a successful built main repo if testing
fails to build.

diff --git a/main/aports-build/aports-build b/main/aports-build/aports-build
--- a/main/aports-build/aports-build
+++ b/main/aports-build/aports-build
@@ -89,7 +89,7 @@ new_release() {
 }
 
 build() {
-	( $buildrepo $repos || echo "FAIL" ) | while read line; do
+	( $buildrepo "$@" || echo "FAIL" ) | while read line; do
 		case "$line" in
 		FAIL) return 1;;
 		[0-9]*/[0-9]*) $status_msg "$line";;
@@ -145,28 +145,28 @@ while true; do
 
 	# do the compile, send output to log
 	log "building $_current"
-	if ! build >"$logdir"/$hostname.log 2>&1 ; then
-		local errlog=$hostname.$_current.log
-		cp "$logdir"/$hostname.log "$logdir"/$errlog
-		# todo: revert last commit?
-		send_irc "failed to build $_current: $logurlprefix/$errlog"
-		exit 1
-	fi
-
-	# upgrade our running system
-	log "upgrading system"
-	sudo apk upgrade -U -a --quiet || log 'failed to apk upgrade'
-
-	# copy for distribution
-	cd "$packages" || return 1
-	if [ -z "$upload_pkg" ]; then
-		break
-	fi
-	log "uploading packages"
 	rc=0
-	for i in $upload_pkg; do
-		local repo
-		for repo in $repos; do
+	for repo in $repos; do
+		if ! build $repo >"$logdir"/$hostname.log 2>&1 ; then
+			local errlog=$hostname.$_current.log
+			cp "$logdir"/$hostname.log "$logdir"/$errlog
+			# todo: revert last commit?
+			send_irc "failed to build $_current: $logurlprefix/$errlog"
+			exit 1
+		fi
+
+		# upgrade our running system
+		log "upgrading system"
+		sudo apk upgrade -U -a --quiet || log 'failed to apk upgrade'
+
+		# copy for distribution
+		cd "$packages" || return 1
+		if [ -z "$upload_pkg" ]; then
+			continue
+		fi
+
+		log "uploading packages to $repo"
+		for i in $upload_pkg; do
 			if rsync -ruv --delete-delay --delay-updates \
 					$repo/$arch $i/$repo/; then
 				$upload_msg "$rel/$repo/$arch"
@@ -174,13 +174,12 @@ while true; do
 				rc=1
 			fi
 		done
+		# report to irc that we are done with repo
+		send_irc "files from $_current uploaded to $repo"
 	done
 	[ $rc -eq 0 ] && touch /tmp/uploaded && sudo apk update
 
-	# report to irc that we are done
-	send_irc "files from $_current uploaded"
-
-	if $do_release; then
+	if [ -n "$upload_pkg" ] && $do_release; then
 		if new_release ${_current_tag#v}; then
 			$upload_msg "$rel/releases/$arch"
 			send_irc "release $_current_tag uploaded"
