main/aports-build: send status messages only to mqtt

diff --git a/main/aports-build/aports-build b/main/aports-build/aports-build
--- a/main/aports-build/aports-build
+++ b/main/aports-build/aports-build
@@ -85,6 +85,16 @@ new_release() {
 	return 0
 }
 
+build() {
+	( $buildrepo $repos || echo "FAIL" ) | while read line; do
+		case "$line" in
+		FAIL) return 1;;
+		[0-9]*/[0-9]*) $status_msg "$line";;
+		*) echo "$line";;
+		esac
+	done
+}
+
 cd $aports || return 1
 [ -z "$repos" ] && return 1
 
@@ -128,16 +138,7 @@ while true; do
 
 	# do the compile, send output to log
 	log "building $_current"
-#	# temp workaround - abuild does not resolve the linux kernel dep
-#	(
-#		cd $HOME/aports/main
-#		for i in linux-*; do
-#			(
-#			export REPODEST=$HOME/packages
-#			cd $i && abuild -Rk )||break
-#		done
-#	)
-	if ! $buildrepo $repos >"$logdir"/$hostname.log 2>&1 ; then
+	if ! build >"$logdir"/$hostname.log 2>&1 ; then
 		local errlog=$hostname.$_current.log
 		cp "$logdir"/$hostname.log "$logdir"/$errlog
 		# todo: revert last commit?
