community/keycloak: upgrade to 23.0.1

diff --git a/community/keycloak/support-for-readonly-usr-share.patch b/community/keycloak/support-for-readonly-usr-share.patch
--- a/community/keycloak/support-for-readonly-usr-share.patch
+++ b/community/keycloak/support-for-readonly-usr-share.patch
@@ -31,7 +31,7 @@ installation, because `kc build` fails when the quarkus directory is empty.
 
 --- a/quarkus/dist/src/main/content/bin/kc.sh
 +++ b/quarkus/dist/src/main/content/bin/kc.sh
-@@ -30,8 +30,12 @@
+@@ -34,8 +34,12 @@
    fi
  }
  
@@ -45,25 +45,41 @@ installation, because `kc build` fails when the quarkus directory is empty.
  SERVER_OPTS="$SERVER_OPTS -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
  SERVER_OPTS="$SERVER_OPTS -Dquarkus-log-max-startup-records=10000"
  CLASSPATH_OPTS="'$(abs_path "../lib/quarkus-run.jar")'"
-@@ -115,7 +119,20 @@
+@@ -48,6 +52,7 @@
+     printf '%s\n' "$1" | sed "s/'/'\\\\''/g; 1 s/^/'/; $ s/$/'/"
+ }
+ 
++BUILD=false
+ PRE_BUILD=true
+ while [ "$#" -gt 0 ]
+ do
+@@ -70,7 +75,7 @@
+             -D*) SERVER_OPTS="$SERVER_OPTS ${OPT}";;
+             *) case "$1" in
+                  --optimized | --help | --help-all | -h) PRE_BUILD=false;;
+-                 build) if [ -z "$CONFIG_ARGS" ]; then PRE_BUILD=false; fi;;
++                 build) BUILD=true; if [ -z "$CONFIG_ARGS" ]; then PRE_BUILD=false; fi;;
+                esac 
+                CONFIG_ARGS="$CONFIG_ARGS ${OPT}"
+                ;;
+@@ -138,6 +143,20 @@
+ if [ "$PRINT_ENV" = "true" ]; then
+   echo "Using JAVA_OPTS: $JAVA_OPTS"
+   echo "Using JAVA_RUN_OPTS: $JAVA_RUN_OPTS"
++fi
++
++if [ "$BUILD" = "true" ]; then
++  # XXX-Patched: Added by Alpine Linux aport to allow running Keycloak
++  # from read-only /usr/share.
++  if ! [ -e "$BUILD_DIR"/quarkus/build-system.properties ]; then
++    # Copy the distribution quarkus files. They will be overwritten by
++    # `kc build`, but this command fails when the directory is empty.
++    mkdir -p "$BUILD_DIR"/quarkus
++    cp "$(abs_path '../lib/quarkus.dist')"/* "$BUILD_DIR"/quarkus/
++    ln -s "$(abs_path '../lib/app')" "$BUILD_DIR"/app
++  fi
++  # Workaround to avoid errors related to symlinks.
++  export QUARKUS_PACKAGE_OUTPUT_DIRECTORY="$BUILD_DIR"
  fi
  
- case "$CONFIG_ARGS" in
--  " build"* | *--optimized* | *-h | *--help*) ;;
-+  " build"*)
-+    # XXX-Patched: Added by Alpine Linux aport to allow running Keycloak
-+    # from read-only /usr/share.
-+    if ! [ -e "$BUILD_DIR"/quarkus/build-system.properties ]; then
-+      # Copy the distribution quarkus files. They will be overwritten by
-+      # `kc build`, but this command fails when the directory is empty.
-+      mkdir -p "$BUILD_DIR"/quarkus
-+      cp "$(abs_path '../lib/quarkus.dist')"/* "$BUILD_DIR"/quarkus/
-+      ln -s "$(abs_path '../lib/app')" "$BUILD_DIR"/app
-+    fi
-+    # Workaround to avoid errors related to symlinks.
-+    export QUARKUS_PACKAGE_OUTPUT_DIRECTORY="$BUILD_DIR"
-+    ;;
-+  *--optimized* | *-h | *--help*) ;;
-   *)
-     eval "'$JAVA'" -Dkc.config.build-and-exit=true $JAVA_RUN_OPTS || exit $?
-     JAVA_RUN_OPTS="-Dkc.config.built=true $JAVA_RUN_OPTS"
+ if [ "$PRE_BUILD" = "true" ]; then
