main/postgresql: check config errors on reload

diff --git a/main/postgresql/postgresql.initd b/main/postgresql/postgresql.initd
--- a/main/postgresql/postgresql.initd
+++ b/main/postgresql/postgresql.initd
@@ -139,8 +139,12 @@ stop() {
 reload() {
 	ebegin "Reloading PostgreSQL configuration"
 
-	start-stop-daemon --signal HUP --pidfile "$pidfile"
-	eend $?
+	start-stop-daemon --signal HUP --pidfile "$pidfile" && check_config_errors
+	local retval=$?
+
+	check_pending_restart
+
+	eend $retval
 }
 
 setup() {
@@ -206,6 +210,41 @@ get_config() {
 		| grep . || printf '%s\n' "$default"
 }
 
+check_config_errors() {
+	local out=$(psql_command "
+		select
+		  sourcefile || ': line ' || sourceline || ': ' || error ||
+		    case when name is not null
+		    then ': ' || name || ' = ''' || setting || ''''
+		    else ''
+		    end
+		from pg_file_settings
+		where error is not null
+		  and name not in (select name from pg_settings where pending_restart = true);
+		")
+	local retval=$?
+
+	if [ "$retval" -eq 0 ] && [ "$out" ]; then
+		eerror 'Configuration file contains errors:'
+		printf '%s\n' "$out" | while read line; do
+			eerror "  $line"
+		done
+		return 1
+	fi
+}
+
+check_pending_restart() {
+	local out=$(psql_command "select name from pg_settings where pending_restart = true;")
+	local retval=$?
+
+	if [ "$retval" -eq 0 ] && [ "$out" ]; then
+		ewarn 'PostgreSQL must be restarted to apply changes in the following parameters:'
+		local line; for line in $out; do
+			ewarn "  $line"
+		done
+	fi
+}
+
 check_deprecated_var() {
 	local old_name="$1"
 	local new_name="$2"
@@ -217,4 +256,8 @@ check_deprecated_var() {
 
 getval() {
 	eval "printf '%s\n' \"\$$1\""
+}
+
+psql_command() {
+	su $user -c "psql --no-psqlrc --no-align --tuples-only -q -c \"$1\""
 }
