main/postgresql: fix init scripts for 9.2
- change some variables, {NICE,RUDE,FORCE}_TIMEOUT to correspond with
  gentoo variables, while still beeing backawards compatible
- change data dir to 9.2
- patch initdb to not suggest how to start postgresql

diff --git a/main/postgresql/postgresql.initd b/main/postgresql/postgresql.initd
--- a/main/postgresql/postgresql.initd
+++ b/main/postgresql/postgresql.initd
@@ -12,10 +12,25 @@ depend() {
 	after firewall
 }
 
-checkconfig() {
-	[ -d "$PGDATA/base" ] && return 0
-	echo "checking config"
+get_config() {
+	[ -f ${PGDATA%/}/postgresql.conf ] || return 1
+	eval echo $(sed -e 's:#.*::' ${PGDATA%/}/postgresql.conf | awk '$1 == "'$1'" { print ($2 == "=" ? $3 : $2) }')
+}
 
+
+checkconfig() {
+	configured_port=$(get_config port)
+	: ${configured_port:=${PGPORT:-5432}}
+	socket_path=$(get_config unix_socket_directory)
+	: ${socket_path:=/var/run/postgresql}
+
+	checkpath -d -m 0770 -o postgres:postgres ${socket_path}
+
+	if [ -n "$WAIT_FOR_START" ]; then
+		START_TIMEOUT=$WAIT_FOR_START
+	fi
+
+	[ -d "$PGDATA/base" ] && return 0
 	if [ -z "$AUTO_SETUP" ] ; then
 		eerror "Database not found at: $PGDATA"
 		eerror "Please make sure that PGDATA points to the right path."
@@ -34,72 +49,71 @@ start() {
 		rm -f "$PGDATA/postmaster.pid"
 	fi
 
-	local retval
+	local retval= x= extraenv=
+	for x in ${PG_EXTRA_ENV} ; do
+		extraenv="${extraenv} --env ${x}"
+	done
 
-	su -l ${PGUSER} \
-		-c "env PGDATA=\"${PGDATA}\" /usr/bin/pg_ctl start ${WAIT_FOR_START} -o '--silent-mode=true ${PGOPTS}'" >/dev/null
+	start-stop-daemon --start \
+		--user ${PGUSER:-postgres} \
+		--group ${PGGROUP:-postgres} \
+		--env "PGPORT=${configured_port}" \
+		${extraenv} \
+		--pidfile ${PGDATA}/postmaster.pid \
+		--wait 100 \
+		--exec /usr/bin/pg_ctl \
+		-- \
+		start -s -w -t ${START_TIMEOUT:-10} \
+		-l ${PGDATA}/postmaster.log \
+		-D ${PGDATA} -o "--data-directory=${PGDATA} $PGOPTS"
 	retval=$?
-	[ $retval -ne 0 ] && eend $retval && return $retval
 
-	# The following is to catch the case of an already running server
-	# in which pg_ctl doesn't know to which server it connected to and false reports the server as 'up'
-	sleep 2
-	if [ ! -f "$PGDATA/postmaster.pid" ] ; then
-		eerror "The pid-file doesn't exist but pg_ctl reported a running server."
-		eerror "Please check whether there is another server running on the same port or read the log-file."
-		eend 1
-		return 1
+	if [ $retval -ne 0 ] ; then
+		eerror "Check the log for a possible explanation of the above error."
+		eerror "    ${PGDATA}/postmaster.log"
 	fi
-
-	local pid
-	read pid < "$PGDATA/postmaster.pid"
-	test -d /proc/"${pid}" 
-	eend $?
+	eend $retval
 }
 
 stop() {
-	ebegin "Stopping PostgreSQL (this can take up to $(( ${WAIT_FOR_DISCONNECT} + ${WAIT_FOR_CLEANUP} )) seconds)"
-
-	local retval
-
-	su -l ${PGUSER} \
-		-c "env PGDATA=\"${PGDATA}\" /usr/bin/pg_ctl stop -t ${WAIT_FOR_DISCONNECT} -m smart" >/dev/null
-
-	retval=$?
-	[ $retval -eq 0 ] && eend $retval && return $retval
-
-	ewarn "Some clients did not disconnect within ${WAIT_FOR_DISCONNECT} seconds."
-	ewarn "Going to shutdown the server anyway."
-
-	su -l ${PGUSER} \
-		-c "env PGDATA=\"${PGDATA}\" /usr/bin/pg_ctl stop -m fast" >/dev/null
-
-	retval=$?
-	[ $retval -eq 0 ] && eend $retval && return $retval
-
-	if [ ${WAIT_FOR_QUIT} -eq 0 ] ; then
-		eerror "Server did not shut down and sending the SIGQUIT has been disabled."
-		eend $retval
-		return $retval
+	if [ -n "$WAIT_FOR_DISCONNECT" ]; then
+		NICE_TIMEOUT=$WAIT_FOR_DISCONNECT
+	fi
+	if [ -n "$WAIT_FOR_CLEANUP" ]; then
+		RUDE_QUIT=YES
+		RUDE_TIMEOUT=$WAIT_FOR_CLEANUP
+	fi
+	if [ -n "$WAIT_FOR_QUIT" ] && [ $WAIT_FOR_QUIT -ne 0 ]; then
+		FORCE_QUIT=YES
+		FORCE_TIMEOUT=$WAIT_FOR_QUIT
 	fi
 
-	ewarn "Shutting down the server gracefully failed."
-	ewarn "Forcing it to shutdown which leads to a recover-run on next startup."
+	local seconds=${NICE_TIMEOUT}
+	local retval
+	local retries=SIGTERM/${NICE_TIMEOUT}
+	if [ "${RUDE_QUIT}" != "NO" ] ; then
+		retries="${retries}/SIGINT/${RUDE_TIMEOUT}"
+		seconds=$(( $seconds + ${NICE_TIMEOUT} ))
+	fi
+	if [ "${FORCE_QUIT}" = "YES" ] ; then
+		retries="${retries}/SIGQUIT/${FORCE_TIMEOUT}"
+		seconds=$(( $seconds + ${FORCE_TIMEOUT} ))
+	fi
 
-	su -l ${PGUSER} \
-		-c "env PGDATA=\"${PGDATA}\" /usr/bin/pg_ctl stop -m immediate" >/dev/null
+	ebegin "Stopping PostgreSQL (this can take up to ${seconds} seconds)"
 
-	retval=$?
-	[ $retval -eq 0 ] && eend $retval && return $retval
-
-	eerror "Forced shutdown failed!!! Something is wrong with your system, please take care of it manually."
-	eend $?
+	# Loops through nice, rude, and force quit in one go.
+	start-stop-daemon --stop \
+		--exec /usr/bin/postgres \
+		--retry ${retries} \
+		--progress \
+		--pidfile ${PGDATA}/postmaster.pid
+	eend
 }
 
 reload() {
 	ebegin "Reloading PostgreSQL configuration"
-	su -l ${PGUSER} \
-		-c "env PGDATA=\"${PGDATA}\" /usr/bin/pg_ctl reload" >/dev/null
+	kill -HUP $(head -n1 ${PGDATA}/postmaster.pid)
 	eend $?
 }
 
@@ -124,8 +138,6 @@ setup() {
 	chmod 0700 "${PGDATA}" 
 	cd "${PGDATA}" # to avoid the: could not change directory to "/root" 
 	su -c "/usr/bin/initdb --pgdata ${PGDATA}" postgres
-	einfo "You can use the '/etc/init.d/postgresql' script to run PostgreSQL instead"
-	einfo "of 'pg_ctl'."
 	local res=$?
 
 	# move the pg_hba.conf and friends
