community/pandoc-cli: take over maintainership
emailed the previous maintainer and received permission to take over this aport

diff --git a/community/pandoc-cli/APKBUILD b/community/pandoc-cli/APKBUILD
--- a/community/pandoc-cli/APKBUILD
+++ b/community/pandoc-cli/APKBUILD
@@ -1,9 +1,10 @@
 # Contributor: Jean-Louis Fuchs <jean-louis.fuchs@adfinis-sygroup.ch>
-# Maintainer: Jean-Louis Fuchs <jean-louis.fuchs@adfinis-sygroup.ch>
+# Maintainer: Celeste <cielesti@protonmail.com>
+maintainer="Celeste <cielesti@protonmail.com>"
 pkgname=pandoc-cli
 pkgver=3.6.2
-pkgrel=0
-pkgdesc="universal markup converter"
+pkgrel=1
+pkgdesc="Universal markup converter"
 url="https://pandoc.org/"
 # limited by ghc
 arch="aarch64 x86_64"
@@ -21,31 +22,50 @@ provides="pandoc=$pkgver-r$pkgrel"
 replaces="pandoc"
 
 # Cabal seems to be built without sandbox, moving the cabal-dir into src
-export CABAL_DIR="$srcdir/.cabal"
+export CABAL_DIR="${CABAL_DIR:-"$srcdir/.cabal"}"
 
 cabal_update() {
-	cd $builddir
-	cabal update
+	local repo="hackage.haskell.org"
+
+	# Default config uses HTTP, change it to HTTPS.
+	[ -f "$CABAL_DIR"/config ] || {
+		cabal user-config init
+		cabal user-config update -a \
+			"repository $repo {url: https://$repo/}"
+	}
+
+	cd "$startdir"
+	[ -d "$builddir" ] || abuild unpack
+	msg "Freezing $pkgname dependencies"
+
+	# Resolve deps and generate fresh cabal.project.freeze with version constraints.
 	(
-		cd "$builddir"
+		cd "$builddir" || {
+			error 'Is $builddir set correctly?'
+			return 1
+		}
+		cabal v2-update
 		cabal v2-freeze \
 			--strong-flags \
 			--shadow-installed-packages \
 			--constraint "pandoc +embed_data_files" \
 			--flags "+server +lua"
 
-		mv cabal.project.freeze "$startdir/"
+		mv -v cabal.project.freeze "$startdir"/
 	)
+
+	if ! abuild checksum; then
+		die "Failed to update checksum, run 'abuild checksum' manually"
+	fi
 }
 
 prepare() {
 	default_prepare
-	ln -sf "$srcdir/cabal.project.freeze" \
-		"$builddir/cabal.project.freeze"
+
+	ln -svf "$srcdir"/cabal.project.freeze "$builddir"/
 }
 
 build() {
-	export PATH="$PATH:/usr/lib/llvm15/bin"
 	cabal v2-update
 	cabal v2-build pandoc-cli:exes \
 		--jobs=${JOBS:-1} \
@@ -57,11 +77,12 @@ build() {
 
 package() {
 	# See https://github.com/haskell/cabal/issues/6919#issuecomment-761563498
-	cabal list-bin pandoc-cli:exes | xargs install -Dm755 -t "$pkgdir"/usr/bin
+	cabal list-bin pandoc-cli:exes |
+		xargs install -Dvm755 -t "$pkgdir"/usr/bin/
 
 	ln -sfv pandoc "$pkgdir"/usr/bin/pandoc-server
 
-	install -Dm644 -t "$pkgdir"/usr/share/man/man1 man/*.1
+	install -Dvm644 man/*.1 -t "$pkgdir"/usr/share/man/man1/
 }
 
 sha512sums="
