community/lua-dromozoa-utf8: downgrade to 1.11
Upstream removed release 2.0 and continue with 1.x... >_<

diff --git a/community/lua-dromozoa-utf8/test.sh.patch b/community/lua-dromozoa-utf8/test.sh.patch
--- a/community/lua-dromozoa-utf8/test.sh.patch
+++ b/community/lua-dromozoa-utf8/test.sh.patch
@@ -3,15 +3,15 @@ Don't overwhelm console with test output...
 --- a/test.sh
 +++ b/test.sh
 @@ -24,7 +24,11 @@
- 
- for i in test/test*.lua
  do
--  "$lua" "$i"
-+  "$lua" "$i" > "${i%.lua}.out" 2>&1 || {
-+    echo "Tests failed, printing last 30 lines of the output..."
-+    tail -n 30 "${i%.lua}.out"
-+    exit 1
-+  }
+   case X$# in
+     X0) lua "$i";;
+-    *) "$@" "$i";;
++    *) "$@" "$i" > "${i%.lua}.out" 2>&1 || {
++         echo "Tests failed, printing last 30 lines of the output..."
++         tail -n 30 "${i%.lua}.out"
++         exit 1
++       };;
+   esac
  done
  
- mkdir -p out
