testing/scsi-tgt: Rework init scripts for better error handling

diff --git a/testing/scsi-tgt/tgtd.initd b/testing/scsi-tgt/tgtd.initd
--- a/testing/scsi-tgt/tgtd.initd
+++ b/testing/scsi-tgt/tgtd.initd
@@ -1,17 +1,28 @@
 #!/sbin/openrc-run
 
 name="tgtd"
-command="/usr/sbin/tgtd"
-command_args_foreground="--foreground"
-command_background=true
 pidfile="/run/$RC_SVCNAME.pid"
-
-# sigterm doesn't stop it
-retry="SIGINT/5"
-
-output_log="/var/log/$RC_SVCNAME.log"
-error_log="/var/log/$RC_SVCNAME.log"
+command="/usr/sbin/tgtd"
+command_args_background="--pid-file ${pidfile}"
 
 depend() {
 	need dev localmount
+}
+
+start_post() {
+	# We start tgtd, but leave in "offline" mode until
+	# targets are configured.
+	tgtadm --op update --mode sys --name State -v offline
+}
+
+stop() {
+	# Remove system node. This will fail if
+	# not all targets have been removed first.
+	tgtadm --op delete --mode system
+	retval=$?
+	if [ $retval -ne 0 ]; then
+		eerror "Failed to shutdown tgtd"
+		eend $retval
+		exit $retval
+	fi
 }
