main/gstreamer, main/gst-plugins-[base,good,bad,ugly]
main/gstreamer: Clarify license
main/gst-plugins-base: Clarify license, update configure options
main/gst-plugins-good: Clarify license, update configure options, add Qt and Gtk-3 plugins as separate packages
main/gst-plugins-bad: Clarify license, updte configure options, fix compile against libressl
main/gst-plugins-ugly: Clarify license, updte configure options

diff --git a/main/gst-plugins-good/APKBUILD b/main/gst-plugins-good/APKBUILD
--- a/main/gst-plugins-good/APKBUILD
+++ b/main/gst-plugins-good/APKBUILD
@@ -5,12 +5,12 @@ pkgrel=0
 pkgdesc="GStreamer Multimedia Framework Good Plugins"
 url="https://gstreamer.freedesktop.org/"
 arch="all"
-license="LGPL"
-subpackages="$pkgname-lang $pkgname-doc"
-depends=
+license="GPL-2.0-or-later LGPL-2.0-or-later"
+subpackages="$pkgname-lang $pkgname-doc $pkgname-qt $pkgname-gtk"
 replaces="gst-plugins-good1"
-depends_dev="gstreamer-dev gst-plugins-base-dev"
-makedepends="$depends_dev
+makedepends="
+	gstreamer-dev
+	gst-plugins-base-dev
 	flac-dev
 	gdk-pixbuf-dev
 	glib-dev
@@ -37,12 +37,18 @@ makedepends="$depends_dev
 	v4l-utils-dev
 	wavpack-dev
 	zlib-dev
+	mpg123-dev
+	lame-dev
+	gtk+3.0-dev
+	qt5-qtdeclarative-dev
+	qt5-x11extras-dev
+	libcaca-dev
+	cairo-dev
+	orc-compiler
 	"
-replaces=
-ldpath="/usr/lib/gstreamer-.0"
-source="https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-$pkgver.tar.xz
-	"
-builddir="$srcdir"/gst-plugins-good-$pkgver
+ldpath="/usr/lib/gstreamer-1.0"
+source="https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-$pkgver.tar.xz"
+options="!check" # elements/souphttpsrc fails
 
 # secfixes:
 #   1.10.4-r0:
@@ -57,7 +63,7 @@ builddir="$srcdir"/gst-plugins-good-$pkgver
 #   - CVE-2016-10199
 
 build() {
-	cd "$_builddir"
+	cd "$builddir"
 	./configure \
 		--build=$CBUILD \
 		--host=$CHOST \
@@ -68,15 +74,42 @@ build() {
 		--enable-experimental \
 		--disable-fatal-warnings \
 		--with-package-name="GStreamer Good Plugins (Alpine Linux)" \
-		--with-package-origin="http://alpinelinux.org/" \
-		|| return 1
+		--with-package-origin="http://alpinelinux.org/"
 	make
+}
+
+check() {
+	cd "$builddir"
+	make check
 }
 
 package() {
 	cd "$builddir"
 	export GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1
-	make DESTDIR="$pkgdir" install || return 1
+	make DESTDIR="$pkgdir" install
+}
+
+_mv() {
+	mkdir -p "$subpkgdir"/"$ldpath"
+        mv "$1" "$subpkgdir"/"$ldpath"
+}
+
+qt() {
+	pkgdesc="Gstreamer Qt plugin."
+        for i in $(find "$pkgdir" -type f ); do
+                if ldd $i 2>/dev/null | grep -q "libQt"; then
+                        _mv "$i" || return 1
+                fi
+        done
+}
+
+gtk() {
+	pkgdesc="Gstreamer gtk-3 plugin."
+        for i in $(find "$pkgdir" -type f ); do
+                if ldd $i 2>/dev/null | grep -q "libgtk-3"; then
+                        _mv "$i" || return 1
+                fi
+        done
 }
 
 doc() {
