main/libyuv: upgrade to 0.0.1928
I know this is madness, an alternative would be to do something to
abuild to handle googlesource.com tarballs like this

diff --git a/main/libyuv/APKBUILD b/main/libyuv/APKBUILD
--- a/main/libyuv/APKBUILD
+++ b/main/libyuv/APKBUILD
@@ -1,9 +1,13 @@
 # Maintainer: Andy Postnikov <apostnikov@gmail.com>
 pkgname=libyuv
-pkgver=0.0.1887.20251502
-pkgrel=1
-# using commit from libavif
-_commit=a6a2ec654b1be1166b376476a7555c89eca0c275
+pkgver=0.0.1928
+pkgrel=0
+# use commit that bumped version in include/libyuv/version.h
+_commit=94644361b4fc21befdadbf425a5d256b17f20565
+# from within the source directory, before applying patches:
+# find . -type f | sort | xargs cat | sha512sum
+_libyuvchecksum=b92d034854b4b1f5b67ec10aec9ff242c5a46597fc1f02e92feb9defa73fe863abd6c45140e54cb4b76a5831830bcaf695eff44c6362faedd47817051683f80d
+# used instead of $pkgname-$pkgver.tar.gz, stupid googlesource.com
 pkgdesc="Library for YUV scaling"
 url="https://chromium.googlesource.com/libyuv/libyuv/"
 arch="all"
@@ -13,11 +17,57 @@ checkdepends="gtest-dev"
 subpackages="$pkgname-dbg $pkgname-static $pkgname-dev"
 source="$pkgname-$pkgver.tar.gz::https://chromium.googlesource.com/libyuv/libyuv/+archive/$_commit.tar.gz
 	skip-s390x.patch
-	fix-loongarch64-build.patch"
+	"
+
+fetch() {
+	local s
+	mkdir -p "$srcdir"
+	set -- ${sha512sums:-$sha256sums}
+
+	for s in $source; do
+		local file="$startdir/$s"
+		if is_remote "$s"; then
+			uri_fetch_mirror "$s" || return 1
+			file="$SRCDEST/$(filename_from_uri $s)"
+		fi
+
+		sumalgo=sha512 # this has to be set?
+		# this is the only part that differ from default_fetch()
+		case "$s" in
+		"$pkgname-$pkgver.tar.gz"*)
+			# do nothing here, googlesource.com will create tarballs with
+			# different timestamps, thus different checksums, every fetch
+			shift 2
+			;;
+		*)
+			if [ "$sumalgo" != none ]; then
+				if ! echo "$1 $file" | ${sumalgo}sum -c; then
+					if is_remote $s; then
+						csum="${1:0:8}"
+
+						echo "Because the remote file above failed the ${sumalgo}sum check it will be renamed."
+						echo "Rebuilding will cause it to re-download which in some cases may fix the problem."
+						echo "Renaming: ${file##*/} to ${file##*/}.$csum"
+						mv "$file" "$file.$csum"
+					fi
+					die "Use 'abuild checksum' to generate/update the checksum(s)"
+				fi
+				shift 2
+			fi
+			;;
+		esac
+
+		ln -sf "$file" "$srcdir/"
+	done
+}
 
 unpack() {
-	mkdir -p $srcdir/$pkgname-$pkgver
-	tar xzf $srcdir/$pkgname-$pkgver.tar.gz -C $srcdir/$pkgname-$pkgver
+	mkdir -p "$builddir"
+	tar xzf "$srcdir"/"$pkgname"-"$pkgver".tar.gz -C "$builddir"
+
+	cd "$builddir"
+	find . -type f | sort | xargs cat | sha512sum | grep -q "$_libyuvchecksum" \
+		&& msg2 "$builddir: OK"
 }
 
 build() {
@@ -39,7 +89,6 @@ package() {
 }
 
 sha512sums="
-7b93c41082588208f556dda6c0b01d6609dfe1ce4a90137de2d4be73afb6655aed09b1f9d2ff4c6eb845a2142be636ae8e4b2e98a53aa4002467efb27a5e1f0a  libyuv-0.0.1887.20251502.tar.gz
-bb46d560cc4cf31c2380addc1906d5a0f251902bf097d654e1e043022fe94f4db55efa446a9ef8e6b97f5582fc0445b7e25d93747fe9c6ca4f88246362f5a96c  skip-s390x.patch
-b505f6b8f6b191565f61c8d5b41a8f9c6653e0863c33f27628d08211d9a528f6a2f62dab951b707a12f6740a59931eda6f39a0ab4d2c1f1c06b369be22a10a14  fix-loongarch64-build.patch
+86c66efa2e167a3291c809dbe5b17175674899e5e3010c6845fead6f82f0917e0dfea1e2c0f4523536db66a737efda56d3f458186011f1a2fcbdcda2614413e7  libyuv-0.0.1928.tar.gz
+29a84c25329c671e1a96dde0df02701f9c175ca3e137676803514abda523e59328ef727059f5e83b6f3756cbbb6281ef5a547b2c41525c9df78fc88a1ed90b0f  skip-s390x.patch
 "
