main/varnish: upgrade to 6.0.0

diff --git a/main/varnish/APKBUILD b/main/varnish/APKBUILD
--- a/main/varnish/APKBUILD
+++ b/main/varnish/APKBUILD
@@ -2,25 +2,25 @@
 # Contributor: V.Krishn <vkrishn4@gmail.com>
 # Maintainer: Natanael Copa <ncopa@alpinelinux.org>
 pkgname=varnish
-pkgver=5.2.1
+pkgver=6.0.0
 pkgrel=0
 pkgdesc="High-performance HTTP accelerator"
 url="http://www.varnish-cache.org/"
 arch="all"
 license="BSD"
+options="!check" # tests fail
 depends="gcc libc-dev libgcc"
 depends_dev=
 makedepends="$depends_dev pcre-dev ncurses-dev libedit-dev py-docutils
 	linux-headers libexecinfo-dev"
-install="varnish.pre-install"
+install="$pkgname.pre-install"
 subpackages="$pkgname-dbg $pkgname-dev $pkgname-doc $pkgname-libs $pkgname-geoip::noarch"
 pkgusers="varnish"
 pkggroups="varnish"
-source="http://varnish-cache.org/_downloads/varnish-$pkgver.tgz
+source="http://varnish-cache.org/_downloads/$pkgname-$pkgver.tgz
 	fix-stack-overflow.patch
-	musl-mode_t.patch
-	musl-includes.patch
-	python-version-fix.patch
+	musl-include-vpf.patch
+	musl-include-vsb.patch
 
 	varnishd.initd
 	varnishd.confd
@@ -31,7 +31,7 @@ source="http://varnish-cache.org/_downloads/varnish-$pkgver.tgz
 	varnishd.logrotate
 	maxminddb.vcl"
 
-builddir="$srcdir"/varnish-$pkgver
+builddir="$srcdir/$pkgname-$pkgver"
 
 # secfixes:
 #   5.2.1-r0:
@@ -43,8 +43,8 @@ builddir="$srcdir"/varnish-$pkgver
 build() {
 	cd "$builddir"
 	./configure \
-		--build=$CBUILD \
-		--host=$CHOST \
+		--build="$CBUILD" \
+		--host="$CHOST" \
 		--prefix=/usr \
 		--sysconfdir=/etc \
 		--mandir=/usr/share/man \
@@ -54,15 +54,20 @@ build() {
 	make
 }
 
+check() {
+	cd "$builddir"
+	make -j1 check || { find . -name 'test-suite.log' -print -exec cat '{}' ';'; return 1; }
+}
+
 package() {
 	cd "$builddir"
 	make DESTDIR="$pkgdir" install
 	for i in $source; do
 		case $i in
-		*.initd) install -Dm755 "$srcdir"/$i \
-				"$pkgdir"/etc/init.d/${i%.*} ;;
-		*.confd) install -Dm644 "$srcdir"/$i \
-				"$pkgdir"/etc/conf.d/${i%.*} ;;
+		*.initd) install -Dm755 "$srcdir/$i" \
+				"$pkgdir/etc/init.d/${i%.*}" ;;
+		*.confd) install -Dm644 "$srcdir/$i" \
+				"$pkgdir/etc/conf.d/${i%.*}" ;;
 		esac
 	done
 	install -Dm644 "$srcdir"/varnishd.logrotate \
@@ -88,11 +93,10 @@ geoip() {
 		"$subpkgdir"/usr/lib/varnish/plugins/maxminddb.vcl
 }
 
-sha512sums="2e979983c7f2325e289768752cc474dc3032c3420de65ccfd5871098c076aecf18e962b04308ecb1860f542fd6f6418dc79220fdd6cf4a75f7476a733faa589c  varnish-5.2.1.tgz
+sha512sums="39bae462fe40bda9b7c93114ab8256c838a7d67f1a9f7397c37ad090163a33232676120eb7609d0512684a563d8e02c1c2ff5e1b9da0ddedef2250db51c3cc79  varnish-6.0.0.tgz
 19d2ef52aaecadec42505b52a7bb683f52c9de1186180c0b02afc6a1044127a39c0468470563e7f248ed93b0e45d279adfebf35e78c49f4b79e1dfb5a15b0f46  fix-stack-overflow.patch
-8758bef9039a2cca23b7302668bd49f1ea07f54835512a8a9558bb9ed5de1c0fca53f2085ccd298fe0c6579fc81c3b583a85f4f6b25b6ad85f89bf3be04afb70  musl-mode_t.patch
-ccd5b1ebb1e98e4d6003de5c4713bed36f1af3f8ae0eb4b63d7da50831a320e4eb9a9e589b300db8b9177ce131c5d00964bb24bbe829ade6727e5d8965fe0757  musl-includes.patch
-bb64ddd0c15279b448a091b20aff4b36270b42b4d3e7389f98d0c9e54303d47d676eb90e1735e614bcede788466c291a8f809bdea733ddef8ad4f24bd645daf0  python-version-fix.patch
+2123668169b055f2d88f9b5b8e0877ca8b3cbfcd61e03d91fd7d0513b3267e4ef01a4d858cc6a3298cca0a49aaea2f92ff4fd9c0baf52a6c67b452a53f7e54d0  musl-include-vpf.patch
+c51c8964880990c2b01807b2a38d886b146736a918bda9ea2e032c50085bf6745cab3cccb4ee4c561ab936a8b7cfb278cfcb758543ea6c605c15b8973c9f10ce  musl-include-vsb.patch
 5ac7867e85cbd721f903c524ed4b524423d9dada4acfeefb0e543214a208828df5cc4efe2f012991bea6b38c2b223c24b17d3890ec4ed2c57d2b441b8e5a6900  varnishd.initd
 98c8901e53f3c6adb908b9eb01fd441ea53f3c54d4a79aecb1fb1eddfa2fc93de3d0de403a4464a9baff15873b3a20623837e3a37cb225e924a329e32b9e37d6  varnishd.confd
 c67a7898f40849989edcbe74e1a418e196f48e178ca30126bc13db226e4f4c2c2ba74d9d0650ef68ed88732917fc06b80ef1f62c2d9d2c14a89f26fd25aed0f7  varnishlog.initd
