main/monit: improve init script, don't force supervise-daemon
Allow users to disable supervise-daemon or use another supervisor
via conf.d file.

diff --git a/main/monit/monit.initd b/main/monit/monit.initd
--- a/main/monit/monit.initd
+++ b/main/monit/monit.initd
@@ -1,39 +1,47 @@
 #!/sbin/openrc-run
-# Copyright 1999-2011 Gentoo Foundation
-# Distributed under the terms of the GNU General Public License, v2 or later
-# $Header: /var/cvsroot/gentoo-x86/app-admin/monit/files/monit.initd-5.0-r1,v 1.2 2011/12/31 16:28:50 idl0r Exp $
-
-supervisor=supervise-daemon
 
 name="monit"
 description="Monit service supervisor"
 
-: ${monit_config:=${CONF:-/etc/monitrc}}
-
-command=/usr/bin/monit
-command_args="-c ${monit_config}"
-command_args_foreground="-I"
-
-extra_commands="configtest"
+extra_commands="checkconfig configtest"
 extra_started_commands="reload"
+
+# $monit_config is for backward compatibility (Alpine <3.19)
+: ${cfgfile:="${monit_config:-/etc/monitrc}"}
+
+command="/usr/bin/monit"
+command_args="-c $cfgfile"
+command_args_foreground="-I"
+pidfile="/run/$RC_SVCNAME.pid"
+
+required_files="$cfgfile"
 
 depend() {
 	use net
 }
 
+start_pre() {
+	checkconfig
+}
+
+checkconfig() {
+	ebegin "Checking $name configuration"
+
+	if ! /usr/bin/monit -t -c "$cfgfile" >/dev/null 2>&1; then
+		eerror "$RC_SVCNAME has detected an error in your setup:"
+		/usr/bin/monit -t "$cfgfile"
+		return 1
+	fi
+	eend 0
+}
+
+# Deprecated, only for backward compatibility (Alpine <3.19)
 configtest() {
-        /usr/bin/monit -t -c "${monit_config}" 1>/dev/null 2>&1
-        ret=$?
-        if [ $ret -ne 0 ]; then
-                eerror "${RC_SVCNAME} has detected an error in your setup:"
-                /usr/bin/monit -t "${monit_config}"
-        fi
-        return $ret
+	checkconfig "$@"
 }
 
 reload() {
-	ebegin "Reloading monit"
-	$command -c "${monit_config}" reload >/dev/null 2>&1
+	ebegin "Reloading $name"
+	$command -c "$cfgfile" reload >/dev/null 2>&1
 	eend $?
 }
-
