main/chrony: upgrade to 1.28

diff --git a/main/chrony/APKBUILD b/main/chrony/APKBUILD
--- a/main/chrony/APKBUILD
+++ b/main/chrony/APKBUILD
@@ -1,6 +1,6 @@
 # Maintainer: Natanael Copa <ncopa@alpinelinux.org>
 pkgname=chrony
-pkgver=1.27
+pkgver=1.28
 pkgrel=0
 _ver=${pkgver/_/-}
 pkgdesc="NTP client and server programs"
@@ -30,7 +30,7 @@ prepare() {
 		esac
 	done
 	sed -i "s:/etc/chrony:/etc/chrony/chrony:g" \
-		chrony*.[158] faq.txt chrony.texi || die "sed failed"
+		chrony*.[158] faq.txt || die "sed failed"
 }
 
 build() {
@@ -57,10 +57,24 @@ package() {
 	touch "$pkgdir"/etc/chrony/chrony.drift
 	install -m644 "$srcdir"/chrony.conf "$pkgdir"/etc/chrony/chrony.conf
 }
-md5sums="0c2ae73f7e8ddfe31eeafc803818b9e4  chrony-1.27.tar.gz
+md5sums="d11dd205cd8837ae49f065e42a84f363  chrony-1.28.tar.gz
 c479553205e2dfe1409c7924b0d0f81b  0001-uclibc-res-do-not-call-res_init.patch
 1f72a2805160dfa653866e0963256f7f  0002-ntp_sources-decrease-maximum-re-resolving-delay.patch
 d62521b4c8837e15262c47ac88359307  chronyd.confd
 f0c73948224cc1706cf9c94e4d2d7b69  chronyd.initd
 468eaf2b5465d60b3ee021ce3f948ab1  chrony.logrotate
 46f42c52953d398ca44d6baa449618d7  chrony.conf"
+sha256sums="7adc34e77c5b5ffdf274adad54de503a34386f6b483c45e1a723751763c04364  chrony-1.28.tar.gz
+4aec957ff59adbba1058e5376c73fe74e1e6fb511d9ca6cb5b6e74fca8c75a9f  0001-uclibc-res-do-not-call-res_init.patch
+20be1362eac7f19d5ff3c69d0821d165ef7c29202b563c5e638c0f3092b192d8  0002-ntp_sources-decrease-maximum-re-resolving-delay.patch
+29040502f86c419dbfbc7e2627cc658a8df82b37da21b3d1fce2eed9136d8f99  chronyd.confd
+f3a2a5ff9800bfc6a49897c6c8f64d264a75fc2e65cd98e059beaf9e5446fd1b  chronyd.initd
+d25ce3f5ce4a28184931c68a97340a5b332cbaf071434d172f262122240ad652  chrony.logrotate
+43e1bf9c3b0eb95c6330afdc9063f24353086f057d258c00ea711975a86c1194  chrony.conf"
+sha512sums="e77686453692d1b7c71107df3beb5747dfaa97ecbe810edde90e60daa2f5516abd2298681a4af2bf142239c041280ae9ce43db7cc18ca2c95fdf957876d977f2  chrony-1.28.tar.gz
+5b1d0766eceee000d97dfb20c34f95319ac295729c16e571d7fe382e7d737c7335a1a98b67d89792056f969d4bb9eb7296c343ee4bb16c6a0805606f505d16c5  0001-uclibc-res-do-not-call-res_init.patch
+765687fe59ba0f0f254e2d443defdb451fe6371d13dc62692d86d935d938dc10eb54c24ea70589227cd519153f94ae5171fcf6a0a08a2e7baf7b76be8abd4ac2  0002-ntp_sources-decrease-maximum-re-resolving-delay.patch
+6919c7bddce2a8f81c0f2759c7c58506e97f89102bfeb7b5c19c6da5ed4cbd9070faddd4f3fb411bb4c653fffbdcc93a7f7dc810f38b199f038b1d4072f57640  chronyd.confd
+fdf97b2e6790b29ba1979326e553808712ba25b500e6c82346651b27711ba4b2e22f1bba9b26b6740127bd9ccaa25a7b7d27514a00489be5823a8bbf4cef13a8  chronyd.initd
+8c2f9b396bde7f0124fdc4bb25fb31d154ae4ec73717401e5dd36a3730cd55ff91e60c70bcafb917883e437993ee245ad56e7a12c3711b482c6df592896a42dc  chrony.logrotate
+23157310e9352736efb000fef9f37cb57bfdc3b0ee95bfd5022b8e00dbfb16bfede1692fd91a128a9bedebfcf938b1668fa0695a112bd0c24525487ee2a53c65  chrony.conf"
