community/genext2fs: upgrade to 1.6.3

diff --git a/community/genext2fs/fix-tests.patch b/community/genext2fs/fix-tests.patch
--- a/community/genext2fs/fix-tests.patch
+++ b/community/genext2fs/fix-tests.patch
@@ -194,3 +194,18 @@ skip block count test as command succeeds but block count difference is probably
  if [ "$used_inodes" -ge 212 ]; then
  	echo "  inode count ($used_inodes): PASS"
  else
+@@ -418,11 +418,11 @@
+ 	TZ=UTC-11 touch -t 200502070321.43 $test_dir/file1.txt $test_dir/subdir/file2.txt $test_dir/subdir $test_dir
+ 	./genext2fs -B $blocksz -N 32 -b 200 -d $test_dir -f -o Linux $test_img
+ 	pass=true
+-	if ! /usr/sbin/e2fsck -fn $test_img > /dev/null 2>&1; then
++	if ! e2fsck -fn $test_img > /dev/null 2>&1; then
+ 		echo "  -B $blocksz e2fsck: FAIL"; pass=false
+ 	fi
+-	v1=$(/usr/sbin/debugfs -R "cat file1.txt" $test_img 2>/dev/null)
+-	v2=$(/usr/sbin/debugfs -R "cat subdir/file2.txt" $test_img 2>/dev/null)
++	v1=$(debugfs -R "cat file1.txt" $test_img 2>/dev/null)
++	v2=$(debugfs -R "cat subdir/file2.txt" $test_img 2>/dev/null)
+ 	if [ "$v1" = "hello $blocksz" ] && [ "$v2" = "world $blocksz" ]; then
+ 		echo "  -B $blocksz contents: PASS"
+ 	else
