community/binaryen: upgrade to 105
Co-Authored-By: Jakub Jirutka <jakub@jirutka.cz>

diff --git a/community/binaryen/APKBUILD b/community/binaryen/APKBUILD
--- a/community/binaryen/APKBUILD
+++ b/community/binaryen/APKBUILD
@@ -1,14 +1,14 @@
 # Contributor: Jakub Jirutka <jakub@jirutka.cz>
 # Maintainer: Jakub Jirutka <jakub@jirutka.cz>
 pkgname=binaryen
-pkgver=98
-pkgrel=1
+pkgver=105
+pkgrel=0
 pkgdesc="Compiler infrastructure and toolchain library for WebAssembly, in C++"
 url="https://github.com/WebAssembly/binaryen"
-arch="all !s390x !mips !mips64"
+arch="all !s390x"
 license="Apache-2.0"
 makedepends="cmake python3"
-checkdepends="nodejs"
+checkdepends="filecheck llvm-test-utils nodejs"
 subpackages="$pkgname-dev"
 source="https://github.com/WebAssembly/binaryen/archive/version_$pkgver/binaryen-$pkgver.tar.gz"
 builddir="$srcdir/$pkgname-version_$pkgver"
@@ -31,8 +31,8 @@ check() {
 	# Tests are extremely chatty.
 	msg 'running tests with stdout/stderr redirected into ./check.log...'
 	python3 check.py --binaryen-bin build/bin > check.log 2>&1 || {
-		echo 'tests failed, printing last 100 lines of check.log:' >&2
-		tail -n 100 check.log
+		echo 'tests failed, printing last 1000 lines of check.log:' >&2
+		tail -n 1000 check.log
 		return 1
 	}
 }
@@ -42,5 +42,5 @@ package() {
 }
 
 sha512sums="
-b5678cd12a125f9a57add6ce3c220cd79226bbc71b8abb71951ef2095376549da8ba362cdf99e4d1a01211db91b63c1f5314fd5df68d56bfd36315e21368f8c0  binaryen-98.tar.gz
+5b16551fab37c660900abeae49fb4e23abc0b61165d326ce4db23959a0eab640df0df03c5649c0bcd35a8515b959a7a9d78d1014c4ea6cb08da4ef48f715f702  binaryen-105.tar.gz
 "
