main/gcc: do not paxmark if cross-building
paxctl rejects the binaries as invalid ELF images, because they aren't built for the system architecture

diff --git a/main/gcc/APKBUILD b/main/gcc/APKBUILD
--- a/main/gcc/APKBUILD
+++ b/main/gcc/APKBUILD
@@ -369,7 +369,10 @@ package() {
 	mv "$pkgdir"/usr/lib/*-gdb.py \
 		"$pkgdir"/usr/share/gdb/python/auto-load/usr/lib/
 
-	paxmark -pmrs "$pkgdir"/$_gcclibexec/cc1 || return 1
+	# only paxmark if cross-compiling, otherwise paxctl fails
+	if [ "$CBUILD" = "$CTARGET" ]; then
+		paxmark -pmrs "$pkgdir"/$_gcclibexec/cc1 || return 1
+	fi
 
 	# move ada runtime libs
 	if $LANG_ADA; then
