main/openrc: modloop.initd fix for boot media firmware import
fixes #18239
Boot media firmware files are pulled-in as symlinks and supplement modloop firmware files (override if same name).

diff --git a/main/openrc/modloop.initd b/main/openrc/modloop.initd
--- a/main/openrc/modloop.initd
+++ b/main/openrc/modloop.initd
@@ -96,7 +96,7 @@ start() {
 	ebegin "Mounting modloop $modloop"
 	mkdir -p /.modloop
 	if [ -n "$modloop" ]; then
-		verify_modloop "$modloop" || eerror "Failed to verify signature of $img!"
+		verify_modloop "$modloop" || eerror "Failed to verify signature of $modloop!"
 		mount -o loop,ro $modloop /.modloop
 		eend $? || return 1
 	else
@@ -131,14 +131,13 @@ start() {
 		rm -rf /lib/modules && ln -sf /.modloop/modules /lib/
 	fi
 
-	# copy firmware if there are any
+	# symlink firmware files
+	mkdir -p /lib/firmware
+	[ -z "$(ls -A /lib/firmware)" ] && [ -d /lib/modules/firmware ] && ln -s /lib/modules/firmware/* /lib/firmware/ 2>/dev/null
 	if [ -d $alpine_mnt/firmware ]; then
-	        ebegin "Copying firmware from $alpine_mnt/firmware"
-	        cp -R -a $alpine_mnt/firmware /lib/
-	        eend $?
-	elif  [ -d /lib/modules/firmware ]; then
-		rmdir /lib/firmware 2>/dev/null \
-			&& ln -s /lib/modules/firmware /lib/
+		ebegin "Linking firmware from $alpine_mnt/firmware on top"
+		ln -sf $alpine_mnt/firmware/* /lib/firmware/ 2>/dev/null
+		eend $?
 	fi
 	return 0
 }
@@ -151,6 +150,11 @@ stop() {
 			umount -d "$mnt" || ret=1
 		fi
 	done
+
+	# cleanup orphaned symlinks from modloop
+	find /lib/firmware -maxdepth 1 -type l -exec sh -c 'readlink "$0" | grep -q "^/lib/modules/firmware" && rm "$0"' {} \;
+	[ "$( readlink /lib/modules )" = "/.modloop/modules" ] && rm /lib/modules
+
 	eend $ret || return 1
 }
 
