community/py3-ufo2ft: upgrade to 2.31.0

diff --git a/community/py3-ufo2ft/APKBUILD b/community/py3-ufo2ft/APKBUILD
--- a/community/py3-ufo2ft/APKBUILD
+++ b/community/py3-ufo2ft/APKBUILD
@@ -1,8 +1,8 @@
 # Contributor: Leo <thinkabit.ukim@gmail.com>
 # Maintainer:
 pkgname=py3-ufo2ft
-pkgver=2.30.0
-pkgrel=1
+pkgver=2.31.0
+pkgrel=0
 pkgdesc="bridge from UFOs to FontTools objects"
 url="https://github.com/googlefonts/ufo2ft"
 arch="noarch"
@@ -17,12 +17,18 @@ depends="
 	python3
 	"
 makedepends="
-	py3-pytest-runner
-	py3-pytest-xdist
+	py3-gpep517
 	py3-setuptools
 	py3-setuptools_scm
+	py3-wheel
 	"
-checkdepends="py3-pytest py3-compreffor py3-skia-pathops"
+checkdepends="
+	py3-compreffor
+	py3-pytest
+	py3-pytest-runner
+	py3-pytest-xdist
+	py3-skia-pathops
+	"
 subpackages="$pkgname-pyc"
 source="$pkgname-$pkgver.tar.gz::https://github.com/googlefonts/ufo2ft/archive/v$pkgver.tar.gz"
 builddir="$srcdir/ufo2ft-$pkgver"
@@ -33,21 +39,29 @@ s390x)
 	;;
 esac
 
+# build() {
+# 	python3 setup.py build
+# 	# remove failing tests
+# 	rm tests/integration_test.py
+# }
 build() {
-	export SETUPTOOLS_SCM_PRETEND_VERSION=$pkgver
-	python3 setup.py build
-	# remove failing tests
-	rm tests/integration_test.py
+	SETUPTOOLS_SCM_PRETEND_VERSION=$pkgver \
+	gpep517 build-wheel \
+		--wheel-dir dist \
+		--output-fd 3 3>&1 >&2
 }
 
 check() {
-	PYTHONPATH="$PWD/build/lib" pytest -n4
+	python3 -m venv --clear --without-pip --system-site-packages testenv
+	testenv/bin/python3 -m installer dist/*.whl
+	testenv/bin/python3 -m pytest -n auto -p no:warnings
 }
 
 package() {
-	python3 setup.py install --skip-build --root="$pkgdir"
+	python3 -m installer -d "$pkgdir" \
+		dist/*.whl
 }
 
 sha512sums="
-921493d65285b42dc45fafab0c416fedac03163082d8cd6343c5b27e56a15ea2cae7b0f61fa0bd4b1b8631186ea60c0801e1fc2e653fdacd603c5959bd7ee983  py3-ufo2ft-2.30.0.tar.gz
+c4198492d31268d00a57923837a8c832a50c6ca521c97955715c613ff843e37978111338b37792ec633ee8bb67b1add8f0f68875a705e8e4df531b41fcad54b2  py3-ufo2ft-2.31.0.tar.gz
 "
