core/busybox: upgrade to 1.13.0

diff --git a/core/busybox/APKBUILD b/core/busybox/APKBUILD
--- a/core/busybox/APKBUILD
+++ b/core/busybox/APKBUILD
@@ -1,40 +1,34 @@
 pkgname=busybox
-pkgver=1.12.1
-pkgrel=6
+pkgver=1.13.0
+pkgrel=0
 pkgdesc="Size optimized toolbox of many common UNIX utilities"
 url=http://busybox.net
 license=GPL-2
 depends=uclibc
 
-source="http://busybox.net/downloads/busybox-1.12.1.tar.bz2
-	http://busybox.net/downloads/fixes-1.12.1/busybox-1.12.1-basename.patch
-	http://busybox.net/downloads/fixes-1.12.1/busybox-1.12.1-grep.patch
-	http://busybox.net/downloads/fixes-1.12.1/busybox-1.12.1-lineedit.patch
-	http://busybox.net/downloads/fixes-1.12.1/busybox-1.12.1-login.patch
-	http://busybox.net/downloads/fixes-1.12.1/busybox-1.12.1-standalone.patch
-	http://busybox.net/downloads/fixes-1.12.1/busybox-1.12.1-vi.patch
-	bb-modprobe-v9.diff
+source="http://busybox.net/downloads/$pkgname-$pkgver.tar.bz2
+	http://busybox.net/downloads/fixes-$pkgver/$pkgname-$pkgver-ash.patch
+	http://busybox.net/downloads/fixes-$pkgver/$pkgname-$pkgver-getopt.patch
+	http://busybox.net/downloads/fixes-$pkgver/$pkgname-$pkgver-id.patch
+	http://busybox.net/downloads/fixes-$pkgver/$pkgname-$pkgver-inotify.patch
+	http://busybox.net/downloads/fixes-$pkgver/$pkgname-$pkgver-klogd.patch
+	http://busybox.net/downloads/fixes-$pkgver/$pkgname-$pkgver-lineedit.patch
+	http://busybox.net/downloads/fixes-$pkgver/$pkgname-$pkgver-modprobe.patch
 	$pkgname-1.12.1-vi-path.patch
 	$pkgname-1.11.1-bb.patch
-	$pkgname-1.12.0-mdev-exec.patch
-	$pkgname-1.12.1-iproute-metric.patch
 	busyboxconfig"
 
 build() {
 	cd $srcdir/$pkgname-$pkgver
 
 	#patches
-	patch -p1 -i ../$pkgname-1.12.1-basename.patch 		|| return 1
-	patch -p1 -i ../$pkgname-1.12.1-grep.patch 		|| return 1
-	patch -p1 -i ../$pkgname-1.12.1-lineedit.patch 		|| return 1
-	patch -p1 -i ../$pkgname-1.12.1-login.patch 		|| return 1
-	patch -p1 -i ../$pkgname-1.12.1-standalone.patch 	|| return 1
-	patch -p1 -i ../$pkgname-1.12.1-vi.patch 		|| return 1
-	patch -p1 -i ../$pkgname-1.12.1-vi-path.patch 		|| return 1
-	patch -p1 -i ../$pkgname-1.11.1-bb.patch 		|| return 1
-	patch -p0 -i ../$pkgname-1.12.0-mdev-exec.patch 	|| return 1
-	patch -p0 -i ../$pkgname-1.12.1-iproute-metric.patch 	|| return 1
-	patch -p0 -i ../bb-modprobe-v9.diff			|| return 1
+	for i in ../*.patch; do
+		msg "Applying $i"
+		if ! patch -p1 -i $i; then
+			error "$i failed"
+			return 1
+		fi
+	done
 
 	cp ../busyboxconfig .config
 	make silentoldconfig || return 1
@@ -42,16 +36,14 @@ build() {
 	make install DESTDIR=$pkgdir
 }
 
-md5sums="dc2e5e00d6fee8229ae92884c68733a7  busybox-1.12.1.tar.bz2
-70fedd0f03d92bceae053904bca11c1d  busybox-1.12.1-basename.patch
-76273f1580295a12270dcca0cdeb9a27  busybox-1.12.1-grep.patch
-62efeac9a6da03154cfb677935e84c34  busybox-1.12.1-lineedit.patch
-9c5d79a7426cfc2b4d7d1f0474d59b75  busybox-1.12.1-login.patch
-291c8564e3a25447bbcbfcc6865391cb  busybox-1.12.1-standalone.patch
-724e2613f9c9308f24a9c2de504de9a0  busybox-1.12.1-vi.patch
-a8aff3962d4481e8b402e739703fbe38  bb-modprobe-v9.diff
+md5sums="c9159004d24ea7b9f6a816048c5cd1e6  busybox-1.13.0.tar.bz2
+4d92a48bc78034d8d7db87034f27ab27  busybox-1.13.0-ash.patch
+c559acc16820d7351510ad9a71a463fd  busybox-1.13.0-getopt.patch
+93952435bdf3fc81217127f127a4233f  busybox-1.13.0-id.patch
+de12cfa77e5fa6923eac11fe5d8305c5  busybox-1.13.0-inotify.patch
+38a2101d0e01a736864ee0d3fb657571  busybox-1.13.0-klogd.patch
+c6ed3d86e147e0691fdd00bce335d901  busybox-1.13.0-lineedit.patch
+209bd64eba39e1ecfd119bf865aaa1d6  busybox-1.13.0-modprobe.patch
 f5a8ae3145aa249868c1a1abc319c228  busybox-1.12.1-vi-path.patch
 4c0f3b486eaa0674961b7ddcd0c60a9b  busybox-1.11.1-bb.patch
-b4ce6235028c2c20fa367375534c3a18  busybox-1.12.0-mdev-exec.patch
-54de0abe27e0ad362973be7fa81c487e  busybox-1.12.1-iproute-metric.patch
-a0c5e5edabf0a6cc73a2c3ce0ba60d74  busyboxconfig"
+0a32b03209b82e37e085f0bd06985518  busyboxconfig"
