community/wasm-bindgen: upgrade to 0.2.118
run tests on 32bit and big endian architectures and allow them to fail,
this will capture the runs in build logs to be compared between releases
and to share with upstream

diff --git a/community/wasm-bindgen/APKBUILD b/community/wasm-bindgen/APKBUILD
--- a/community/wasm-bindgen/APKBUILD
+++ b/community/wasm-bindgen/APKBUILD
@@ -1,6 +1,6 @@
 # Maintainer: kpcyrd <git@rxv.cc>
 pkgname=wasm-bindgen
-pkgver=0.2.117
+pkgver=0.2.118
 pkgrel=0
 pkgdesc="Interoperating JS and Rust code"
 url="https://github.com/rustwasm/wasm-bindgen"
@@ -15,11 +15,6 @@ source="https://github.com/rustwasm/wasm-bindgen/archive/refs/tags/$pkgver/wasm-
 	tests.patch
 	"
 options="net"
-
-case "$CARCH" in
-# FIXME most tests fail
-x86|s390x|arm*) options="$options !check" ;;
-esac
 
 prepare() {
 	# https://github.com/rustwasm/wasm-bindgen/issues/1819
@@ -37,12 +32,22 @@ build() {
 
 check() {
 	cd crates/cli
-	RUSTFLAGS= \
-	cargo test --frozen -- \
-		--skip no_duplicate_wasm_export_in_node_esm_atomics_debug \
-		--skip termination_abort_handler \
-		--skip termination_reinit
-	# the above tests make use of the -Z flag, only available in rust nightly
+
+	case "$CARCH" in
+	arm*|s390x|x86)
+		RUSTFLAGS= \
+		cargo test --frozen \
+			--no-fail-fast \
+			|| true # FIXME most tests fail
+		;;
+	*)
+		RUSTFLAGS= \
+		cargo test --frozen -- \
+			--skip no_duplicate_wasm_export_in_node_esm_atomics_debug \
+			--skip termination_abort_handler \
+			--skip termination_reinit
+		# the above tests make use of the -Z flag, only available in rust nightly
+	esac
 }
 
 package() {
@@ -53,7 +58,7 @@ package() {
 }
 
 sha512sums="
-5d216c924041e036ef4bab8dfde161e3f2cf575a9821a18115e4809334f58a645736538cd718b1878f55e46e67b4d784d18003496abe4033a5e6b923ea8a3d32  wasm-bindgen-0.2.117.tar.gz
-18bfac758c1d47e58fcb240e2e903b5876d16835ec61c1d7792e8e28ce44ba997c23400c88d2c946ca6117a29fde7257608ed0559fb2167d2e435bc5bc219a95  Cargo.lock
-a1b872bca381766704e773ece632926bddee6094799881776482bab6c60edad3358bdfe6ee3605562de84b49cd43fba2f15992f4da20749cbf277ba0d72ad1c4  tests.patch
+6581ba0ead95ef350c19b3e6a2ed3c4532451d24a28193a99f70c2300177b2a7f52af49cc5718c6d125bffdd72458e3ac10205cb8d7afcf53d09ff46cab4c0f8  wasm-bindgen-0.2.118.tar.gz
+d34c6f4557a6f0eccf3dd843704cda1df946b88323ff279c73ee79f35fd01a2c38139c0cdc16f3b5b69591f850493f49f95024ff54acf7e99909fc7aec5d458b  Cargo.lock
+23e90619665c294e1f7e2b86ea7050b407fbd94de3b41f1d4df8d7b6dbfd243745a9670bd0ea4e538d35cb64157f4f6303bcf051c71f5ffee9c91487d19ba3fe  tests.patch
 "
