community/py3-pybind11: upgrade to 2.11.0

diff --git a/community/py3-pybind11/APKBUILD b/community/py3-pybind11/APKBUILD
--- a/community/py3-pybind11/APKBUILD
+++ b/community/py3-pybind11/APKBUILD
@@ -1,8 +1,8 @@
 # Maintainer: Carlo Landmeter <clandmeter@alpinelinux.org>
 pkgname=py3-pybind11
 _pkgname=pybind11
-pkgver=2.10.4
-pkgrel=1
+pkgver=2.11.0
+pkgrel=0
 pkgdesc="Seamless operability between C++11 and Python"
 url="https://github.com/pybind/pybind11"
 arch="noarch"
@@ -10,14 +10,17 @@ license="MPL-2.0"
 makedepends="
 	boost-dev
 	cmake
+	py3-gpep517
 	py3-setuptools
+	py3-wheel
 	python3-dev
 	samurai
 	"
 checkdepends="
+	catch2
 	py3-pytest
 	"
-subpackages="$pkgname-dev"
+subpackages="$pkgname-dev $pkgname-pyc"
 source="$pkgname-$pkgver.tar.gz::https://github.com/pybind/pybind11/archive/v$pkgver.tar.gz"
 builddir="$srcdir/$_pkgname-$pkgver"
 
@@ -25,8 +28,7 @@ replaces="py-pybind11" # Backwards compatibility
 provides="py-pybind11=$pkgver-r$pkgrel" # Backwards compatibility
 
 build() {
-	# fails to build with fortify headers enabled
-	# https://github.com/pybind/pybind11/issues/1650
+	# fails with lto due to fortify-headers
 	export CXXFLAGS="$CXXFLAGS -U_FORTIFY_SOURCE"
 
 	python3 setup.py build
@@ -34,6 +36,7 @@ build() {
 	if [ "$CBUILD" != "$CHOST" ]; then
 		CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
 	fi
+	CXXFLAGS="$CXXFLAGS -flto=auto" \
 	cmake -B build -G Ninja \
 		-DCMAKE_BUILD_TYPE=None \
 		-DPYTHON_EXECUTABLE=/usr/bin/python3 \
@@ -41,6 +44,10 @@ build() {
 		-DUSE_PYTHON_INCLUDE_DIR=FALSE \
 		$CMAKE_CROSSOPTS
 	cmake --build build
+
+	gpep517 build-wheel \
+		--wheel-dir .dist \
+		--output-fd 3 3>&1 >&2
 }
 
 check() {
@@ -48,8 +55,8 @@ check() {
 }
 
 package() {
-	python3 setup.py install --root="$pkgdir" \
-		--install-headers=/usr/include/pybind11 --skip-build
+	python3 -m installer -d "$pkgdir" \
+		.dist/*.whl
 
 	DESTDIR="$pkgdir" cmake --install build
 }
@@ -61,5 +68,5 @@ dev() {
 }
 
 sha512sums="
-7970defbb6d057a44468ed707c80bfa6ef8c9578528fbc084b03aeea20a52dbd681581f82d55ff90af11ee89693379bd79e2ab6603239ba05b0aa8da29dd93c7  py3-pybind11-2.10.4.tar.gz
+10edfdc499ed70234de0796f79b9f3a7a14d4baf01fb09fedbd9126e0a13d9cdeb213950c53a8f7a67cd6049b1db31efacfe2192098236b242ad3685967ea907  py3-pybind11-2.11.0.tar.gz
 "
