community/hledger-stockquotes: upgrade to 0.1.2.2
required to build with new ghc

this version is published on github but not on hackage for some reason

diff --git a/community/hledger-stockquotes/APKBUILD b/community/hledger-stockquotes/APKBUILD
--- a/community/hledger-stockquotes/APKBUILD
+++ b/community/hledger-stockquotes/APKBUILD
@@ -1,22 +1,48 @@
 # Contributor: Dhruvin Gandhi <contact@dhruvin.dev>
 # Maintainer: Dhruvin Gandhi <contact@dhruvin.dev>
 pkgname=hledger-stockquotes
-pkgver=0.1.2.1
+pkgver=0.1.2.2
 pkgrel=0
 pkgdesc="hledger addon that pulls historical stock prices for commodities"
 url="https://github.com/prikhi/hledger-stockquotes#readme"
 arch="x86_64" # limited by GHC
 license="BSD-3-Clause"
 makedepends="ghc cabal libffi-dev ncurses-dev zlib-dev"
-source="https://hackage.haskell.org/package/hledger-stockquotes-$pkgver/hledger-stockquotes-$pkgver.tar.gz
-	cabal.project.freeze"
+source="$pkgname-$pkgver.tar.gz::https://github.com/prikhi/hledger-stockquotes/archive/refs/tags/$pkgver.tar.gz
+	cabal.config
+	"
 options="!check" # fail to build for some reason
 
 export CABAL_DIR="$srcdir"/cabal
 
+cabal_update() {
+	msg "Freezing $pkgname dependencies"
+
+	# Resolve deps and generate fresh cabal.config with version constraints.
+	(
+		cd "$builddir"
+		cabal update
+		cabal v1-freeze --strong-flags --shadow-installed-packages
+
+		# Add version tag at the first line.
+		sed -i "1i--$pkgver" "cabal.config"
+
+		mv "cabal.config" "$startdir/"
+	)
+
+	if ! abuild checksum; then
+		die "Failed to update checksum, run 'abuild checksum' manually"
+	fi
+}
+
 prepare() {
 	default_prepare
-	cp "$srcdir"/cabal.project.freeze .
+
+	if [ "$(head -n 1 "$srcdir/cabal.config")" != "--$pkgver" ]; then
+		die "Requirements file is outdated, run 'abuild cabal_update'"
+	fi
+
+	ln -sf "$srcdir/cabal.config" "$builddir/cabal.project.freeze"
 }
 
 build() {
@@ -36,6 +62,6 @@ package() {
 }
 
 sha512sums="
-7e1015e137765dce96ac289bef0d0bcc3344342285d33b1b3653ede9b9773582b5427e5d7ca6d2bacda8e3223e442d13ba304404a86f6358fd1660218a84c744  hledger-stockquotes-0.1.2.1.tar.gz
-09c19e0601437ddd5c25521f6be62e2af3f67baf7b8fbbbe872217160758d661cced8d67a52a86024e74a97578647066e8e2df0d458e02b03b16d9c89b7b0e24  cabal.project.freeze
+0b637efc9d99f1b283b53cd45331603a8badd30d91692a854786e91c536ddf2d336973f7c2b8f1d8e439dc730893d91fbd1c2a040bed448a59f1006bfee79653  hledger-stockquotes-0.1.2.2.tar.gz
+da132ba8d991de94d9ca4e72dea63b484b056f65882359954f917ac4f098ddd2ef08f890d27492f846f07868a1e5607562b1471ac62d6715c287d5ffb5002e24  cabal.config
 "
