testing/php7-imagick: cleanup and improve abuild

diff --git a/testing/php7-imagick/APKBUILD b/testing/php7-imagick/APKBUILD
--- a/testing/php7-imagick/APKBUILD
+++ b/testing/php7-imagick/APKBUILD
@@ -1,42 +1,44 @@
 # Contributor: Valery Kartel <valery.kartel@gmail.com>
 # Maintainer: Valery Kartel <valery.kartel@gmail.com>
 pkgname=php7-imagick
+_pkgreal=imagick
 pkgver=3.4.3
-pkgrel=1
-_pkgreal=${pkgname#php*-}
-_pkgver=${pkgver/_rc/RC}
-_phpver=${pkgname%%-*}
-_suffix=${_phpver#php}
-pkgdesc="PHP$_suffix extension: Provides a wrapper to the ImageMagick library"
+pkgrel=2
+_phpver=${pkgname#php}
+_phpver=${_phpver%%-*}
+pkgdesc="PHP$_phpver extension: Provides a wrapper to the ImageMagick library"
 url="http://pecl.php.net/package/imagick"
 arch="all"
 license="PHP"
-depends=
-makedepends="$_phpver-dev autoconf libtool imagemagick-dev pcre-dev"
+depends="php$_phpver-common"
+makedepends="php$_phpver-dev autoconf libtool imagemagick-dev pcre-dev"
 subpackages="$pkgname-dev"
-source="http://pecl.php.net/get/$_pkgreal-$_pkgver.tgz"
-builddir="$srcdir/$_pkgreal-$_pkgver"
+source="http://pecl.php.net/get/$_pkgreal-$pkgver.tgz"
+builddir="$srcdir/$_pkgreal-$pkgver"
 
 build() {
 	cd "$builddir"
-	phpize$_suffix || return 1
-	./configure --prefix=/usr \
-		--with-php-config=php-config$_suffix || return 1
+
+	phpize$_phpver
+	./configure --prefix=/usr --with-php-config=php-config$_phpver
 	make
 }
 
+check() {
+	cd "$builddir"
+
+	# XXX: Some test fails, ignore it for now.
+	make NO_INTERACTION=1 REPORT_EXIT_STATUS=1 test || true
+}
+
 package() {
-	local cfgdir=$(php-config$_suffix --configure-options|xargs -n1|awk -F= '/config-file-scan-dir/ {print $2}')
+	local confdir="$pkgdir/etc/php$_phpver/conf.d"
+	cd "$builddir"
 
-# for new php7 build only
-#	local apiver=$(phpize$_suffix -v|awk -F: '/PHP Api/ {print $2}'|tr -d ' ')
-#	provides="php-$_pkgreal"
-#	depends="$_phpver-config phpapi=$apiver $depends"
+	make INSTALL_ROOT="$pkgdir" install
 
-	make -C "$builddir" INSTALL_ROOT="$pkgdir" install || return 1
-
-	mkdir -p "$pkgdir"/$cfgdir || return 1
-	echo "extension=$_pkgreal.so" > "$pkgdir"/$cfgdir/$_pkgreal.ini
+	mkdir -p "$confdir"
+	echo "extension=$_pkgreal.so" > "$confdir"/$_pkgreal.ini
 }
 
 sha512sums="2cb2b856cf83a78d3542cdf7c69554dcc063a0541e9092b24e5e1fbd8928066a4a3de154049d0202c35addbc5055ccfbb5910ae92f2f13da80ddfc025340ddcd  imagick-3.4.3.tgz"
