community/tcl-lib: enable tests and update url

diff --git a/community/tcl-lib/APKBUILD b/community/tcl-lib/APKBUILD
--- a/community/tcl-lib/APKBUILD
+++ b/community/tcl-lib/APKBUILD
@@ -2,13 +2,13 @@
 # Maintainer: Galen Abell <galen@galenabell.com>
 pkgname=tcl-lib
 pkgver=1.21
-pkgrel=0
+pkgrel=1
 pkgdesc="Tcl standard library"
-url="https://www.tcl.tk/software/tcllib/"
+url="https://www.tcl-lang.org/software/tcllib/"
 arch="noarch"
 license="BSD-2-Clause"
+depends="tcl"
 makedepends="tcl-dev"
-options="!check" # no tests
 subpackages="$pkgname-doc"
 source="$pkgname-$pkgver.tar.gz::https://core.tcl-lang.org/tcllib/uv/tcllib-$pkgver.tar.gz"
 builddir="$srcdir/tcllib-$pkgver"
@@ -23,6 +23,38 @@ build() {
 		--infodir=/usr/share/info \
 		--localstatedir=/var
 	make
+}
+
+check() {
+	case "$CARCH" in
+	# Skip tests that take a long time to run
+	ppc64le)
+		rm -Rf	modules/doctools2idx/*.test \
+			modules/doctools2toc/*.test \
+			modules/pt/*.test
+		;;
+	# Skip tests that fail on big endian s390x
+	s390x)
+		rm -Rf	modules/fumagic/filetypes.test
+		;;
+	esac
+
+	# USER environment var required by the tests for "tool.tcl"
+	export USER="${USER:-$(id -un)}"
+	tclsh ./sak.tcl test run -l tcllibtest || true
+
+	if [ -s tcllibtest.failures ]; then
+		msg "Some tests failed:"
+		cat tcllibtest.failures
+		msg "Fail details:"
+		cat tcllibtest.faildetails
+		msg "Err details:"
+		cat tcllibtest.errdetails
+		return 1
+	else
+		msg "Congratulations, all tests passed!"
+		return 0
+	fi
 }
 
 package() {
