community/dotnet6-build: upgrade to 6.0.106

diff --git a/community/dotnet6-build/APKBUILD b/community/dotnet6-build/APKBUILD
--- a/community/dotnet6-build/APKBUILD
+++ b/community/dotnet6-build/APKBUILD
@@ -1,6 +1,10 @@
 # Maintainer: Antoine Martin (ayakael) <dev@ayakael.net>
 # Contributor: Antoine Martin (ayakael) <dev@ayakael.net>
 
+# secfixes:
+#   6.0.106-r0:
+#     - CVE-2022-30184
+
 #
 # Variables for dotnet build version 6.0
 # This APKBUILD is designed to be the same for version 6.0 and up
@@ -8,7 +12,7 @@
 #
 
 pkgname=dotnet6-build
-pkgver=6.0.105
+pkgver=6.0.106
 pkgrel=0
 
 # Tag of tarball generator. This may change from usual due to mistakes from upstream
@@ -61,7 +65,7 @@ _patches="
 	runtime_fix-musl-123.patch
 	runtime_lld-fix.patch
 	runtime_non-portable-distrorid-fix-alpine.patch
-	runtime_rid-alpine-316.patch
+	runtime_rid-alpine-317.patch
 	runtime_x86-64-use-system-libunwind.patch
 	sdk_add-zsh-compdef-completion-script.patch
 	sdk_portable-runtime-id.patch
@@ -191,7 +195,7 @@ _patch() {
 				case $package in
 					check*)cd "$_testdir" || { echo "$_testdir does not exist"; failed=$failed $i; continue; };;
 					build*)cd "$builddir";;
-					*) cd src/$package.* || { echo "$package does not exist for patch"; failed=$failed $i; continue; };;
+					*) cd src/$package || { echo "$package does not exist for patch"; failed=$failed $i; continue; };;
 				esac
 				patch -Np1 -i "$srcdir/$(filename_from_uri $i)" || failed="$failed $i"
 				cd "$builddir"
@@ -327,6 +331,9 @@ build() {
 		/p:LogVerbosity=minimal
 		/p:MinimalConsoleLogOutput=true
 		"
+
+	# Build uses a lot of storage space. This cleans-up as we build for pipelines.
+	local args="$args /p:CleanWhileBuilding=true"
 
 	# PrebuiltPackagesPath needs to be set despite --with-packages,
 	# as build tools has an error
@@ -482,7 +489,7 @@ zshcomp() {
 	depends="dotnet-host"
 
 	install -dm 755 "$subpkgdir"/usr/share/zsh/site-functions
-	install -m 755 "$builddir"/src/sdk.*/scripts/register-completions.zsh "$subpkgdir"/usr/share/zsh/site-functions/_dotnet
+	install -m 755 "$builddir"/src/sdk/scripts/register-completions.zsh "$subpkgdir"/usr/share/zsh/site-functions/_dotnet
 }
 
 bashcomp() {
@@ -494,7 +501,7 @@ bashcomp() {
 	depends="dotnet-host"
 
 	install -dm 755	"$subpkgdir"/usr/share/bash-completion/completions
-	install -m 755 "$builddir"/src/sdk.*/scripts/register-completions.bash "$subpkgdir"/usr/share/bash-completion/completions/_dotnet
+	install -m 755 "$builddir"/src/sdk/scripts/register-completions.bash "$subpkgdir"/usr/share/bash-completion/completions/_dotnet
 }
 
 doc() {
@@ -507,7 +514,7 @@ doc() {
 }
 
 sha512sums="
-e060451bd80a6bd6e06c800f60892c8848b7a757c94955fe0511c430b048db519b1ccdd5a83d6c8e467987bf00611cfad20cd72a5f4ee294308be03af23211c1  source-build-tarball-6.0.105.tar.gz
+8575d02d041d104105e39ae0524b58b2bb875addd5bf6bbe1fb616b2076cf8fadddfa0654cf7e14aa18ca4be0d1f0a897d9b668af84525b059fda92284315259  source-build-tarball-6.0.106.tar.gz
 fff94ca2b01ab360f0ef7d8b5408e49d867733f0008b8b70ebcc8eaaa8e832001510275f075848d24f9f71eb968daf57e30fe24f1ea9d0a38405936f9a2caf26  source-build-testssuite-ddc8576cc4ffccf6b102eed55125b2596336e684.tar.gz
 fc281df5fcf0d31dc9ff7f5b0e870960cfbe3c4fa0f6a6bb50b22c4ee18d2c608c827205bc79bd7f686d77ac917582fc26f68432cdd86c4a33b910c0c7416d09  source-build-turkey-71880bd94711519f7b786248a88a827a401207a2.tar.gz
 a2b21c38ed739f9bd18b39a28ef21b940ae32beeb2c8f99575289111e5ecaae40e017a500b3b452ef5df7c7e12dff2f8385acada92ca7507d1ed351c6aa9e311  aspnetcore_musl-build-fix.patch
@@ -520,12 +527,12 @@ ce36d0233d33cdc96888a64ab83a4099f877413269bcb5602704cedfb6aa89bf6d86157545f6f624
 385599c3b35cf34c7cc008ce1e28ab724f51567d759cbd04d64bd9977a139fa9c1d97e4038fc1249b3fca04e0abb99b7abfdde57d1ae4d83742ca76e6b7c40e0  installer_forgotten-MicrosoftAspNetCoreAppRuntimePac.patch
 a1e89c860bd6526293038746ed9a963e139b3f199931244b8a3d27e31c9eacba7484523e4151a1a0d7d3137edd271d907954b116619426f5db48361053740e27  installer_musl-build-fix.patch
 e14c5861c389c7e1d9a7ec96446be96335723bde403b685b16028a3f87ff6f6614400c876432d7302d3e2b4cd38e8d24979597c8ba909c0ad1d7b6cf2b4c3bfc  installer_portable-runtime-id.patch
-e8a4300e5d50622c9e9895779eab50a0a9ed28e03ea9ce5a2ca462b222910f650868441d8ed1f775855abab3431fd04ec20334da6b4c6f32e7a475d30aee1de3  installer_reprodicible-tarball.patch
+10b45ae9bb098945426527316466dfe69b24d72f6d6510912d57355bdf252f9e0f3b28ee6ff2731af443f60d40b6872998b522d17075ed07962f677373edeeed  installer_reprodicible-tarball.patch
 2e79e27b201a3e4423d63666b3dd575d0cb5ddbe258af24d9a2d0f9eb4cc8d177070249cfd08536fa7c3c6debdf939239a7e2c1aadd692d3e903bbb168f241b5  runtime_detect-armv8.patch
 aef649d2480d71ce68b030c0d67c2bfd965349a7ab52dbdca7c954edadb308ee6fbebf357113292d1323bfa9b2f8f01fe28d3904b2ebcc7a555742135bfdc726  runtime_fix-musl-123.patch
 dda6b463af8e0c8342b9c0d1a584f6d6410fb48df9fb0ef3c07d5ee7eb4abf2a29a01bf7a39fc70c2f5986c0b24c7bfe602cbfbeb1157cb0e0fb0eaa7fb03d1c  runtime_lld-fix.patch
 adb7537feb742f9b838323336e891b6e92c017215628ab2742841b6ec5945987d76082c6d42746f84062f0e537bb1d74cfa3989866fb105b9608af23abf17753  runtime_non-portable-distrorid-fix-alpine.patch
-1c737579bbc8152cb376632781188e543f4b64920adfa537d313366d55f23c896ecd61e366b5e801cd85441aadab8e61b9b775532e829cb347749279c8028902  runtime_rid-alpine-316.patch
+1fb414e925a516577240425739242af29eb22507c61c3fc9f7f8eb1f8c34650b00251148f6629704183959a6415bafcfc7442583ad7b1182c1c7c5b8bfd92b6a  runtime_rid-alpine-317.patch
 e8fba8748c600696a529dd9b861b2e4bffed9f6a56c1e6ec58c1444b567b92a00e6c310f835eb7915db5f924409782d6ec3d7ae98082bde22401ce7836ee7acb  runtime_x86-64-use-system-libunwind.patch
 55afa9c74be6f5a87f1ff5aa44caad094cf620eb4388f6407218acf3d58a878f5565a0e875e95c3dbe0efca1879c120ee4b8076c521bfc9d6069a652c4a4fdd8  sdk_add-zsh-compdef-completion-script.patch
 532534ed88fda70b5088b655af00a7218c72f99a65b35194ebcd960b354b24f043c4b63e72b915aaf69ba847f7befa7d650495a0741d7526accb58b425f74a26  sdk_portable-runtime-id.patch
