community/php7: really allow tests to fail on x86 and armhf

diff --git a/community/php7/APKBUILD b/community/php7/APKBUILD
--- a/community/php7/APKBUILD
+++ b/community/php7/APKBUILD
@@ -353,15 +353,15 @@ check() {
 	sed -i "/^PHP_TEST_SHARED_EXTENSIONS/,/extension=/ \
 		s|in \$(PHP_MODULES)\"*|in $php_modules|" Makefile
 
-	local report_exit_status=1
+	local allow_fail="no"
 	case "$CARCH" in
-		x86 | armhf) report_exit_status=0;;  # allow tests fail
+		x86 | armhf) allow_fail="yes"  # don't halt on test failures
 	esac
 
-	NO_INTERACTION=1 REPORT_EXIT_STATUS="$report_exit_status" \
+	NO_INTERACTION=1 REPORT_EXIT_STATUS=1 \
 		SKIP_SLOW_TESTS=1 SKIP_ONLINE_TESTS=1 TEST_TIMEOUT=10 \
 		TZ= LANG= LC_ALL= \
-		make test
+		make test || [ "$allow_fail" = yes ] || return 1
 
 	echo 'NOTE: We have skipped quite a lot tests, see disabled-tests.list.'
 }
