community/ocaml: improve code-style

diff --git a/community/ocaml/APKBUILD b/community/ocaml/APKBUILD
--- a/community/ocaml/APKBUILD
+++ b/community/ocaml/APKBUILD
@@ -20,15 +20,8 @@ builddir="$srcdir/$pkgname-$pkgver"
 build() {
 	cd "$builddir"
 
-	#strip out -fomit-frame-pointer due to -pg
-	local _cflags="$CFLAGS"
-	CFLAGS="-fPIC"
-	for i in $_cflags; do
-		case $i in
-		-fomit-frame-pointer);;
-		*) CFLAGS="$CFLAGS $i";;
-		esac
-	done
+	# Strip out -fomit-frame-pointer due to -pg.
+	export CFLAGS="${CFLAGS/-fomit-frame-pointer/} -fPIC"
 
 	./configure -cc "${CC:-gcc}" \
 		--bindir /usr/bin \
@@ -38,22 +31,27 @@ build() {
 }
 
 check() {
-       cd "$builddir"
-       # there seem to be some spurious failures, ignore until fixed
-       make test || true
-       cd testsuite
-       make report || true
+	cd "$builddir"
+
+	# FIXME: there seem to be some spurious failures, ignore until fixed.
+	make test || true
+	make -C testsuite report || true
 }
 
 package() {
 	cd "$builddir"
-	make BINDIR="$pkgdir"/usr/bin LIBDIR="$pkgdir"/usr/lib/ocaml MANDIR="$pkgdir"/usr/share/man install
+
+	make install \
+		BINDIR="$pkgdir"/usr/bin \
+		LIBDIR="$pkgdir"/usr/lib/ocaml \
+		MANDIR="$pkgdir"/usr/share/man
 
 	install -Dm644 LICENSE "$pkgdir"/usr/share/licenses/$pkgname/LICENSE
 	install -Dm644 Changes "$pkgdir"/usr/share/doc/$pkgname/Changes
 
 	find "$pkgdir"/usr/lib/ocaml -name \*.ml -delete
 }
+
 sha512sums="42560874ce363212fa4e862138d7260113bc8dff8b39c040332bbd9b039ba938788344ba8ce63ffc0a251bf21a6e493f3c1e505b6f51db6fec4d21578921060e  ocaml-4.06.1.tar.gz
 75c67e143a4a05b334bdebbad48ded1e04d383d8ea9b747df2633a5af96b1115b502510faf57753c71bbac38fbc9d9746b167861a63b2fd295901db0d22ea317  fix-mcontext-fields.patch
 b2cef41400b31c1dcfd206c1534827f7b33b0afd6234b26fb95cf15c092affa85c27a615c14ece254ec326430f31b58ca70b9cc23a84ebf8baac2624bd5b0a71  fix-segfault-in-ppc64le.patch"
