Patched abuild to use source mirror, and added options to enable/disable color.

diff --git a/main/abuild/APKBUILD b/main/abuild/APKBUILD
--- a/main/abuild/APKBUILD
+++ b/main/abuild/APKBUILD
@@ -2,13 +2,26 @@
 pkgdesc="Script to build Alpine Packages"
 pkgname=abuild
 pkgver=2.1
-pkgrel=0
+pkgrel=1
 url=http://git.alpinelinux.org/cgit/abuild/
 source="http://git.alpinelinux.org/cgit/abuild/snapshot/abuild-$pkgver.tar.bz2
-	"
+	0002-add-fetch-from-source-mirror.patch
+	0003-add-color-control-command-line-option.patch"
 depends="fakeroot file sudo pax-utils openssl apk-tools"
 makedepends="openssl-dev pkgconfig"
 license=GPL-2
+
+prepare() {
+	cd "$srcdir"/$pkgname-$_realver
+	# patches
+	for i in ../0002-add-fetch-from-source-mirror.patch ../0003-add-color-control-command-line-option.patch; do
+		msg "Applying $i"
+		if ! patch --verbose -p1 -i $i; then
+			error "$i failed"
+			return 1
+		fi
+	done
+}
 
 build() {
 	cd "$srcdir/$pkgname-$pkgver"
@@ -18,4 +31,6 @@ build() {
 	install -m 644 abuild.conf "$pkgdir"/etc/abuild.conf
 }
 
-md5sums="2268fa6147c8088139ef136184cd2ae0  abuild-2.1.tar.bz2"
+md5sums="2268fa6147c8088139ef136184cd2ae0  abuild-2.1.tar.bz2
+29b83cfe5c4b8e8491c6f2f073da4314  0002-add-fetch-from-source-mirror.patch
+d710ffb3c7f3eae52cac62bc2bf4f454  0003-add-color-control-command-line-option.patch"
