testing/handbrake: use external libs

diff --git a/testing/handbrake/APKBUILD b/testing/handbrake/APKBUILD
--- a/testing/handbrake/APKBUILD
+++ b/testing/handbrake/APKBUILD
@@ -2,7 +2,7 @@
 pkgname=handbrake
 _pkgname=HandBrake
 pkgver=0.10.2
-pkgrel=1
+pkgrel=2
 pkgdesc="Handbrake video transcoder"
 url="https://handbrake.fr"
 arch="x86_64 armhf"
@@ -14,28 +14,44 @@ makedepends="yasm autoconf libtool zlib-dev libbz2 libogg-dev libtheora-dev
 		tinyxml-dev fontconfig-dev libass-dev intltool glib-dev dbus-glib-dev
 		gtk+3.0-dev webkitgtk-dev eudev-dev libnotify-dev libdvdread-dev
 		gstreamer0.10-dev x264-dev lame-dev linux-headers cmake
-		autoconf automake"
+		autoconf automake ffmpeg-dev coreutils libdvdnav-dev 
+		libbluray-dev x265-dev libvpx-dev fdk-aac-dev"
 subpackages="$pkgname-lang $pkgname-gtk"
-source="${_pkgname}-${pkgver}.tar.bz2::https://handbrake.fr/rotation.php?file=${_pkgname}-${pkgver}.tar.bz2"
+source="${_pkgname}-${pkgver}.tar.bz2::https://handbrake.fr/rotation.php?file=${_pkgname}-${pkgver}.tar.bz2
+	handbrake-9999-fix-missing-x265-link-flag.patch
+	handbrake-9999-remove-dvdnav-dup.patch
+	handbrake-9999-remove-faac-dependency.patch"
 
 _builddir="$srcdir"/${_pkgname}-${pkgver}
 
+prepare() {
+        local i
+        cd "$_builddir"
+        for i in $source; do
+                case $i in
+                *.patch) msg $i; patch -p1 -i "$srcdir"/$i || return 1;;
+                esac
+        done
+	# build against external libs
+	sed -i 's:.*contrib/.*::g' \
+		make/include/main.defs \
+		|| die "Contrib removal failed."
+}
+
 build() {
         cd "$_builddir"
-	./configure --prefix=/usr  || return 1
+	./configure --prefix=/usr \
+		--force \
+		--verbose \
+		--disable-gtk-update-checks \
+		|| return 1
 
 	cd build
-	# This is retarded, but handbrake's "custom.defs" doesn't seem to work
-	make ffmpeg.configure || return 1
-	make ffmpeg.build CFLAGS="-D_GNU_SOURCE -I${_builddir}/build/contrib/include -I." || return 1
-
-	make build CFLAGS="-I${_builddir}/build/contrib/include -I."  || return 1
-
+	make || return 1
 }
 
 package() {
 	cd "$_builddir"/build
-
 	make -j1 install DESTDIR="$pkgdir"
 }
 
@@ -49,6 +65,15 @@ gtk() {
 
 }
 
-md5sums="db0a71147463664c4230ed3f1caf4fe8  HandBrake-0.10.2.tar.bz2"
-sha256sums="4cc3828393b26a982dbe00febd700c5090d3443c1d45492e0b373e02da73c699  HandBrake-0.10.2.tar.bz2"
-sha512sums="7059a88fac1e4810c54880eb4afe58716af7ac81e5b098e34f3a68c19d7c03e51b57e1a196603e2c8d377e94bb3a910d20f1d9ed62d3eab6422031e62730d4a2  HandBrake-0.10.2.tar.bz2"
+md5sums="db0a71147463664c4230ed3f1caf4fe8  HandBrake-0.10.2.tar.bz2
+9adb0a65dbdd959a07d903387046d9d6  handbrake-9999-fix-missing-x265-link-flag.patch
+b9aeb4db4da07d9966d4861d75de5fe7  handbrake-9999-remove-dvdnav-dup.patch
+48a93cb08aba88568fcfc43e16892621  handbrake-9999-remove-faac-dependency.patch"
+sha256sums="4cc3828393b26a982dbe00febd700c5090d3443c1d45492e0b373e02da73c699  HandBrake-0.10.2.tar.bz2
+b96fc610c716e13c2c5071d33a59861d6679f14c60d3cb8e475cb2d7cbb3829a  handbrake-9999-fix-missing-x265-link-flag.patch
+1418b164818d5c17a0dd87f13773cadad7c05827e38ea884e7a8a10750401ceb  handbrake-9999-remove-dvdnav-dup.patch
+05af966252b8b6e50d3c79c5dc258d8db95574335ca10d31b9f87af9a23b049b  handbrake-9999-remove-faac-dependency.patch"
+sha512sums="7059a88fac1e4810c54880eb4afe58716af7ac81e5b098e34f3a68c19d7c03e51b57e1a196603e2c8d377e94bb3a910d20f1d9ed62d3eab6422031e62730d4a2  HandBrake-0.10.2.tar.bz2
+9ca716b290f384db839609d176b6883c4dc1aaf31206b206cfd1f29c85bb134e29fbf72bda1a8589f76e1885019dbdee5a39d8299f7f0a20a6ef8a01868f4845  handbrake-9999-fix-missing-x265-link-flag.patch
+a3d57dd37d518286a62554cfcc4722d6fd588a0c3966d30785100edc4476febb2b48fc4f9b2a7eb5b5dc049043fabd4398e1e190e10cbd63c25b2936824977d3  handbrake-9999-remove-dvdnav-dup.patch
+9d070e50a9b7d4b8ac25b7d56bd341aca6dc979ba506c84f4b95109909f70020723915cd120bed24e84a8fc242ee3c3a5775f43a78b7995e53cd499444c9f6dc  handbrake-9999-remove-faac-dependency.patch"
