testing/mgba: upgrade to 0.10.1

diff --git a/testing/mgba/APKBUILD b/testing/mgba/APKBUILD
--- a/testing/mgba/APKBUILD
+++ b/testing/mgba/APKBUILD
@@ -2,23 +2,36 @@
 # Contributor: knuxify <knuxify@gmail.com>
 # Maintainer:
 pkgname=mgba
-pkgver=0.9.3
-pkgrel=3
+pkgver=0.10.1
+pkgrel=0
 pkgdesc="Game Boy Advance Emulator"
 url="https://mgba.io"
 arch="all !s390x" # broken on big-endian
 arch="$arch !armhf" # Missing qt5-qtmultimedia-dev
 license="MPL-2.0"
-makedepends="cmake qt5-qtmultimedia-dev qt5-qtbase-dev qt5-qttools-dev
-	sdl2-dev libzip-dev zlib-dev libpng-dev ffmpeg-dev imagemagick-dev
-	libepoxy-dev cmocka-dev libedit-dev py3-virtualenv python3-dev
-	libzip-tools elfutils-dev samurai
+makedepends="
+	cmake
+	cmocka-dev
+	elfutils-dev
+	ffmpeg-dev
+	imagemagick-dev
+	libedit-dev
+	libepoxy-dev
+	libpng-dev
+	libzip-dev
+	python3-dev
+	qt5-qtbase-dev
+	qt5-qtmultimedia-dev
+	qt5-qttools-dev
+	samurai
+	sdl2-dev
+	zlib-dev
 	"
 checkdepends="py3-cffi py3-cached-property"
-subpackages="$pkgname-doc libmgba:_libmgba libmgba-dev $pkgname-qt:_qt"
-source="mgba-$pkgver.tar.gz::https://github.com/mgba-emu/mgba/archive/$pkgver.tar.gz
-	ffmpeg5.patch
-	"
+subpackages="$pkgname-doc libmgba libmgba-dev $pkgname-qt"
+source="mgba-$pkgver.tar.gz::https://github.com/mgba-emu/mgba/archive/$pkgver.tar.gz"
+# the tests fail to build this release
+options="!check"
 
 build() {
 	if [ "$CBUILD" != "$CHOST" ]; then
@@ -29,9 +42,9 @@ build() {
 		-DCMAKE_INSTALL_LIBDIR=lib \
 		-DBUILD_SHARED_LIBS=True \
 		-DCMAKE_BUILD_TYPE=MinSizeRel \
-		-DBUILD_TEST:BOOL=ON \
-		-DBUILD_SUITE:BOOL=ON \
-		$CMAKE_CROSSOPTS .
+		-DBUILD_TEST="$(want_check && echo ON || echo OFF)" \
+		-DBUILD_SUITE="$(want_check && echo ON || echo OFF)" \
+		$CMAKE_CROSSOPTS
 	cmake --build build
 }
 
@@ -44,25 +57,23 @@ package() {
 	DESTDIR="$pkgdir" cmake --install build
 
 	# remove test leftovers
-	rm "$pkgdir"/usr/bin/mgba-fuzz
-	rm "$pkgdir"/usr/bin/tbl-fuzz
+	rm -f "$pkgdir"/usr/bin/mgba-fuzz
+	rm -f "$pkgdir"/usr/bin/tbl-fuzz
 }
 
-_qt() {
+qt() {
 	pkgdesc="Qt5 frontend for the mGBA emulator"
 
-	mkdir -p "$subpkgdir"/usr/share/applications
 	amove usr/bin/mgba-qt
-	amove usr/share/applications/mgba-qt.desktop
+	amove usr/share/applications
 }
 
-_libmgba() {
+libmgba() {
 	pkgdesc="Shared library of mGBA"
 
 	amove usr/lib
 }
 
 sha512sums="
-da65b3c7ec32d732163f129c4fd38949ae2da2980beb3257bf6def5e35534a27b6d30309bb3c9a8d651642f99e1a45db7a8577c8dbf5472153d4551167471b3a  mgba-0.9.3.tar.gz
-3f714c1c950636a5938d4226b8120bd566ec65a922a9ea43b01913e266b0b81e2334fef37b73fa3e1fd0cd2ffb619f14283ce5ded328e99b28af34f40c77b2c2  ffmpeg5.patch
+bb79d2380a4708b70daf95c9b403427f77254391b1e11d68411384f265a670907e64b842c9978c9be558ffad337b738d9d83988d52890f08aed7e7fc124f19d4  mgba-0.10.1.tar.gz
 "
