community/xournalpp: upgrade to 1.3.0
https://github.com/xournalpp/xournalpp/releases/tag/v1.3.0

diff --git a/community/xournalpp/APKBUILD b/community/xournalpp/APKBUILD
--- a/community/xournalpp/APKBUILD
+++ b/community/xournalpp/APKBUILD
@@ -2,13 +2,17 @@
 # Maintainer: mio <miyopan@e.email>
 maintainer="mio <miyopan@e.email>"
 pkgname=xournalpp
-pkgver=1.2.10
+pkgver=1.3.0
 pkgrel=0
-pkgdesc="Xournal++ is a handwriting notetaking software with PDF annotation support"
+pkgdesc="Handwriting notetaking software with PDF annotation support"
 url="https://github.com/xournalpp/xournalpp"
 arch="all"
 license="GPL-2.0-or-later"
 depends="adwaita-icon-theme"
+_gtestver=1.16.0
+_luaver=5.4
+# ninja-is-really-ninja: for C++20 modules support, required in >=1.3.0
+# https://github.com/michaelforney/samurai/issues/99
 makedepends="
 	cmake
 	glib-dev
@@ -23,21 +27,37 @@ makedepends="
 	libxml2-dev
 	libzip-dev
 	lsb-release
-	lua5.4-dev
+	lua$_luaver-dev
+	ninja-is-really-ninja
 	poppler-dev
 	portaudio-dev
-	samurai
+	qpdf-dev
+	"
+checkdepends="
+	font-cantarell
+	xvfb-run
 	"
 subpackages="$pkgname-dbg $pkgname-doc $pkgname-lang"
+# gtest: undefined reference to 'testing::internal::PrintU8StringTo'
+# https://github.com/google/googletest/issues/4591
 source="xournalpp-$pkgver.tar.gz::https://github.com/xournalpp/xournalpp/archive/v$pkgver.tar.gz
-	no-execinfo.patch
-	skip-tests.patch
+	gtest-$_gtestver.tar.gz::https://github.com/google/googletest/archive/v$_gtestver.tar.gz
+	skip-test.patch
 	"
 
 build() {
-	local cmake_crossopts
+	local cmake_crossopts gtest_opts
 	if [ "$CBUILD" != "$CHOST" ]; then
 		cmake_crossopts="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
+	fi
+
+	if want_check; then
+		gtest_opts="
+			-DDOWNLOAD_GTEST=ON
+			-DENABLE_CPPTRACE=OFF
+			-DFETCHCONTENT_FULLY_DISCONNECTED=ON
+			-DFETCHCONTENT_SOURCE_DIR_GOOGLETEST=$srcdir/googletest-$_gtestver
+			"
 	fi
 
 	# Increase stack-size to avoid crashes when using pen for input
@@ -45,19 +65,23 @@ build() {
 	cmake -B build -G Ninja \
 		-DCMAKE_INSTALL_PREFIX=/usr \
 		-DBUILD_SHARED_LIBS=True \
-		-DLUA_LIBRARIES="/usr/lib/lua5.4/liblua.so" \
-		-DENABLE_GTEST="$(want_check && echo on || echo off)" \
+		-DLUA_LIBRARIES="/usr/lib/lua$_luaver/liblua.so" \
+		-DENABLE_GTEST="$(want_check && echo ON || echo OFF)" \
 		-DCMAKE_BUILD_TYPE=MinSizeRel \
-		$cmake_crossopts
+		$cmake_crossopts $gtest_opts
 	cmake --build build --target all translations
 
 	if want_check; then
 		cmake --build build --target test-units
+		cmake --build build --target test-gtk-integration
 	fi
 }
 
 check() {
-	cmake --build build --target test
+	# *PaletteTabTest: (xournalpp_test:2648): Gtk-ERROR **: [...]
+	# failed to add UI: Failed to open file “”: No such file or directory
+	xvfb-run -a ctest --test-dir build \
+		-E "(UnrenderedPaletteTabTest|RenderedPaletteTabTest)"
 }
 
 package() {
@@ -66,7 +90,7 @@ package() {
 }
 
 sha512sums="
-1bdbbc53b31e295ced095667dfb1935c624ec967d2aaa29ccf244f9e0a661bc5397a5bc66365e8d250071c0393695b404616ceee68438c2cb282ffb6a895ff02  xournalpp-1.2.10.tar.gz
-1046141c3b51286fee439b4bba1ea247e7d121054b64134eecfb5859932d55d5afbf617052502bd7ca110928122b9690d463d579ed1575cf37b52ce318b087ca  no-execinfo.patch
-05d2e539958e50b9bb7b4f6cca391c931b6d1fc8303a3165ed7a0602e8a56396cd6b665f8fe6edac9eda9eca39cfae6d8e56abee8d924ebb9b0cd4c3ae558e29  skip-tests.patch
+35de6577261f07d0213551c1869af114ae4dfd295d414de78c4c209a78963a6aa5ffe322a4ba15b2f3240aac092b86635965b776a16a9417bd350eecfd87be40  xournalpp-1.3.0.tar.gz
+bec8dad2a5abbea8e9e5f0ceedd8c9dbdb8939e9f74785476b0948f21f5db5901018157e78387e106c6717326558d6642fc0e39379c62af57bf1205a9df8a18b  gtest-1.16.0.tar.gz
+71dc7f2cc89286a80493b01ad36ffbb6ad3045755417eedf6045b8422ad0ff937ecfda147322c7496a06d78183fce15ea6eddf012144dd5516d834e6fc2e16f2  skip-test.patch
 "
