community/nickel: upgrade to 1.14.0

diff --git a/community/nickel/APKBUILD b/community/nickel/APKBUILD
--- a/community/nickel/APKBUILD
+++ b/community/nickel/APKBUILD
@@ -1,20 +1,37 @@
 maintainer="Hoang Nguyen <folliekazetani@protonmail.com>"
 pkgname=nickel
-pkgver=1.9.1
+pkgver=1.14.0
 pkgrel=0
 pkgdesc="Generic configuration language for less"
 url="https://nickel-lang.org/"
-# s390x, loongarch64: nix crate fails to build
-# riscv64: check_manual_snippets_doc_manual_syntax_md test hangs indefinitely
-arch="all !s390x !riscv64 !loongarch64"
+# s390x: nix crate fails to build
+# riscv64: apply_client_options test hangs indefinitely
+arch="all !s390x !riscv64"
 license="MIT"
-makedepends="cargo cargo-auditable"
-checkdepends="python3"
-subpackages="$pkgname-doc $pkgname-language-server:_langserver"
-options="net"
-source="$pkgname-$pkgver.tar.gz::https://github.com/tweag/nickel/archive/refs/tags/$pkgver.tar.gz
-	explicit-dep-comrak.patch
+makedepends="
+	cargo
+	cargo-auditable
+	oniguruma-dev
+	py3-gpep517
+	py3-installer
+	py3-maturin
+	python3-dev
 	"
+checkdepends="python3"
+subpackages="
+	$pkgname-doc
+	$pkgname-language-server:_langserver
+	py3-$pkgname-pyc
+	py3-$pkgname:_py3
+	"
+options="net"
+source="
+	$pkgname-$pkgver.tar.gz::https://github.com/tweag/nickel/archive/refs/tags/$pkgver.tar.gz
+	explicit-dep-comrak.patch
+	nix.patch
+	"
+
+export RUSTONIG_DYNAMIC_LIBONIG=1
 
 prepare() {
 	default_prepare
@@ -22,13 +39,39 @@ prepare() {
 	cargo fetch --target="$CTARGET" --locked
 }
 
+# supported by nix
+_features="package-experimental"
+case "$CARCH" in
+	aarch64|x86|x86_64)
+		makedepends="$makedepends nix nix-dev"
+		_features="$_features,nix-experimental"
+		;;
+esac
+
 build() {
-	cargo auditable build --frozen --release --workspace \
-		--bin nickel --bin nls
+	cargo auditable build \
+		--frozen \
+		--release \
+		--workspace \
+		--features="$_features" \
+		--bin nickel \
+		--bin nls
+
+	cd py-nickel
+	gpep517 build-wheel \
+		--wheel-dir .dist \
+		--output-fd 3 3>&1 >&2
 }
 
 check() {
-	cargo test --frozen --workspace
+	# conflicting-index-deps fails on 32-bit architectures
+	# https://github.com/tweag/nickel/issues/2372
+	case "$CARCH" in
+		x86|armhf|armv7) _skip_tests="--skip conflicting-index-deps" ;;
+		*) _skip_tests="" ;;
+	esac
+
+	cargo test --frozen --workspace -- $_skip_tests
 }
 
 package() {
@@ -37,6 +80,9 @@ package() {
 		target/release/nls
 
 	install -Dm644 doc/manual/*.md -t "$pkgdir"/usr/share/doc/$pkgname/
+
+	python3 -m installer -d "$pkgdir" \
+		py-nickel/.dist/*.whl
 }
 
 _langserver() {
@@ -44,7 +90,14 @@ _langserver() {
 	amove usr/bin/nls
 }
 
+_py3() {
+	pkgdesc="Python 3 bindings for $pkgname"
+
+	amove usr/lib/python3.*
+}
+
 sha512sums="
-23b926125f1c5ad7ff9fae1105f63164ea71b44c3cb1e4568e9fe40dec37e96e464c9c4ab8b4272f28ab35de6c3fa833e04e4815143aef4ec5ae16b9b62f9be0  nickel-1.9.1.tar.gz
+89ec0b5c105e7feccb20b223ac5f9ffd75c524a5344e3c690f287e897e91a135b834f6c23df3143ec973b87c1ead9362b068d7dc4fe667d9755787d7778ad427  nickel-1.14.0.tar.gz
 a5d2c2899e81d480702f4f43d42373019a28d032e711a12d133b320ff4ad43b158bb4fb9577a5bfbc150131913d7267a8fe511b908b1e62b09de089fb440a677  explicit-dep-comrak.patch
+18cd28bdcd03d50d83cb66c9794ef7f8abdd99b3e038b5ae988e1337aabd621946aeb97d4c0a9d7d9f1e021dd9a76174e138d566739bb2b11565853d14024371  nix.patch
 "
