testing/pdal-python-plugins: upgrade to 1.6.2
https://github.com/PDAL/python-plugins/compare/1.2.1...1.6.2

- 1.6.2 includes numpy 2.1 support
- 1.6.1 includes pdal 2.8.0 support

Resolves build errors in 1.2.1 with pdal 2.8.0+:

```
/home/builder/builds/pdal-python-plugins/src/pdal-plugins-1.2.1/pdal/plang/Invocation.cpp: In member function 'void* pdal::plang::Invocation::extractArray(PyObject*, const std::string&, pdal::Dimension::Type, size_t&)':
/home/builder/builds/pdal-python-plugins/src/pdal-plugins-1.2.1/pdal/plang/Invocation.cpp:260:38: error: 'PyArray_Descr' has no member named 'elsize'
  260 |     if (static_cast<uint32_t>(dtype->elsize) != Dimension::size(t))
      |                                      ^~~~~~
/home/builder/builds/pdal-python-plugins/src/pdal-plugins-1.2.1/pdal/plang/Invocation.cpp:263:53: error: 'PyArray_Descr' has no member named 'elsize'
  263 |         oss << "dtype of array has size " << dtype->elsize
      |                                                     ^~~~~~
```

diff --git a/testing/pdal-python-plugins/APKBUILD b/testing/pdal-python-plugins/APKBUILD
--- a/testing/pdal-python-plugins/APKBUILD
+++ b/testing/pdal-python-plugins/APKBUILD
@@ -1,33 +1,43 @@
 # Contributor: Brian Vuyk <bvuyk@sama.com>
 # Maintainer: Brian Vuyk <bvuyk@sama.com>
 pkgname=pdal-python-plugins
-pkgver=1.2.1
-pkgrel=3
+pkgver=1.6.2
+pkgrel=0
 pkgdesc="Supports embedding Python in PDAL pipelines with the readers.numpy and filters.python drivers."
 url="https://github.com/PDAL/python-plugins"
-arch="aarch64 armhf armv7 ppc64le riscv64 x86 x86_64" # Exclude s390x due to test failures.
+arch="all !s390x" # Exclude s390x due to test failures.
 license="BSD-3-Clause"
 depends="python3 py3-numpy"
 checkdepends="pdal"
-makedepends="cmake pdal-dev py3-numpy-dev python3-dev py3-setuptools py3-packaging py3-scikit-build ninja"
-source="https://files.pythonhosted.org/packages/source/p/pdal-plugins/pdal-plugins-1.2.1.tar.gz"
-builddir="$srcdir/pdal-plugins-$pkgver"
+makedepends="cmake pdal-dev py3-gpep517 py3-numpy-dev py3-pybind11
+	py3-scikit-build-core python3-dev samurai"
+source="https://files.pythonhosted.org/packages/source/p/pdal-plugins/pdal_plugins-$pkgver.tar.gz
+	enable-tests.patch"
+builddir="$srcdir/pdal_plugins-$pkgver"
 
 build() {
-	python3 setup.py build -DWITH_TESTS=ON
+	gpep517 build-wheel \
+		--wheel-dir .dist \
+		--output-fd 3 3>&1 >&2
 }
 
 check() {
-	export PDAL_DRIVER_PATH=$(python3 -c "import os, skbuild; print(os.path.join(skbuild.constants.SKBUILD_DIR(), 'cmake-build'))")
+	export WHEEL_DIR="$(python3 -m "scikit_build_core.builder.wheel_tag")"
+	export PDAL_DRIVER_PATH="$builddir"/build/$WHEEL_DIR/Release
+	# filters.python should appear in pdal output
 	pdal --drivers
+
+	# Copy test data where tests can find them
+	cp -r "$builddir"/src/pdal/test/data $PDAL_DRIVER_PATH/src/pdal/test/
 	$PDAL_DRIVER_PATH/pdal_filters_python_test
 	$PDAL_DRIVER_PATH/pdal_io_numpy_test
 }
 
 package() {
-	python3 setup.py install --skip-build --root="$pkgdir"
+	python3 -m installer -d "$pkgdir" .dist/*.whl
 }
 
 sha512sums="
-328bb1960c823e442f08e3b3f7aca0e98a0755bc4fd655ad57d4efa202ecab4fc034ce85bb8015e7d0f0b13f4556b25cc9fb18d9f1b4281dbf65c23e21b2e577  pdal-plugins-1.2.1.tar.gz
+c8afd30dbce6c17609fb39bb88354237c5a52cf6987233f5e20afd6735df2c2481e5945c7e620816f6f483210ef4caf4e905afd2414e4065cd8cc8e0d08ef511  pdal_plugins-1.6.2.tar.gz
+6597ac5f0218a080ae0510f87c534ed794914c0882118524c0a9ff91435e348b6a1f689f1122fde02dea04524dcc2ad2dc5bfc74e1477c15f8bc451b1e1453c5  enable-tests.patch
 "
