testing/dkimproxy: Fixes #1474, bump pkgrel.

diff --git a/testing/dkimproxy/dkimproxy.in.initd b/testing/dkimproxy/dkimproxy.in.initd
--- a/testing/dkimproxy/dkimproxy.in.initd
+++ b/testing/dkimproxy/dkimproxy.in.initd
@@ -1,12 +1,31 @@
 #!/sbin/runscript
 
-command="/usr/sbin/${RC_SVCNAME}"
-command_args="${OPTS}"
-pidfile="/var/run/${RC_SVCNAME}.pid"
-description="SMTP proxy that verifies signature on incomming messages"
+description="SMTP proxy that verifies signature on incoming messages"
 
 depend() {
 	need net
 	after firewall
 }
 
+checkconfig() {
+	if [ ! -f ${CONFIGFILE} ]; then
+		eerror "Missing configuration file ${CONFIGFILE}"
+		return 1
+	fi
+}
+
+start() {
+	checkconfig || return 1
+	ebegin "Starting dkimproxy.in"
+	start-stop-daemon --start -q --exec /usr/sbin/dkimproxy.in \
+		--pidfile "${PIDFILE}" --make-pidfile --background \
+		-- --conf_file=${CONFIGFILE} ${OPTS}
+	eend $?
+}
+
+
+stop() {
+	ebegin "Stopping dkimproxy.in"
+	start-stop-daemon --stop -q --pidfile "${PIDFILE}"
+	eend $?
+}
diff --git a/testing/dkimproxy/dkimproxy.out.initd b/testing/dkimproxy/dkimproxy.out.initd
--- a/testing/dkimproxy/dkimproxy.out.initd
+++ b/testing/dkimproxy/dkimproxy.out.initd
@@ -1,12 +1,31 @@
 #!/sbin/runscript
 
-command="/usr/sbin/${RC_SVCNAME}"
-command_args="${OPTS}"
-pidfile="/var/run/${RC_SVCNAME}.pid"
-description="SMTP proxy that signs outgoing messages"
+description="SMTP proxy that verifies signature on outgoing messages"
 
 depend() {
 	need net
 	after firewall
 }
 
+checkconfig() {
+	if [ ! -f ${CONFIGFILE} ]; then
+		eerror "Missing configuration file ${CONFIGFILE}"
+		return 1
+	fi
+}
+
+start() {
+	checkconfig || return 1
+	ebegin "Starting dkimproxy.out"
+	start-stop-daemon --start -q --exec /usr/sbin/dkimproxy.out \
+		--pidfile "${PIDFILE}" --make-pidfile --background \
+		-- --conf_file=${CONFIGFILE} ${OPTS}
+	eend $?
+}
+
+
+stop() {
+	ebegin "Stopping dkimproxy.out"
+	start-stop-daemon --stop -q --pidfile "${PIDFILE}"
+	eend $?
+}
