testing/logstash: update to version 2.4.0
Substantial rework of aport

diff --git a/testing/logstash/APKBUILD b/testing/logstash/APKBUILD
--- a/testing/logstash/APKBUILD
+++ b/testing/logstash/APKBUILD
@@ -1,64 +1,89 @@
 # Contributor: Steeve Chailloux <steeve@chaahk.com>
-# Maintainer:
+# Maintainer: Nathan Johnson <nathan@nathanjohnson.info>
 pkgname=logstash
-pkgver=1.4.2
-pkgrel=1
+pkgver=2.4.0
+pkgrel=0
 pkgdesc="A flexible, open source, data collection, parsing and enrichment pipeline"
 url="http://logstash.net"
 arch="noarch"
-license="apache"
-depends="openjdk7-jre-base"
+license="ASL 2.0"
+depends="openjdk8-jre-base bash java-jffi-native"
 depends_dev=""
-makedepends="$depends_dev"
+makedepends="$depends_dev ruby-json java-cacerts openjdk8 ruby-rake ruby-bundler ruby bash java-jffi-native"
 install="$pkgname.pre-install $pkgname.post-deinstall"
 pkgusers="logstash"
 subpackages=""
 source="
-    https://download.elasticsearch.org/${pkgname}/${pkgname}/${pkgname}-${pkgver}.tar.gz
-    $pkgname.confd
-    $pkgname.initd
-    "
-
-_builddir="${srcdir}/${pkgname}-${pkgver}"
-prepare() {
-	local i
-	cd "$_builddir"
-	for i in $source; do
-		case $i in
-		*.patch) msg $i; patch -p1 -i "$srcdir"/$i || return 1;;
-		esac
-	done
-}
-
+	${pkgname}-${pkgver}.tar.gz::https://github.com/elastic/${pkgname}/archive/v${pkgver}.tar.gz
+	gem.patch
+	$pkgname.confd
+	$pkgname.initd"
+builddir="${srcdir}/${pkgname}-${pkgver}"
 build() {
-    echo "Nothing to build"
+	export JAVA_HOME=/usr/lib/jvm/default-jvm
+	cd $builddir
+	rake bootstrap || return 1
+	rake test:install-core || return 1
+	rake artifact:tar || return 1
 }
 
 package() {
-	cd "$_builddir"
+	cd "$builddir"/build
+	tar xzf ${pkgname}-${pkgver}.tar.gz
+	cd ${pkgname}-${pkgver}
 
 	install -m755 -D "$srcdir"/$pkgname.initd \
 		"$pkgdir"/etc/init.d/$pkgname || return 1
 	install -m644 -D "$srcdir"/$pkgname.confd \
 		"$pkgdir"/etc/conf.d/$pkgname || return 1
 
-    # created the necessary dirs
-    install -dm755 -o logstash -g daemon "$pkgdir/usr/share/logstash" || return 1
-    install -dm755 -o logstash -g daemon "$pkgdir/var/log/logstash" || return 1
-    install -dm755 -o logstash -g daemon "$pkgdir/var/run/logstash" || return 1
-    install -dm755 -o logstash -g daemon "$pkgdir/etc/logstash" || return 1
+	# created the necessary dirs
+	install -o $pkgusers -g daemon -dm755 "$pkgdir/usr/share/logstash" || return 1
+	install -o $pkgusers -g daemon -dm755 "$pkgdir/var/log/logstash" || return 1
+	install -dm755 "$pkgdir/etc/logstash" || return 1
+	install -dm755 "$pkgdir/usr/bin" || return 1
 
-    # copy files
-    cp -r * "$pkgdir/usr/share/logstash/" || return 1
-    chown -R logstash:daemon "$pkgdir/usr/share/logstash/" || return 1
+	# copy files
+	cp -a bin "$pkgdir/usr/share/logstash/" || return 1
+	cp -a lib "$pkgdir/usr/share/logstash/" || return 1
+	cp -a vendor "$pkgdir/usr/share/logstash/" || return 1
+	cp Gemfile* "$pkgdir/usr/share/logstash/" || return 1
+
+	# fix perms - their tars strips exec perms from everything for some reason
+	# TODO - probably should fix rake, but I don't know rake --NJ
+	cd "$pkgdir"
+	find . -type d -exec chmod 755 {} \;
+	find . -type d -name bin -exec bash -c "chmod 755 {}/*" \;
+
+	# Clean up the jni dirs - these are statically linked to gnu libc6.so
+	# symlink the so's to our libjffi installed system-wide.  Ugly, but
+	# can't seem to make this work with jruby 9k from community.
+	cd "$pkgdir"/usr/share/logstash/vendor/jruby/lib/jni
+
+	# Delete arches / OSes that aren't for us
+	find . -type d -a -maxdepth 1 -a ! -name "*-Linux" -a ! -name ".*" -exec rm -rf {} \;
+	rm -rf ppc64*-Linux
+
+	# symlink the remaining .so's to the system wide ligjffi - this is
+	# a bit messy but only one of them will be inspected for a given install.
+	find . -type f -exec rm -f {} \; -exec bash -c "ln -s /usr/lib/libjffi-*.so {}" \; || return 1
+	chown -R $pkgusers:daemon "$pkgdir/usr/share/logstash/" || return 1
+
+	# symlinks for /usr/bin
+	cd "$pkgdir"/usr/bin
+	ln -s /usr/share/logstash/bin/logstash
+	ln -s /usr/share/logstash/bin/logstash-plugin
 }
 
-md5sums="6e6be734392e8c7d6d55e23d0bd8d2b3  logstash-1.4.2.tar.gz
+md5sums="334f95ec06fb6a511991a5b36f04ae67  logstash-2.4.0.tar.gz
+9cfc9c117ed00da3f4909e1275f8cea9  gem.patch
 27359d9e7e41af5fe4fd77998338ea1c  logstash.confd
-40465daf3f1bfbb160db982790bf46c9  logstash.initd"
-sha256sums="d5be171af8d4ca966a0c731fc34f5deeee9d7631319e3660d1df99e43c5f8069  logstash-1.4.2.tar.gz
+e819e39a444ede99806034ef8481e49c  logstash.initd"
+sha256sums="efd44b6d5a69a1ea0be4398d377e64abd625b70b55710ca47e03f08b919b707c  logstash-2.4.0.tar.gz
+c0a9caf9a7b732cf85764bacbb1cbaf431b827f4201ea1d676baf0c8efd8580f  gem.patch
 c9ecb570f2b33f5aededb590c65c4a9bb9b60321c1e05b9bb7b55cbde89c3cc7  logstash.confd
-79bff7a11265489b36db5df9e281691cd06c26b6ec727fd898821823e52c4c4b  logstash.initd"
-sha512sums="6bf0527446b51582fa996ae03566487f7d3de2262cf2b88c62ba2549b00027c4cd820547afb01678def235f0c49597c2b36daf69b5f3c5eb155933ca6c2b3b7b  logstash-1.4.2.tar.gz
+bfcdb917abc20f7259ba680f283d9111f319bbbb118056db117ccb9e9df80c61  logstash.initd"
+sha512sums="a3b9afa65941b5489f7e21f6e7fa396a2caaa09ec6d3c42ef65fd005b518de625e7296cc3fd3712cc52bd3aedef6fca69bf62095a7d3d25b3a7099ef367872d5  logstash-2.4.0.tar.gz
+f9e877f0f10a3e89b9eefc5a019b5aac0367cc08a9957b0a55d05a7bff9f97b8b4e1ff56495ecc1efacf97d0b6e64758771d76e8fab0858bb0b8dcf34f5764fb  gem.patch
 8491786f1e8f247a4c284bb5e7c0b0c1f8332a76e61e33053e07d850975f762526a7aa7217b073f0e5c4907c1b0029bcf679c41e0b9713ce12f97b28378590df  logstash.confd
-49f4785ef3f3389d5d521c4e33b6ffbb29a9192a6dd52af3e62d4e71c6a18b291461e18dce3f03e67856cc4647cf64c625e330353fd1f01f9e983800352b8652  logstash.initd"
+9e7f7f5910b95d24998ae55b5ad08429ec9e756a7537d55c3bceea9a888ec661de8490208dc870a575328dba1cb43dc4dd4d4e298ef949aef8563a3105078dfa  logstash.initd"
