main/slony1: fix logrotation
we fix logrotation by only supporting syslog and not redirect the slon
output to a given logfile.

This is becase when redirecting, the only way to do log rotation is restart
the service to reopen the log file. We do not want force restart of service
which will close open connections.

diff --git a/main/slony1/slony1.initd b/main/slony1/slony1.initd
--- a/main/slony1/slony1.initd
+++ b/main/slony1/slony1.initd
@@ -1,37 +1,41 @@
 #!/sbin/runscript
-# Copyright 1999-2004 Gentoo Foundation
-# Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo-x86/dev-db/slony1/files/slony1.init,v 1.2 2007/03/07 23:18:21 nakano Exp $
+
+pidfile=/var/run/slony/slony1.pid
+command=/usr/bin/slon
+config=/etc/slon.conf
 
 depend() {
-	need postgresql
+	need postgresql net
+	after firewall
+}
+
+start_pre() {
+	checkpath --directory ${pidfile%/*}
+	if ! [ -e "$config" ]; then
+		eerror "config file $config is missing"
+		return 1
+	fi
+	if [ -n "$LOGFILE" ]; then
+		ewarn "LOGFILE in /etc/conf.d/slony1 is ignored. Only syslog is supported."
+	fi
+	if [ -n "$LOGLEVEL" ]; then
+		ewarn "LOGLEVEL in /etc/conf.d/slony1 is ignored."
+	fi
 }
 
 start() {
 	ebegin "Starting slony1"
-	/usr/bin/slon -p /var/run/slony1.pid -d $LOGLEVEL $CLUSTER "dbname=$DBNAME user=$DBUSER host=$DBHOST" >> $LOGFILE 2>&1 &
-
-	while :
-	do
-		cnt=$(($cnt + 1))
-		if [ -f "/var/run/slony1.pid" ]; then
-			ret=0
-			break
-		fi
-
-		if [ $cnt -eq 30 ]; then
-			eerror "Please see log file: $LOGFILE"
-			ret=1
-			break
-		fi
-		sleep 1
-	done
-	eend $ret
-}
-
-stop() {
-	ebegin "Stopping slony1"
-	kill `cat /var/run/slony1.pid`
+	if [ -n "$CLUSTER" ]; then
+		set -- $CLUSTER "dbname=$DBNAME user=$DBUSER host=$DBHOST"
+	fi
+	start-stop-daemon --exec $command \
+		--pidfile "$pidfile" \
+		--background \
+		--wait 100 \
+		-- \
+		-p "$pidfile" \
+		-f "$config" \
+		"$@"
 	eend $?
 }
 
