community/mycroft-core: upgrade to 21.2.0

diff --git a/community/mycroft-core/0003-system-wide-setups.patch b/community/mycroft-core/0003-system-wide-setups.patch
--- a/community/mycroft-core/0003-system-wide-setups.patch
+++ b/community/mycroft-core/0003-system-wide-setups.patch
@@ -1,7 +1,7 @@
-From 06cc33c94b20a3e6ac37fb2f594b9bcaf8987ea6 Mon Sep 17 00:00:00 2001
+From 8418563970aa04fd516e196efc50e6cf58007002 Mon Sep 17 00:00:00 2001
 From: Bart Ribbers <bribbers@disroot.org>
 Date: Fri, 15 Jan 2021 12:59:25 +0100
-Subject: [PATCH 1/2] Replace mycroft-{start,stop} with scripts that can launch
+Subject: [PATCH] Replace mycroft-{start,stop} with scripts that can launch
  properly installed setups
 
 These scripts will work with system-wide setups
@@ -17,13 +17,15 @@ Also make sure these scripts are actually installed by setup.py.
 These changes should make it possible to create a PyPi package
 installable with pip.
 ---
- bin/mycroft-start | 157 ++++++++++++++++++++++++++++++++++++++++++++--
- bin/mycroft-stop  | 109 ++++++++++++++++++++++++++++++--
- setup.py          |   6 +-
- 3 files changed, 261 insertions(+), 11 deletions(-)
+ bin/mycroft-start      | 153 +++++++++++++++++++++++++++++++++++++++--
+ bin/mycroft-stop       | 109 +++++++++++++++++++++++++++--
+ dev_setup.sh           |  54 +++------------
+ requirements/tests.txt |   2 +-
+ setup.py               |   7 +-
+ 5 files changed, 270 insertions(+), 55 deletions(-)
 
 diff --git a/bin/mycroft-start b/bin/mycroft-start
-index 65723c2c373..36ddc9fcbe6 100755
+index 65723c2c3734..30cd1ecfdbbb 100755
 --- a/bin/mycroft-start
 +++ b/bin/mycroft-start
 @@ -1,4 +1,4 @@
@@ -32,7 +34,7 @@ index 65723c2c373..36ddc9fcbe6 100755
  
  # Copyright 2019 Mycroft AI Inc.
  #
-@@ -14,8 +14,155 @@
+@@ -14,8 +14,151 @@
  # See the License for the specific language governing permissions and
  # limitations under the License.
  
@@ -125,11 +127,7 @@ index 65723c2c373..36ddc9fcbe6 100755
 +
 +	# Launch process in background
 +	# Send logs to XDG Base Directories cache location
-+	if [ -n "${XDG_CACHE_HOME+x}" ]; then
-+		logdir="$XDG_CACHE_HOME/mycroft"
-+	else
-+		logdir="$HOME/.cache/mycroft"
-+	fi
++	logdir="${XDG_STATE_HOME:-$HOME/.local/state}/mycroft"
 +
 +	if [ ! -d "$logdir" ]; then
 +		mkdir -p "$logdir"
@@ -193,7 +191,7 @@ index 65723c2c373..36ddc9fcbe6 100755
 +		;;
 +esac
 diff --git a/bin/mycroft-stop b/bin/mycroft-stop
-index b86b0ea6557..289c736959a 100755
+index b86b0ea65577..289c736959ae 100755
 --- a/bin/mycroft-stop
 +++ b/bin/mycroft-stop
 @@ -1,4 +1,4 @@
@@ -314,11 +312,158 @@ index b86b0ea6557..289c736959a 100755
 +#	100 at least one process was stopped
 +#	120 if any process had to be killed
 +exit $result
+diff --git a/dev_setup.sh b/dev_setup.sh
+index 4290850bda03..7181c82f2ba1 100755
+--- a/dev_setup.sh
++++ b/dev_setup.sh
+@@ -25,6 +25,12 @@ set -Ee
+ cd $(dirname $0)
+ TOP=$(pwd -L)
+ 
++if [ -n "${XDG_CACHE_HOME+x}" ]; then
++	logdir="$XDG_CACHE_HOME/mycroft"
++else
++	logdir="$HOME/.cache/mycroft"
++fi
++
+ function clean_mycroft_files() {
+     echo '
+ This will completely remove any files installed by mycroft (including pairing
+@@ -34,11 +40,12 @@ Do you wish to continue? (y/n)'
+         read -N1 -s key
+         case $key in
+         [Yy])
+-            sudo rm -rf /var/log/mycroft
++            rm -rf $logdir
+             rm -f /var/tmp/mycroft_web_cache.json
+             rm -rf "${TMPDIR:-/tmp}/mycroft"
+             rm -rf "$HOME/.mycroft"
+             sudo rm -rf "/opt/mycroft"
++            ${VIRTUALENV}/bin/pip uninstall .
+             exit 0
+             ;;
+         [Nn])
+@@ -227,33 +234,6 @@ locally?'
+     fi
+ 
+     echo
+-    # Add mycroft-core/bin to the .bashrc PATH?
+-    sleep 0.5
+-    echo '
+-There are several Mycroft helper commands in the bin folder.  These
+-can be added to your system PATH, making it simpler to use Mycroft.
+-Would you like this to be added to your PATH in the .profile?'
+-    if get_YN ; then
+-        echo -e "$HIGHLIGHT Y - Adding Mycroft commands to your PATH $RESET"
+-
+-        if [[ ! -f ~/.profile_mycroft ]] ; then
+-            # Only add the following to the .profile if .profile_mycroft
+-            # doesn't exist, indicating this script has not been run before
+-            echo '' >> ~/.profile
+-            echo '# include Mycroft commands' >> ~/.profile
+-            echo 'source ~/.profile_mycroft' >> ~/.profile
+-        fi
+-
+-        echo "
+-# WARNING: This file may be replaced in future, do not customize.
+-# set path so it includes Mycroft utilities
+-if [ -d \"${TOP}/bin\" ] ; then
+-    PATH=\"\$PATH:${TOP}/bin\"
+-fi" > ~/.profile_mycroft
+-        echo -e "Type ${CYAN}mycroft-help$RESET to see available commands."
+-    else
+-        echo -e "$HIGHLIGHT N - PATH left unchanged $RESET"
+-    fi
+ 
+     # Create a link to the 'skills' folder.
+     sleep 0.5
+@@ -332,18 +312,15 @@ Please review the following package changes carefully."
+     fi
+ }
+ 
+-
+ function open_suse_install() {
+     $SUDO zypper install -y git python3 python3-devel libtool libffi-devel libopenssl-devel autoconf automake bison swig portaudio-devel mpg123 flac curl libicu-devel pkg-config libjpeg-devel libfann-devel python3-curses pulseaudio
+     $SUDO zypper install -y -t pattern devel_C_C++
+ }
+ 
+-
+ function fedora_install() {
+     $SUDO dnf install -y git python3 python3-devel python3-pip python3-setuptools python3-virtualenv pygobject3-devel libtool libffi-devel openssl-devel autoconf bison swig glib2-devel portaudio-devel mpg123 mpg123-plugins-pulseaudio screen curl pkgconfig libicu-devel automake libjpeg-turbo-devel fann-devel gcc-c++ redhat-rpm-config jq make
+ }
+ 
+-
+ function arch_install() {
+     $SUDO pacman -S --needed --noconfirm git python python-pip python-setuptools python-virtualenv python-gobject libffi swig portaudio mpg123 screen flac curl icu libjpeg-turbo base-devel jq pulseaudio pulseaudio-alsa
+ 
+@@ -356,7 +333,6 @@ function arch_install() {
+     )
+ }
+ 
+-
+ function centos_install() {
+     $SUDO yum install epel-release
+     redhat_common_install
+@@ -513,7 +489,7 @@ if ! grep -q "$TOP" $VENV_PATH_FILE ; then
+ ' "$VENV_PATH_FILE"
+ fi
+ 
+-# install required python modules
++# Install required python modules
+ if ! pip install -r requirements/requirements.txt ; then
+     echo 'Warning: Failed to install required dependencies. Continue? y/N'
+     read -n1 continue
+@@ -537,6 +513,8 @@ fi
+ if ! pip install -r requirements/tests.txt ; then
+     echo "Warning: Test requirements failed to install. Note: normal operation should still work fine..."
+ fi
++# Actually installing Mycroft and it's deps
++pip install .
+ 
+ SYSMEM=$(free | awk '/^Mem:/ { print $2 }')
+ MAXCORES=$(($SYSMEM / 2202010))
+@@ -582,15 +560,5 @@ chmod +x bin/mycroft-say-to
+ chmod +x bin/mycroft-skill-testrunner
+ chmod +x bin/mycroft-speak
+ 
+-# create and set permissions for logging
+-if [[ ! -w /var/log/mycroft/ ]] ; then
+-    # Creating and setting permissions
+-    echo 'Creating /var/log/mycroft/ directory'
+-    if [[ ! -d /var/log/mycroft/ ]] ; then
+-        $SUDO mkdir /var/log/mycroft/
+-    fi
+-    $SUDO chmod 777 /var/log/mycroft/
+-fi
+-
+ #Store a fingerprint of setup
+ md5sum requirements/requirements.txt requirements/extra-audiobackend.txt requirements/extra-stt.txt requirements/extra-mark1.txt requirements/tests.txt dev_setup.sh > .installed
+diff --git a/requirements/tests.txt b/requirements/tests.txt
+index 9e038123e51a..306320db3e8b 100644
+--- a/requirements/tests.txt
++++ b/requirements/tests.txt
+@@ -5,7 +5,7 @@ pytest-cov==2.8.1
+ cov-core==1.15.0
+ sphinx==2.2.1
+ sphinx-rtd-theme==0.4.3
+-git+https://github.com/behave/behave@v1.2.7.dev1
++behave @ git+https://github.com/behave/behave@v1.2.7.dev1
+ allure-behave==2.8.10
+ 
+ python-vlc==1.1.2
 diff --git a/setup.py b/setup.py
-index 963c503e4d2..89eefa496fc 100644
+index 963c503e4d2f..815fceaa4c65 100644
 --- a/setup.py
 +++ b/setup.py
-@@ -80,5 +80,9 @@ def required(requirements_file):
+@@ -66,6 +66,7 @@ def required(requirements_file):
+         'mark1': required('requirements/extra-mark1.txt'),
+         'stt': required('requirements/extra-stt.txt')
+     },
++    tests_require=required('requirements/tests.txt'),
+     packages=find_packages(include=['mycroft*']),
+     include_package_data=True,
+ 
+@@ -80,5 +81,9 @@ def required(requirements_file):
              'mycroft-enclosure-client=mycroft.client.enclosure.__main__:main',
              'mycroft-cli-client=mycroft.client.text.__main__:main'
          ]
@@ -329,74 +474,3 @@ index 963c503e4d2..89eefa496fc 100644
 +        'bin/mycroft-stop'
 +    ]
  )
-
-From d7727ae06432349782bea2b648dd91b19933cd9f Mon Sep 17 00:00:00 2001
-From: Bart Ribbers <bribbers@disroot.org>
-Date: Fri, 15 Jan 2021 13:18:35 +0100
-Subject: [PATCH 2/2] Update README to reflect properly installed setups
-
----
- README.md | 38 +++++++++++++++++++++++++++-----------
- 1 file changed, 27 insertions(+), 11 deletions(-)
-
-diff --git a/README.md b/README.md
-index 01958ef2c73..84937e30b9e 100644
---- a/README.md
-+++ b/README.md
-@@ -32,29 +32,45 @@ Mycroft is a hackable open source voice assistant.
- 
- ## Getting Started
- 
--First, get the code on your system!  The simplest method is via git ([git installation instructions](https://gist.github.com/derhuerst/1b15ff4652a867391f03)):
--- `cd ~/`
--- `git clone https://github.com/MycroftAI/mycroft-core.git`
--- `cd mycroft-core`
--- `bash dev_setup.sh`
-+Mycroft might be packaged by your distribution already, in that case installing it might be as simple as `apk add mycroft-core` or equivalent for your distribution.
-+Otherwise, the simplest method is downloading the latest release on the [Github releases page](https://github.com/MycroftAI/mycroft-core/releases) and unpacking it somewhere.
-+Then run `python3 setup.py install` in the unpacked directory.
- 
-+For development on Mycroft it's recommended to use Git instead ([git installation instructions](https://gist.github.com/derhuerst/1b15ff4652a867391f03)).
-+
-+```sh
-+cd ~/
-+git clone https://github.com/MycroftAI/mycroft-core.git
-+cd mycroft-core
-+./dev_setup.sh
-+```
- 
- This script sets up dependencies and a [virtualenv][about-virtualenv].  If running in an environment besides Ubuntu/Debian, Arch or Fedora you may need to manually install packages as instructed by dev_setup.sh.
- 
- [about-virtualenv]:https://virtualenv.pypa.io/en/stable/
- 
--NOTE: The default branch for this repository is 'dev', which should be considered a work-in-progress. If you want to clone a more stable version, switch over to the 'master' branch.
-+**NOTE:** The default branch for this repository is 'dev', which should be considered a work-in-progress. If you want to clone a more stable version, switch over to the 'master' branch.
- 
- ## Running Mycroft
- 
--Mycroft provides `start-mycroft.sh` to perform common tasks. This script uses a virtualenv created by `dev_setup.sh`.  Assuming you installed mycroft-core in your home directory run:
--- `cd ~/mycroft-core`
--- `./start-mycroft.sh debug`
-+Mycroft provides `mycroft-start` to perform common tasks. Assuming you installed mycroft-core via your systems package manager or via `setup.py`:
-+
-+```sh
-+mycroft-start debug
-+```
- 
--The "debug" command will start the background services (microphone listener, skill, messagebus, and audio subsystems) as well as bringing up a text-based Command Line Interface (CLI) you can use to interact with Mycroft and see the contents of the various logs. Alternatively you can run `./start-mycroft.sh all` to begin the services without the command line interface.  Later you can bring up the CLI using `./start-mycroft.sh cli`.
-+The "debug" command will start the background services (microphone listener, skill, messagebus, and audio subsystems) as well as bringing up a text-based Command Line Interface (CLI) you can use to interact with Mycroft and see the contents of the various logs.
-+Alternatively you can run `mycroft-start all` to begin the services without the command line interface.
-+Later you can bring up the CLI using `mycroft-start cli`.
- 
- The background services can be stopped as a group with:
--- `./stop-mycroft.sh`
-+
-+```sh
-+mycroft-stop
-+```
-+
-+If you want to develop for Mycroft, please use `start-mycroft.sh` and `stop-mycroft.sh` instead of the aforementioned commands.
-+These provide extra options for development purposes.
- 
- ## Using Mycroft
- 
