community/mycroft-core: upgrade to 21.2.2

diff --git a/community/mycroft-core/0003-system-wide-setups.patch b/community/mycroft-core/0003-system-wide-setups.patch
--- a/community/mycroft-core/0003-system-wide-setups.patch
+++ b/community/mycroft-core/0003-system-wide-setups.patch
@@ -1,4 +1,4 @@
-From b970ba2f07116813640324301089d203200096f6 Mon Sep 17 00:00:00 2001
+From 927c812c3a2a7be503d929070c189b9aaac97896 Mon Sep 17 00:00:00 2001
 From: Bart Ribbers <bribbers@disroot.org>
 Date: Fri, 15 Jan 2021 12:59:25 +0100
 Subject: [PATCH 1/2] Replace mycroft-{start,stop} with scripts that can launch
@@ -19,12 +19,13 @@ installable with pip.
 ---
  bin/mycroft-start      | 153 +++++++++++++++++++++++++++++++++++++++--
  bin/mycroft-stop       | 109 +++++++++++++++++++++++++++--
- requirements/tests.txt |   2 +-
- setup.py               |   7 +-
- 5 files changed, 270 insertions(+), 55 deletions(-)
+ dev_setup.sh           |  82 ++++------------------
+ requirements/tests.txt |   4 +-
+ setup.py               |   9 ++-
+ 5 files changed, 276 insertions(+), 81 deletions(-)
 
 diff --git a/bin/mycroft-start b/bin/mycroft-start
-index 65723c2c3734..30cd1ecfdbbb 100755
+index cec59efaec8..94fedf9a7a3 100755
 --- a/bin/mycroft-start
 +++ b/bin/mycroft-start
 @@ -1,4 +1,4 @@
@@ -38,12 +39,12 @@ index 65723c2c3734..30cd1ecfdbbb 100755
  # limitations under the License.
  
 -SOURCE="${BASH_SOURCE[0]}"
--cd -P "$( dirname "$SOURCE" )"/..
+-cd -P "$( dirname "$SOURCE" )"/.. || exit
 -DIR="$( pwd )"
 +script=${0}
 +script=${script##*/}
  
--. "$DIR/start-mycroft.sh" $@
+-. "$DIR/start-mycroft.sh" "$@"
 +help() {
 +	echo "${script}:  Mycroft command/service launcher"
 +	echo "usage: ${script} [COMMAND] [restart] [params]"
@@ -97,7 +98,7 @@ index 65723c2c3734..30cd1ecfdbbb 100755
 +launch_process() {
 +	name_to_script_path "${1}"
 +
-+	# Luanch process in foreground
++	# Launch process in foreground
 +	echo "Starting $1"
 +	python3 -m ${_module} "$_params"
 +}
@@ -190,7 +191,7 @@ index 65723c2c3734..30cd1ecfdbbb 100755
 +		;;
 +esac
 diff --git a/bin/mycroft-stop b/bin/mycroft-stop
-index b86b0ea65577..289c736959ae 100755
+index dc79ca34a8b..289c736959a 100755
 --- a/bin/mycroft-stop
 +++ b/bin/mycroft-stop
 @@ -1,4 +1,4 @@
@@ -204,12 +205,12 @@ index b86b0ea65577..289c736959ae 100755
  # limitations under the License.
  
 -SOURCE="${BASH_SOURCE[0]}"
--cd -P "$( dirname "$SOURCE" )"/..
+-cd -P "$( dirname "$SOURCE" )"/.. || exit
 -DIR="$( pwd )"
 +script=${0}
 +script=${script##*/}
  
--. "$DIR/stop-mycroft.sh" $@
+-. "$DIR/stop-mycroft.sh" "$@"
 +help() {
 +	echo "${script}:  Mycroft service stopper"
 +	echo "usage: ${script} [service]"
@@ -311,31 +312,181 @@ index b86b0ea65577..289c736959ae 100755
 +#	100 at least one process was stopped
 +#	120 if any process had to be killed
 +exit $result
+diff --git a/dev_setup.sh b/dev_setup.sh
+index 4cfe6ca05a1..5d0eef22604 100755
+--- a/dev_setup.sh
++++ b/dev_setup.sh
+@@ -25,6 +25,8 @@ set -Ee
+ cd $(dirname $0)
+ TOP=$(pwd -L)
+ 
++logdir="${XDG_CACHE_HOME:-$HOME/.cache}/mycroft"
++
+ function clean_mycroft_files() {
+     echo '
+ This will completely remove any files installed by mycroft (including pairing
+@@ -34,11 +36,20 @@ Do you wish to continue? (y/n)'
+         read -N1 -s key
+         case $key in
+         [Yy])
+-            sudo rm -rf /var/log/mycroft
++            rm -rf $logdir
+             rm -f /var/tmp/mycroft_web_cache.json
+             rm -rf "${TMPDIR:-/tmp}/mycroft"
+             rm -rf "$HOME/.mycroft"
+-            sudo rm -rf "/opt/mycroft"
++
++            # If the following directories don't exist anyway we don't have to use sudo
++            # These directories aren't used anymore anyway and are only leftovers
++            if [ -d "/var/log/mycroft" ]; then
++                sudo rm -rf /var/log/mycroft
++            fi
++            if [ -d "/opt/mycroft" ]; then
++                sudo rm -rf /opt/mycroft
++            fi
++            ${VIRTUALENV}/bin/pip uninstall .
+             exit 0
+             ;;
+         [Nn])
+@@ -253,33 +264,6 @@ locally?'
+     fi
+ 
+     echo
+-    # Add mycroft-core/bin to the .bashrc PATH?
+-    sleep 0.5
+-    echo '
+-There are several Mycroft helper commands in the bin folder.  These
+-can be added to your system PATH, making it simpler to use Mycroft.
+-Would you like this to be added to your PATH in the .profile?'
+-    if get_YN ; then
+-        echo -e "$HIGHLIGHT Y - Adding Mycroft commands to your PATH $RESET"
+-
+-        if [[ ! -f ~/.profile_mycroft ]] ; then
+-            # Only add the following to the .profile if .profile_mycroft
+-            # doesn't exist, indicating this script has not been run before
+-            echo '' >> ~/.profile
+-            echo '# include Mycroft commands' >> ~/.profile
+-            echo 'source ~/.profile_mycroft' >> ~/.profile
+-        fi
+-
+-        echo "
+-# WARNING: This file may be replaced in future, do not customize.
+-# set path so it includes Mycroft utilities
+-if [ -d \"${TOP}/bin\" ] ; then
+-    PATH=\"\$PATH:${TOP}/bin\"
+-fi" > ~/.profile_mycroft
+-        echo -e "Type ${CYAN}mycroft-help$RESET to see available commands."
+-    else
+-        echo -e "$HIGHLIGHT N - PATH left unchanged $RESET"
+-    fi
+ 
+     # Create a link to the 'skills' folder.
+     sleep 0.5
+@@ -358,18 +342,15 @@ Please review the following package changes carefully."
+     fi
+ }
+ 
+-
+ function open_suse_install() {
+     $SUDO zypper install -y git python3 python3-devel libtool libffi-devel libopenssl-devel autoconf automake bison swig portaudio-devel mpg123 flac curl libicu-devel pkg-config libjpeg-devel libfann-devel python3-curses pulseaudio
+     $SUDO zypper install -y -t pattern devel_C_C++
+ }
+ 
+-
+ function fedora_install() {
+     $SUDO dnf install -y git python3 python3-devel python3-pip python3-setuptools python3-virtualenv pygobject3-devel libtool libffi-devel openssl-devel autoconf bison swig glib2-devel portaudio-devel mpg123 mpg123-plugins-pulseaudio screen curl pkgconfig libicu-devel automake libjpeg-turbo-devel fann-devel gcc-c++ redhat-rpm-config jq make pulseaudio-utils
+ }
+ 
+-
+ function arch_install() {
+     $SUDO pacman -S --needed --noconfirm git python python-pip python-setuptools python-virtualenv python-gobject libffi swig portaudio mpg123 screen flac curl icu libjpeg-turbo base-devel jq pulseaudio pulseaudio-alsa
+ 
+@@ -382,7 +363,6 @@ function arch_install() {
+     )
+ }
+ 
+-
+ function centos_install() {
+     $SUDO yum install epel-release
+     redhat_common_install
+@@ -545,30 +525,8 @@ if ! grep -q "$TOP" $VENV_PATH_FILE ; then
+ ' "$VENV_PATH_FILE"
+ fi
+ 
+-# install required python modules
+-if ! pip install -r requirements/requirements.txt ; then
+-    echo 'Warning: Failed to install required dependencies. Continue? y/N'
+-    read -n1 continue
+-    if [[ $continue != 'y' ]] ; then
+-        exit 1
+-    fi
+-fi
+-
+-# install optional python modules
+-if [[ ! $(pip install -r requirements/extra-audiobackend.txt) ||
+-	! $(pip install -r requirements/extra-stt.txt) ||
+-	! $(pip install -r requirements/extra-mark1.txt) ]] ; then
+-    echo 'Warning: Failed to install some optional dependencies. Continue? y/N'
+-    read -n1 continue
+-    if [[ $continue != 'y' ]] ; then
+-        exit 1
+-    fi
+-fi
+-
+-
+-if ! pip install -r requirements/tests.txt ; then
+-    echo "Warning: Test requirements failed to install. Note: normal operation should still work fine..."
+-fi
++# Actually install Mycroft and it's deps
++pip install -e ".[test,audio-backend,stt,mark1]"
+ 
+ SYSMEM=$(free | awk '/^Mem:/ { print $2 }')
+ MAXCORES=$(($SYSMEM / 2202010))
+@@ -614,15 +572,5 @@ chmod +x bin/mycroft-say-to
+ chmod +x bin/mycroft-skill-testrunner
+ chmod +x bin/mycroft-speak
+ 
+-# create and set permissions for logging
+-if [[ ! -w /var/log/mycroft/ ]] ; then
+-    # Creating and setting permissions
+-    echo 'Creating /var/log/mycroft/ directory'
+-    if [[ ! -d /var/log/mycroft/ ]] ; then
+-        $SUDO mkdir /var/log/mycroft/
+-    fi
+-    $SUDO chmod 777 /var/log/mycroft/
+-fi
+-
+ #Store a fingerprint of setup
+ md5sum requirements/requirements.txt requirements/extra-audiobackend.txt requirements/extra-stt.txt requirements/extra-mark1.txt requirements/tests.txt dev_setup.sh > .installed
 diff --git a/requirements/tests.txt b/requirements/tests.txt
-index 9e038123e51a..306320db3e8b 100644
+index ca6addcc0d6..69c1ad42938 100644
 --- a/requirements/tests.txt
 +++ b/requirements/tests.txt
-@@ -5,7 +5,7 @@ pytest-cov==2.8.1
+@@ -5,8 +5,8 @@ pytest-cov==2.8.1
  cov-core==1.15.0
  sphinx==2.2.1
  sphinx-rtd-theme==0.4.3
--git+https://github.com/behave/behave@v1.2.7.dev1
-+behave @ git+https://github.com/behave/behave@v1.2.7.dev1
+-https://github.com/krisgesling/tag-expressions-python/tarball/master/
+-https://github.com/krisgesling/behave/tarball/master/
++cucumber-tag-expressions @ git+https://github.com/krisgesling/tag-expressions-python@master
++behave @ git+https://github.com/krisgesling/behave@master
  allure-behave==2.8.10
  
  python-vlc==1.1.2
 diff --git a/setup.py b/setup.py
-index 963c503e4d2f..815fceaa4c65 100644
+index 963c503e4d2..afd950a97cb 100644
 --- a/setup.py
 +++ b/setup.py
-@@ -66,6 +66,7 @@ def required(requirements_file):
+@@ -64,7 +64,8 @@ def required(requirements_file):
+     extras_require={
+         'audio-backend': required('requirements/extra-audiobackend.txt'),
          'mark1': required('requirements/extra-mark1.txt'),
-         'stt': required('requirements/extra-stt.txt')
+-        'stt': required('requirements/extra-stt.txt')
++        'stt': required('requirements/extra-stt.txt'),
++        'test': required('requirements/tests.txt')
      },
-+    tests_require=required('requirements/tests.txt'),
      packages=find_packages(include=['mycroft*']),
      include_package_data=True,
- 
 @@ -80,5 +81,9 @@ def required(requirements_file):
              'mycroft-enclosure-client=mycroft.client.enclosure.__main__:main',
              'mycroft-cli-client=mycroft.client.text.__main__:main'
@@ -348,20 +499,20 @@ index 963c503e4d2f..815fceaa4c65 100644
 +    ]
  )
 
-From 55956b7c30106ec3a903d6544982a051929ecf10 Mon Sep 17 00:00:00 2001
+From eef76c203703239dc07281849df38995e43009f7 Mon Sep 17 00:00:00 2001
 From: Bart Ribbers <bribbers@disroot.org>
 Date: Fri, 15 Jan 2021 13:18:35 +0100
 Subject: [PATCH 2/2] Update README to reflect properly installed setups
 
 ---
- README.md | 43 ++++++++++++++++++++++++++++++++-----------
- 1 file changed, 32 insertions(+), 11 deletions(-)
+ README.md | 44 ++++++++++++++++++++++++++++++++------------
+ 1 file changed, 32 insertions(+), 12 deletions(-)
 
 diff --git a/README.md b/README.md
-index d34d08e3474b..ad8be331fe15 100644
+index d34d08e3474..6e69434d340 100644
 --- a/README.md
 +++ b/README.md
-@@ -32,29 +32,50 @@ Mycroft is a hackable open source voice assistant.
+@@ -32,29 +32,49 @@ Mycroft is a hackable open source voice assistant.
  
  ## Getting Started
  
@@ -372,23 +523,23 @@ index d34d08e3474b..ad8be331fe15 100644
 -- `bash dev_setup.sh`
 +Mycroft might be packaged by your distribution already, in that case installing it might be as simple as `apk add mycroft-core` or equivalent for your distribution.
 +Otherwise, the simplest method is downloading the latest release on the [Github releases page](https://github.com/MycroftAI/mycroft-core/releases) and unpacking it somewhere.
-+Then run the following commandsd in the unpacked directory.
++Then run the following commands in the unpacked directory.
  
 +```sh
-+pip install -r requirements/requirements.txt # This installs the required Python dependencies
-+pip install . # This actually installs mycroft-core
++pip install . # This actually installs Mycroft and it's dependencies
 +```
 +
 +For development on Mycroft it's recommended to use Git instead ([git installation instructions](https://gist.github.com/derhuerst/1b15ff4652a867391f03)).
-+
+ 
+-This script sets up dependencies and a [virtualenv][about-virtualenv].  If running in an environment besides Ubuntu/Debian, Arch or Fedora you may need to manually install packages as instructed by dev_setup.sh.
 +```sh
 +cd ~/
 +git clone https://github.com/MycroftAI/mycroft-core.git
 +cd mycroft-core
 +./dev_setup.sh
 +```
- 
- This script sets up dependencies and a [virtualenv][about-virtualenv].  If running in an environment besides Ubuntu/Debian, Arch or Fedora you may need to manually install packages as instructed by dev_setup.sh.
++
++This script sets up dependencies and a [virtualenv][about-virtualenv].  If running in an environment besides Ubuntu/Debian, Arch or Fedora you may need to manually install packages as instructed by `dev_setup.sh`.
  
  [about-virtualenv]:https://virtualenv.pypa.io/en/stable/
  
