main/ulogd: use supervise-daemon

diff --git a/main/ulogd/ulogd.initd b/main/ulogd/ulogd.initd
--- a/main/ulogd/ulogd.initd
+++ b/main/ulogd/ulogd.initd
@@ -1,12 +1,16 @@
 #!/sbin/openrc-run
-# Copyright 1999-2004 Gentoo Foundation
-# Distributed under the terms of the GNU General Public License v2
-# $Header: /var/www/viewcvs.gentoo.org/raw_cvs/gentoo-x86/app-admin/ulogd/files/ulogd,v 1.2 2004/07/13 16:32:25 aliz Exp $
+supervisor=supervise-daemon
 
-description="Netfilter userspace log daemon"
-description_reload="Reload configuration"
+name="ulogd"
+description="Netfilter userspace logging daemon"
+command="/usr/sbin/ulogd"
 
 extra_started_commands="reload"
+description_reload="Reload configuration"
+
+command_args="$ulogd_opts"
+command_user=root:wheel
+umask=027
 
 depend() {
 	before firewall
@@ -14,28 +18,17 @@ depend() {
 
 checkconfig() {
 	if [ ! -e /etc/ulogd.conf ]; then
-		eerror "You need /etc/ulogd.conf"
+		eerror "/etc/ulogd.conf is missing"
 		return 1
 	fi
 }
 
-start() {
-	checkconfig || return 1
-	ebegin "Starting ulogd"
-	start-stop-daemon --start --quiet --exec /usr/sbin/ulogd --group wheel \
-		--umask 027 -- $ARGS >/dev/null 2>&1
-	eend $?
-}	
-
-stop() {
-	ebegin "Stopping ulogd"
-	start-stop-daemon --stop --quiet --exec /usr/sbin/ulogd >/dev/null 2>&1
-	eend $?
-}	
-
 reload() {
-        ebegin "Reloading ulogd.conf file"
-	killall -HUP ulogd &>/dev/null
+	ebegin "Reloading $name"
+	supervise-daemon $RC_SVCNAME --signal HUP
 	eend $?
-}	
+}
 
+start_pre() {
+	checkconfig || return $?
+}
