testing/pandoc: add cabal_update

diff --git a/testing/pandoc/APKBUILD b/testing/pandoc/APKBUILD
--- a/testing/pandoc/APKBUILD
+++ b/testing/pandoc/APKBUILD
@@ -2,7 +2,7 @@
 # Maintainer: Jean-Louis Fuchs <jean-louis.fuchs@adfinis-sygroup.ch>
 pkgname=pandoc
 pkgver=2.19
-pkgrel=0
+pkgrel=1
 pkgdesc="universal markup converter"
 url="https://pandoc.org/"
 # limited by ghc
@@ -11,16 +11,45 @@ license="GPL-2.0-or-later"
 makedepends="ghc cabal zlib-dev libffi-dev"
 subpackages="$pkgname-doc"
 source="https://hackage.haskell.org/package/pandoc-$pkgver/pandoc-$pkgver.tar.gz
-	cabal.project.freeze
-	"
+	cabal.config
+"
 
 # Cabal seems to be built without sandbox, moving the cabal-dir into src
-export CABAL_DIR="$srcdir/cabal"
+export CABAL_DIR="$srcdir/.cabal"
+
+cabal_update() {
+	msg "Freezing $pkgname dependencies"
+
+	# Resolve deps and generate fresh cabal.config with version constraints.
+	cabal update
+	(
+		cd "$builddir"
+		cabal v1-freeze --shadow-installed-packages
+
+		# Add version tag at the first line.
+		sed -i "1i--$pkgver" "cabal.config"
+
+		mv "cabal.config" "$startdir/"
+	)
+
+	if ! abuild checksum; then
+		die "Failed to update checksum, run 'abuild checksum' manually"
+	fi
+}
 
 prepare() {
 	default_prepare
-	cp "$srcdir/cabal.project.freeze" .  # Created using "cabal freeze"
+
+	if [ "$(head -n 1 "$srcdir/cabal.config")" != "--$pkgver" ]; then
+		die "Requirements file is outdated, run 'abuild cabal_update'"
+	fi
+
+	ln -sf "$srcdir/cabal.config" "$builddir/cabal.project.freeze"
+}
+
+build() {
 	cabal update
+	cabal install --only-dependencies
 	cabal configure \
 		--prefix='/usr' \
 		--enable-tests \
@@ -29,10 +58,6 @@ prepare() {
 		--ghc-option="-j" \
 		--ghc-option="-O1" \
 		--flags="+embed_data_files -trypandoc +static"
-}
-
-build() {
-	cabal install --only-dependencies
 	cabal build --jobs=${JOBS:-1}
 }
 
@@ -51,5 +76,5 @@ package() {
 
 sha512sums="
 c0d9780fdd82d5c322644eb1af76f18df9371943c67c0760a2a1ab762d1165ea9c5b3309dd4c5c3b4c30043cb33027268293fccf3bf0d5ba5ba50ddb32f61eda  pandoc-2.19.tar.gz
-9ea10389c3d4c406ebb5a66503a9c146fa433ada42af44e32605cb24ac6820a3540c2dc1835ffe1e48e743888350cce6e2553a0b1fbcf4dc8cf60be11b2cfc7e  cabal.project.freeze
+506c220f7050b8b156f3e2c7d36f2d3d76ebe33af27fb580c1fd793a45d0a584d5d452d2bc1c3764e1d0067cccf0a629b9f6cb62c0394ab18d055ce1e88c4b14  cabal.config
 "
