main/clang14: install to llvm prefix
see next commit

diff --git a/main/clang14/APKBUILD b/main/clang14/APKBUILD
--- a/main/clang14/APKBUILD
+++ b/main/clang14/APKBUILD
@@ -5,7 +5,7 @@
 # Maintainer: Natanael Copa <ncopa@alpinelinux.org>
 pkgname=clang14
 pkgver=14.0.6
-pkgrel=2
+pkgrel=3
 _llvmver=${pkgver%%.*}
 pkgdesc="A C language family front-end for LLVM"
 arch="all"
@@ -50,13 +50,15 @@ build() {
 
 	if [ $_default_clang = yes ]; then
 		local extras=ON
+		local onlymain=OFF
 	else
 		local extras=OFF
+		local onlymain=ON
 	fi
 
 	cmake -B build -G Ninja -Wno-dev \
 		-DCMAKE_BUILD_TYPE=Release \
-		-DCMAKE_INSTALL_PREFIX=/usr \
+		-DCMAKE_INSTALL_PREFIX=/usr/lib/llvm$_llvmver \
 		-DCMAKE_MODULE_PATH="$srcdir/cmake-$pkgver.src/Modules" \
 		-DCLANG_BUILT_STANDALONE=ON \
 		-DCLANG_ENABLE_ARCMT=$extras \
@@ -67,17 +69,20 @@ build() {
 		-DCLANG_PYTHON_BINDINGS_VERSIONS="$python_version" \
 		-DCLANG_VENDOR=Alpine \
 		-DENABLE_LINKER_BUILD_ID=ON \
-		-DLIBCLANG_BUILD_STATIC=ON
+		-DLIBCLANG_BUILD_STATIC=ON \
+		-DLLVM_INSTALL_TOOLCHAIN_ONLY=$onlymain
 
 	ninja -C build clang-tblgen
 	ninja -C build
 
-	help2man --no-info \
-		--source "Alpine" \
-		--name "Alpine Clang $pkgver-r$pkgrel" \
-		--version-string "$pkgver-r$pkgrel" \
-		--help-option "--help-hidden" \
-		./build/bin/clang > clang.1
+	if [ "$_default_clang" = yes ]; then
+		help2man --no-info \
+			--source "Alpine" \
+			--name "Alpine Clang $pkgver-r$pkgrel" \
+			--version-string "$pkgver-r$pkgrel" \
+			--help-option "--help-hidden" \
+			./build/bin/clang > clang.1
+	fi
 }
 
 check() {
@@ -85,47 +90,116 @@ check() {
 }
 
 package() {
-	depends="libstdc++-dev"
+	# the libraries should always exactly match, not just by soname
+	depends="$pkgname-libs=$pkgver-r$pkgrel gcc libstdc++-dev"
 
-	DESTDIR="$pkgdir" ninja -C build install
+	DESTDIR="$pkgdir" cmake --install build
+	mkdir -p "$pkgdir"/usr/bin
 
 	install -Dm644 build/lib/libclang.a -t "$pkgdir"/usr/lib/llvm$_llvmver/lib/
 
-	cd "$pkgdir"/usr/lib
-	# the soname is the majorver but they kept the broken file version
-	rm libclang.so.13
-	ln -sfv libclang.so.$pkgver libclang.so.$_llvmver
-	ln -svf libclang.so.$_llvmver libclang.so
-
 	if [ $_default_clang = "yes" ]; then
-		rm "$pkgdir"/usr/lib/share/clang/clang-format-bbedit.applescript \
-			"$pkgdir"/usr/lib/share/clang/clang-doc-default-stylesheet.css \
-			"$pkgdir"/usr/lib/share/clang/index.js
-
-		install -Dm644 "$builddir"/clang.1 -t "$pkgdir"/usr/share/man/man1/
+		rm "$pkgdir"/usr/lib/llvm$_llvmver/share/clang/clang-format-bbedit.applescript \
+			"$pkgdir"/usr/lib/llvm$_llvmver/share/clang/clang-doc-default-stylesheet.css \
+			"$pkgdir"/usr/lib/llvm$_llvmver/share/clang/index.js
 
 		mkdir -p "$pkgdir"/usr/share/bash-completion/completions
-		mv "$pkgdir"/usr//share/clang/bash-autocomplete.sh \
+		mv "$pkgdir"/usr/lib/llvm$_llvmver/share/clang/bash-autocomplete.sh \
 			"$pkgdir"/usr/share/bash-completion/completions/clang
 
 		mkdir -p "$pkgdir"/usr/share/emacs/site-lisp
-		mv "$pkgdir"/usr/share/clang/clang-*.el \
+		mv "$pkgdir"/usr/lib/llvm$_llvmver/share/clang/clang-*.el \
 			"$pkgdir"/usr/share/emacs/site-lisp
-		rmdir -p usr/share/clang || true
+		rmdir -p usr/lib/llvm$_llvmver/share/emacs/clang || true
+
+		local sitedir=$(python3 -c "import site; print(site.getsitepackages()[0])")
+		mv "$pkgdir"/usr/lib/llvm$_llvmver/lib/python3* "$pkgdir"/usr/lib
+		mkdir -p "$pkgdir"/"$sitedir"
+		mv "$pkgdir"/usr/lib/llvm$_llvmver/lib/libscanbuild "$pkgdir"/"$sitedir"
+
+		mv "$pkgdir"/usr/lib/llvm$_llvmver/share/* "$pkgdir"/usr/share/
+
+		# symlink everything in the bin dir,
+		# into /usr/bin.
+		local clangexes="
+			analyze-build
+			c-index-test
+			clang
+			clang-cl
+			clang-cpp
+			clang-linker-wrapper
+			clang-nvlink-wrapper
+			clang-pseudo
+			clang++
+			clang-$_llvmver
+			clang-apply-replacements
+			clang-change-namespace
+			clang-check
+			clang-doc
+			clang-extdef-mapping
+			clang-format
+			clang-include-fixer
+			clang-move
+			clang-offload-bundler
+			clang-offload-packager
+			clang-offload-wrapper
+			clang-query
+			clang-refactor
+			clang-rename
+			clang-reorder-fields
+			clang-repl
+			clang-scan-deps
+			clang-tidy
+			clangd
+			diagtool
+			find-all-symbols
+			git-clang-format
+			hmaptool
+			intercept-build
+			modularize
+			pp-trace
+			run-clang-tidy
+			scan-build
+			scan-build-py
+			scan-view
+			"
+		for clangexe in $clangexes; do
+			ln -sfv ../lib/llvm$_llvmver/bin/$clangexe "$pkgdir"/usr/bin/$clangexe
+		done
+
+		install -Dm644 "$builddir"/clang.1 -t "$pkgdir"/usr/share/man/man1/
 	else
 		# only has things we want to put in the main version
-		rm -rf "$pkgdir"/usr/share
-		rm -rf "$pkgdir"/usr/lib/python3*
+		rm -rf "$pkgdir"/usr/lib/llvm$_llvmver/share
+		rm -rf "$pkgdir"/usr/lib/llvm$_llvmver/lib/python*
+
+		# provide only a versioned link, so you can add more than one clang version at once,
+		# and they don't conflict as this is the only thing in the global bin.
+		# we also add clang++-$_llvmver which is not normally present.
+		ln -sfv ../lib/llvm$_llvmver/bin/clang-$_llvmver "$pkgdir"/usr/bin/clang-$_llvmver
+		ln -sfv ../lib/llvm$_llvmver/bin/clang++ "$pkgdir"/usr/bin/clang-$_llvmver++
 	fi
+
+	# hack- 14 had weird naming.
+	local libs="
+		libclang-cpp.so
+		libclang-cpp.so.$_llvmver
+		libclang.so
+		libclang.so.13
+		libclang.so.$pkgver
+		"
+	for lib in $libs; do
+		ln -sfv ../lib/llvm$_llvmver/lib/$lib "$pkgdir"/usr/lib/$lib
+	done
 }
 
 dev() {
 	default_dev
 	_default_replace
 
-	# move back usr/lib/clang/x.y.z/include with files such as altivec.h, msa.h etc
+	# move back usr/lib/llvm*/lib/clang/x.y.z/include with files such as altivec.h, msa.h etc
 	# these are needed to build programs *with* clang, not *against* it.
-	mv "$subpkgdir"/usr/lib/clang "$pkgdir"/usr/lib/
+	mv "$subpkgdir"/usr/lib/llvm$_llvmver/lib/clang "$pkgdir"/usr/lib/llvm$_llvmver/lib/
 }
 
 static() {
@@ -140,31 +214,39 @@ bash() {
 
 libs() {
 	default_libs
+	# this can fail depending on the symlinks and is already moved
+	amove usr/lib/libclang-cpp.so.* || true
+	amove usr/lib/llvm$_llvmver/lib/libclang-cpp.so.*
 	_default_replace
 }
 
 libclang() {
 	_default_replace
+	replaces="$replaces clang-libs"
 
 	# we add an extra subpackage for this so things that link to libclang don't
 	# have to pull libclang-cpp too (separate)
 	amove usr/lib/libclang.so.*
+	amove usr/lib/llvm$_llvmver/lib/libclang.so.*
 }
 
 analyzer() {
 	pkgdesc="Clang source code analysis framework"
-	depends="$pkgname=$pkgver-r$pkgrel perl python3"
+	depends="$pkgname=$pkgver-r$pkgrel py3-$pkgname=$pkgver-r$pkgrel perl python3"
 	_default_replace
 
 	amove \
 		usr/bin/scan* \
 		usr/bin/analyze-build* \
 		usr/bin/intercept-build* \
-		usr/libexec/*-analyzer* \
-		usr/libexec/analyze-* \
-		usr/libexec/intercept-* \
-		usr/share/scan-* \
-		usr/lib/libear*
+		usr/lib/llvm$_llvmver/bin/scan* \
+		usr/lib/llvm$_llvmver/bin/analyze-build* \
+		usr/lib/llvm$_llvmver/bin/intercept-build* \
+		usr/lib/llvm$_llvmver/libexec/*-analyzer* \
+		usr/lib/llvm$_llvmver/libexec/analyze-* \
+		usr/lib/llvm$_llvmver/libexec/intercept-* \
+		usr/lib/llvm$_llvmver/lib/libear* \
+		usr/share/scan-*
 }
 
 extra() {
@@ -198,12 +280,37 @@ extra() {
 		usr/bin/modularize* \
 		usr/bin/pp-trace* \
 		usr/bin/run-clang-tidy* \
+		usr/lib/llvm$_llvmver/bin/clang-apply-replacements* \
+		usr/lib/llvm$_llvmver/bin/clang-change-namespace* \
+		usr/lib/llvm$_llvmver/bin/clang-check* \
+		usr/lib/llvm$_llvmver/bin/clang-doc* \
+		usr/lib/llvm$_llvmver/bin/clang-extdef-mapping* \
+		usr/lib/llvm$_llvmver/bin/clang-format* \
+		usr/lib/llvm$_llvmver/bin/clang-include-fixer* \
+		usr/lib/llvm$_llvmver/bin/clang-move* \
+		usr/lib/llvm$_llvmver/bin/clang-offload-bundler* \
+		usr/lib/llvm$_llvmver/bin/clang-offload-wrapper* \
+		usr/lib/llvm$_llvmver/bin/clang-query* \
+		usr/lib/llvm$_llvmver/bin/clang-refactor* \
+		usr/lib/llvm$_llvmver/bin/clang-rename* \
+		usr/lib/llvm$_llvmver/bin/clang-reorder-fields* \
+		usr/lib/llvm$_llvmver/bin/clang-repl* \
+		usr/lib/llvm$_llvmver/bin/clang-scan-deps* \
+		usr/lib/llvm$_llvmver/bin/clang-tidy* \
+		usr/lib/llvm$_llvmver/bin/clangd* \
+		usr/lib/llvm$_llvmver/bin/c-index-test* \
+		usr/lib/llvm$_llvmver/bin/diagtool* \
+		usr/lib/llvm$_llvmver/bin/find-all-symbols* \
+		usr/lib/llvm$_llvmver/bin/git-clang-format* \
+		usr/lib/llvm$_llvmver/bin/hmaptool* \
+		usr/lib/llvm$_llvmver/bin/modularize* \
+		usr/lib/llvm$_llvmver/bin/pp-trace* \
+		usr/lib/llvm$_llvmver/bin/run-clang-tidy* \
 		usr/share/clang/clang-include-fixer* \
 		usr/share/clang/clang-format*.py \
 		usr/share/clang/*clang-tidy* \
-		usr/share/clang/run-find-all-symbols.py
-
-	amove usr/share/emacs
+		usr/share/clang/run-find-all-symbols.py \
+		usr/share/emacs
 }
 
 python() {
@@ -212,13 +319,8 @@ python() {
 	provides="py3-clang=$pkgver-r$pkgrel"
 	replaces="py3-clang"
 
-	local sitedir=$(python3 -c "import site; print(site.getsitepackages()[0])")
-
 	amove usr/lib/python*
 	amove usr/share/clang/clang-rename.py
-
-	# actually a python module..
-	mv "$pkgdir"/usr/lib/libscanbuild "$subpkgdir"/"$sitedir"
 }
 
 _default_replace() {
