testing/elastic-beats: upgrade to 8.9.0

diff --git a/testing/elastic-beats/APKBUILD b/testing/elastic-beats/APKBUILD
--- a/testing/elastic-beats/APKBUILD
+++ b/testing/elastic-beats/APKBUILD
@@ -1,8 +1,8 @@
 # Contributor: Ramanathan Sivagurunathan <ramzthecoder@gmail.com>
 # Maintainer:
 pkgname=elastic-beats
-pkgver=8.8.2
-pkgrel=1
+pkgver=8.9.0
+pkgrel=0
 pkgdesc="Lightweight shippers for Elasticsearch & Logstash"
 url="https://www.elastic.co/products/beats"
 # riscv64: https://github.com/elastic/go-concert/issues/51
@@ -10,7 +10,11 @@ url="https://www.elastic.co/products/beats"
 # 32-bit: not useful
 arch="all !s390x !armhf !armv7 !x86 !riscv64"
 license="Apache-2.0"
-makedepends="go"
+makedepends="
+	go
+	mage
+	python3
+	"
 subpackages="
 	filebeat
 	filebeat-openrc:filebeat_openrc:noarch
@@ -24,6 +28,7 @@ source="$pkgname-$pkgver.tar.gz::https://github.com/elastic/beats/archive/refs/t
 	metricbeat.confd
 	"
 builddir="$srcdir/beats-$pkgver"
+options="net" # go
 
 export GOCACHE="${GOCACHE:-"$srcdir/go-cache"}"
 export GOTMPDIR="${GOTMPDIR:-"$srcdir"}"
@@ -35,32 +40,72 @@ x86_64) ;;
 *) options="$options !check" ;;
 esac
 
+prepare() {
+	default_prepare
+
+	git init -q
+	git config user.email "example@example.com"
+	git config user.name "example"
+	git add .
+	git commit -q -m "init"
+	git tag "v$pkgver"
+}
+
 build() {
 	export CGO_ENABLED=0
 
 	mkdir -p bin
 
 	# just these two for now
-	msg "building filebeat"
-	go build -o bin/filebeat ./filebeat/main.go
-	msg "building metricbeat"
-	go build -o bin/metricbeat ./metricbeat/main.go
+	(
+		msg "building filebeat"
+		cd filebeat
+		mage build
+		go build -o filebeat main.go
+		mage update
+	)
+	(
+		msg "building metricbeat"
+		cd metricbeat
+		mage build
+		go build -o metricbeat main.go
+		# fails in some random step presently
+		mage update || :
+	)
 }
 
 check() {
-	# requires building systemd go lib
-	#msg "testing filebeat"
-	#go test ./filebeat/...
+	msg "testing filebeat"
+	# shellcheck disable=2046
+	go test $(go list ./filebeat/... | grep -Ev '(journald|inputsource/unix)')
 	msg "testing metricbeat"
-	go test ./metricbeat/...
+	# shellcheck disable=2046
+	go test $(go list ./metricbeat/... | grep -Ev '(module/system/service)')
 }
 
 package() {
-	install -Dm644 filebeat/filebeat.yml filebeat/filebeat.reference.yml \
+	mkdir -p "$pkgdir"/usr/share/metricbeat "$pkgdir"/usr/share/filebeat
+
+	install -Dm644 \
+		filebeat/filebeat.yml \
+		filebeat/filebeat.reference.yml \
+		filebeat/fields.yml \
 		-t "$pkgdir"/etc/filebeat
-	install -Dm644 metricbeat/metricbeat.yml metricbeat/metricbeat.reference.yml \
+	cp -r filebeat/modules.d "$pkgdir"/etc/filebeat/
+	cp -r filebeat/module "$pkgdir"/usr/share/filebeat/
+
+	install -Dm644 \
+		metricbeat/metricbeat.yml \
+		metricbeat/metricbeat.reference.yml \
+		metricbeat/fields.yml \
 		-t "$pkgdir"/etc/metricbeat
-	install -Dm755 bin/* -t "$pkgdir"/usr/bin/
+	cp -r metricbeat/modules.d "$pkgdir"/etc/metricbeat/
+	cp -r metricbeat/module "$pkgdir"/usr/share/metricbeat/
+
+	install -Dm755 \
+		filebeat/filebeat \
+		metricbeat/metricbeat \
+		 -t "$pkgdir"/usr/bin/
 }
 
 filebeat() {
@@ -68,7 +113,8 @@ filebeat() {
 
 	amove \
 		usr/bin/filebeat \
-		etc/filebeat
+		etc/filebeat \
+		usr/share/filebeat
 }
 
 filebeat_openrc() {
@@ -84,7 +130,8 @@ metricbeat() {
 
 	amove \
 		usr/bin/metricbeat \
-		etc/metricbeat
+		etc/metricbeat \
+		usr/share/metricbeat
 }
 
 metricbeat_openrc() {
@@ -96,7 +143,7 @@ metricbeat_openrc() {
 }
 
 sha512sums="
-75c8ed30cc1888789b062dbabcd3a6c8f1531063d05a2d1d1d27869ce8eba4b60522bfe45ee0a66a5969b634888d59ee10d035fc0cf190db9d85bfbbf9a919b5  elastic-beats-8.8.2.tar.gz
+20f1d8333216690adb3dab71eb1b8da7f06d1d53897f3d230ca3affb842d285f4b16cbd7ed7ab54ed07b84c4905c9008d4371b4cc2550cc275e58a0cb3307446  elastic-beats-8.9.0.tar.gz
 526b149419cf51e21ab4b7b49b208dbef81571afd04f2c40ab05297d5eb4b03e64e6c7a06d1acf8771b7b0664a552082ce6f50d5cbc4218aca810440d6185990  filebeat.initd
 f6168b10da75919cf16b2a32a5b25847e9e49aaea7415e49d2644960fc586c60714754cbe60f5a6d290cd7b9f8d3fd86287e46e63891825feb82f747e235d58d  filebeat.confd
 4736fab0119bea080cb5a938d0b40e803967cbfac373d1b714a43176032ea36b9865f3c6658e33ff6befa150ccdf6ddcbfcf59bd31e4ae961d075623eac80ea6  metricbeat.initd
