community/git-annex: upgrade to 10.20220822

diff --git a/community/git-annex/APKBUILD b/community/git-annex/APKBUILD
--- a/community/git-annex/APKBUILD
+++ b/community/git-annex/APKBUILD
@@ -1,8 +1,8 @@
 # Maintainer: Antoine Martin (ayakael) <dev@ayakael.net>
 # Contributor: Antoine Martin (ayakael) <dev@ayakael.net>
 pkgname=git-annex
-pkgver=10.20220724
-pkgrel=1
+pkgver=10.20220822
+pkgrel=0
 pkgdesc="Manage files with git, without checking their contents into git"
 url="http://git-annex.branchable.com"
 arch="x86_64 aarch64" # limited by ghc
@@ -28,7 +28,7 @@ makedepends="
 	zlib-dev
 	"
 
-source="https://git.joeyh.name/index.cgi/git-annex.git/snapshot/git-annex-$pkgver.tar.gz"
+source="https://git.joeyh.name/index.cgi/git-annex.git/snapshot/git-annex-$pkgver.tar.gz cabal.config"
 subpackages="$pkgname-doc $pkgname-bash-completion $pkgname-zsh-completion"
 
 # Add / remove '-' between "-f" and "FeatureName" to adjust feature build
@@ -67,10 +67,38 @@ _restore_home() {
 	export TMPDIR="$ORIG_TMPDIR"
 }
 
+_cabal_update() {
+	_localize_home
+	msg "Freezing $pkgname dependencies"
+
+	# Resolve deps and generate fresh cabal.config with version constraints.
+	cabal update
+	(
+		cd "$builddir"
+		cabal v1-freeze --shadow-installed-packages
+
+		# Add version tag at the first line.
+		sed -i "1i--$pkgver" "cabal.config"
+
+		mv "cabal.config" "$startdir/"
+	)
+
+	if ! abuild checksum; then
+		die "Failed to update checksum, run 'abuild checksum' manually"
+	fi
+	_restore_home
+}
+
 prepare() {
 	default_prepare
 	_localize_home
 	mkdir -p "$HOME" "$TMPDIR"
+
+	if [ "$(head -n 1 "$srcdir/cabal.config")" != "--$pkgver" ]; then
+		die "Requirements file is outdated, run 'abuild _cabal_update'"
+	fi
+
+	ln -sf "$srcdir/cabal.config" "$builddir/cabal.config"
 
 	msg "Features: $_feature_flags"
 
@@ -108,5 +136,6 @@ package() {
 
 
 sha512sums="
-13dfef9c123b490d6defbd26353a53d02a5a98bdfe8994590c48b9a9d19b636f74384d6669b819393ca9c2b32290fc8a32c3de67338a0cae98290b0db842fa82  git-annex-10.20220724.tar.gz
+84e876b9a58c04768f6eab7833119fd87e60214dc7aaf5e86d749315833e52e6e781f3646125f26e1cb7ed59fac945b9144942296dedbc884813baf1c9247b7f  git-annex-10.20220822.tar.gz
+d64a0a4753f0a238bae60c61e5c5db993d668e6f92f081051fea070af74be8806a97327445fed319131a043379dc9731f9e251286eb6a364cc28f2074b730bb3  cabal.config
 "
