communitu/lockdev: fix license and  maintainer

diff --git a/community/lockdev/APKBUILD b/community/lockdev/APKBUILD
--- a/community/lockdev/APKBUILD
+++ b/community/lockdev/APKBUILD
@@ -1,12 +1,12 @@
 # Contributor: Carlo Landmeter <clandmeter@gmail.com>
-# Maintainer:
+# Maintainer: Natanael Copa <ncopa@alpinelinux.org>
 pkgname=lockdev
 pkgver=0_git20130107
 pkgrel=1
 pkgdesc="Run-time shared library for locking devices, using _both_ FSSTND and SVr4 methods."
 url="http://packages.qa.debian.org/l/lockdev.html"
 arch="all"
-license="GPL"
+license="LGPL-2.1"
 depends=""
 depends_dev=""
 makedepends="$depends_dev automake autoconf libtool"
@@ -25,14 +25,14 @@ prepare() {
 		*.patch) msg $i; patch -p1 -i "$srcdir"/$i || return 1;;
 		esac
 	done
+	# bootstap fails with missing m4 dir
+	mkdir m4
+	./bootstrap || return 1
 }
 
 build() {
 	cd "$_builddir"
-	[ "$CLIBC" == "musl" ] && export CFLAGS="$CFLAGS -D__GNU_LIBRARY__"
-	# bootstap fails with missing m4 dir
-	mkdir m4
-	./bootstrap || return 1
+	[ "$CLIBC" = "musl" ] && export CFLAGS="$CFLAGS -D__GNU_LIBRARY__"
 	./configure \
 		--build=$CBUILD \
 		--host=$CHOST \
