community/waydroid: fix rootfs image mounting with modular loop

diff --git a/community/waydroid/waydroid-container.initd b/community/waydroid/waydroid-container.initd
--- a/community/waydroid/waydroid-container.initd
+++ b/community/waydroid/waydroid-container.initd
@@ -13,6 +13,16 @@ depends() {
 	uses net
 }
 
+start_pre() {
+	# Avoid 'mount: /var/lib/waydroid/rootfs: mount failed: Operation not permitted.'
+	if [ ! -c /dev/loop-control ]; then
+		if ! modprobe loop; then
+			eerror "Loopback device support is not available in this kernel"
+			return 1
+		fi
+	fi
+}
+
 stop() {
 	ebegin "Stopping Waydroid container..."
 	
