main/lua-turbo: update to 2.0.1

diff --git a/main/lua-turbo/APKBUILD b/main/lua-turbo/APKBUILD
--- a/main/lua-turbo/APKBUILD
+++ b/main/lua-turbo/APKBUILD
@@ -1,7 +1,9 @@
 # Contributor: Carlo Landmeter <clandmeter@gmail.com>
-# Maintainer:
+# Maintainer: Carlo Landmeter <clandmeter@gmail.com>
+
 pkgname=lua-turbo
-pkgver=1.1.3
+_jitver=2.0.4
+pkgver=2.0.1
 pkgrel=0
 pkgdesc="a framework built for LuaJIT 2 and Linux"
 url="http://www.turbolua.org/"
@@ -25,22 +27,40 @@ prepare() {
 		*.patch) msg $i; patch -p1 -i "$srcdir"/$i || return 1;;
 		esac
 	done
+	# check if we are using the current luajit version
+	if [ -r ../../../../main/luajit/APKBUILD ]; then
+		local _currentjit=$(grep "^pkgver=" ../../../../main/luajit/APKBUILD)
+		export LUAJIT_VERSION="$_jitver"
+		msg "Building for luajit version $_jitver"
+		if [ "${_currentjit#*=}" != "$LUAJIT_VERSION" ]; then
+			die "luajit version does not match!"
+		fi
+	else
+		die "cannot locate luajit APKBUILD!"
+	fi
+	# we need to fix the loading of libssl.
+	# so we replace symlink with real filename
+	sed -i -e \
+		"s|os.getenv(\"TURBO_LIBSSL\") or \"ssl\"|\"$(readlink /usr/lib/libssl.so)\"|" \
+		turbo/hash.lua || return 1
+	sed -i -e \
+		"s|os.getenv(\"TURBO_LIBSSL\") or \"ssl\"|\"$(readlink /usr/lib/libssl.so)\"|" \
+		turbo/crypto_linux.lua || return 1
 }
 
 build() {
 	cd "$_builddir"
-	make PREFIX=/usr LUAJIT_VERSION=2.0.3 || return 1
+	make PREFIX=/usr || return 1
 }
 
 package() {
 	cd "$_builddir"
-	make PREFIX="$pkgdir"/usr \
-		LUAJIT_VERSION=2.0.3 install || return 1
+	make PREFIX="$pkgdir"/usr install || return 1
 }
 
-md5sums="4e2e87d2cc1e9e9cda7d67176a2ab150  lua-turbo-1.1.3.tar.gz
+md5sums="29562bdad7dd6beb5b13dd954b63ec28  lua-turbo-2.0.1.tar.gz
 5fbc1fcf73ef48998a90b06df782162c  fix-bindir.patch"
-sha256sums="025bc2d4236fbdfa59ba55a86c94778408a82561c5c6d39e85705ea3121e7010  lua-turbo-1.1.3.tar.gz
+sha256sums="3885920f018b8d7b5a71d8ea097c0b8da18b2b1e7c9251aabbd1af67c882d7fc  lua-turbo-2.0.1.tar.gz
 d676d0cd520759f293afdb59e59024a4ad30a8c419ab348e6acc1e72a1bb90a4  fix-bindir.patch"
-sha512sums="7fe9a46998d88bfc746aa37eb87f2a63db16d67fbe1973fd459d8490440c1d24dbf0058685bdde17de9d5a150e8503771862a8bf8fb01eb153c607b663c9fae0  lua-turbo-1.1.3.tar.gz
+sha512sums="a3f8b9fa88dc25d13b1101d2feab403d6b02634d8eea7dc94bf8ed9fa7aabb30f4c8d3057debb194fcdc58777b0443fb550f797f94fc6f29705e0a20794bfbde  lua-turbo-2.0.1.tar.gz
 e8ce4427bcf7040fdf3f711a533a0857d9dcf3678334fd4b32917642cb1a5c540ade3d3c8e26bc6b8a7ce0ff6c6f64c92eda70edec3874e7aa3507acb82c2211  fix-bindir.patch"
