main/lua-turbo: upgrade to 1.1.6
properly link to libssl
try to properly detect luajit version

diff --git a/main/lua-turbo/APKBUILD b/main/lua-turbo/APKBUILD
--- a/main/lua-turbo/APKBUILD
+++ b/main/lua-turbo/APKBUILD
@@ -1,10 +1,9 @@
 # Contributor: Carlo Landmeter <clandmeter@gmail.com>
 # Maintainer: Carlo Landmeter <clandmeter@gmail.com>
 
-_jitver=$(grep "^pkgver=" ../luajit/APKBUILD)
-
 pkgname=lua-turbo
-pkgver=1.1.5
+_jitver=2.0.4
+pkgver=1.1.6
 pkgrel=0
 pkgdesc="a framework built for LuaJIT 2 and Linux"
 url="http://www.turbolua.org/"
@@ -29,26 +28,43 @@ prepare() {
 		*.patch) msg $i; patch -p1 -i "$srcdir"/$i || return 1;;
 		esac
 	done
+	# check if we are using the current luajit version
+	if [ -r ../../../../main/luajit/APKBUILD ]; then
+		local _currentjit=$(grep "^pkgver=" ../../../../main/luajit/APKBUILD)
+		export LUAJIT_VERSION="$_jitver"
+		msg "Building for luajit version $_jitver"
+		if [ "${_currentjit#*=}" != "$LUAJIT_VERSION" ]; then
+			die "luajit version does not match!"
+		fi
+	else
+		die "cannot locate luajit APKBUILD!"
+	fi
+	# we need to fix the loading of libssl.
+	# so we replace symlink with real filename
+	sed -i -e \
+		"s|ffi.load\"ssl\"|ffi.load\"$(readlink /usr/lib/libssl.so)\"|" \
+		turbo/hash.lua || return 1
+	sed -i -e \
+		"s|ffi.load(\"ssl\")|ffi.load(\"$(readlink /usr/lib/libssl.so)\")|" \
+		turbo/crypto.lua || return 1
 }
 
 build() {
 	cd "$_builddir"
-	#pkgver=${pkgver#*=}
-	make PREFIX=/usr LUAJIT_VERSION=${_jitver#*=} || return 1
+	make PREFIX=/usr || return 1
 }
 
 package() {
 	cd "$_builddir"
-	make PREFIX="$pkgdir"/usr \
-		LUAJIT_VERSION=${_jitver#*=} install || return 1
+	make PREFIX="$pkgdir"/usr install || return 1
 }
 
-md5sums="b626b227bb2a47f59dda68d121b47db6  lua-turbo-1.1.5.tar.gz
+md5sums="3fe7d896dc6e6abcd65763abe7cada51  lua-turbo-1.1.6.tar.gz
 5fbc1fcf73ef48998a90b06df782162c  fix-bindir.patch
 87944005b334730fe2536cd2897c3fba  case-sensitive-url-matching.patch"
-sha256sums="bfad7e1e229d2fd95c571b99d645032cd5b8799bd533c310fcadabc7ae181214  lua-turbo-1.1.5.tar.gz
+sha256sums="e221ae568f3b1b8fbb59a490c0401da9eda7514c5fcceeaf38788623cd31a3b5  lua-turbo-1.1.6.tar.gz
 d676d0cd520759f293afdb59e59024a4ad30a8c419ab348e6acc1e72a1bb90a4  fix-bindir.patch
 de865aa2c1a0c32088f7eac03521ca71d79a5ea89adedac8cecd99ee5fe67a7e  case-sensitive-url-matching.patch"
-sha512sums="86b64b4a65743cc8033611a9500ce59521af936a460a34d8ca94d18caf311c6213c5448d501829399201e1a930f10a707cffd27b4736a220227606fbba9d38ac  lua-turbo-1.1.5.tar.gz
+sha512sums="f1bbda85a7d05d4f9a336478fa146523737f16564a4f8ba5d2c00cc346b6ad5e3c8deba53bfeef4033463da207f9b85da11ac6fefe3fd9b6df287504bcc8a6ce  lua-turbo-1.1.6.tar.gz
 e8ce4427bcf7040fdf3f711a533a0857d9dcf3678334fd4b32917642cb1a5c540ade3d3c8e26bc6b8a7ce0ff6c6f64c92eda70edec3874e7aa3507acb82c2211  fix-bindir.patch
 b6154799a70c59b7bddffc1afa296afe1e3ac3c3c6bcdd29a4bfbac61bba1f9f12500ed5d9ee326788033213e749adfb63c1c03625b3c3f0081079a76ab3c9eb  case-sensitive-url-matching.patch"
