testing/yaws: misc fixes for consistency
- rename yaws.init.d to yaws.initd
- use tab as indent
- remove install scripts - apk can handle empty dirs

diff --git a/testing/yaws/APKBUILD b/testing/yaws/APKBUILD
--- a/testing/yaws/APKBUILD
+++ b/testing/yaws/APKBUILD
@@ -2,7 +2,7 @@
 # Maintainer:
 pkgname=yaws
 pkgver=1.96
-pkgrel=1
+pkgrel=2
 pkgdesc="Yet Another Web Server, pure Erlang HTTP server/framework"
 url="http://yaws.hyber.org/"
 arch="all"
@@ -11,12 +11,12 @@ depends="erlang linux-pam"
 depends_dev="linux-pam-dev erlang-dev"
 makedepends="$depends_dev"
 options="!emptydirs"
-install="$pkgname.post-install $pkgname.post-upgrade $pkgname.post-deinstall"
+install=""
 subpackages="$pkgname-doc $pkgname-web"
 source="http://yaws.hyber.org/download/$pkgname-$pkgver.tar.gz
-        yaws.init.d
-        yaws.conf.alpine
-        yaws-1.96-etc.patch"
+	yaws.initd
+	yaws.conf.alpine
+	yaws-1.96-etc.patch"
 
 _builddir="$srcdir/$pkgname-$pkgver"
 prepare() {
@@ -31,52 +31,59 @@ prepare() {
 
 build() {
 	cd "$_builddir"
-    export ERLCFLAGS="-W"
-    ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var
-    make || return 1
+	export ERLCFLAGS="-W"
+	./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var
+	make || return 1
 }
 
 package() {
 	cd "$_builddir"
-    make DESTDIR="$pkgdir" install || return 1
+	make DESTDIR="$pkgdir" install || return 1
 
-    # XXX: from arch linux
-    install -d "$pkgdir/usr/lib/erlang/lib"
-    ln -s /usr/lib/yaws "$pkgdir/usr/lib/erlang/lib/$pkgname-$pkgver"
+	# XXX: from arch linux
+	install -d "$pkgdir/usr/lib/erlang/lib"
+	ln -s /usr/lib/yaws "$pkgdir/usr/lib/erlang/lib/$pkgname-$pkgver" \
+		|| return 1
 
-    # init.d
-    install -Dm755 "$srcdir/yaws.init.d" "$pkgdir/etc/init.d/yaws"
+	# init.d
+	install -Dm755 "$srcdir/yaws.initd" "$pkgdir/etc/init.d/yaws" \
+		|| return 1
 
-    # License
-    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
+	# License
+	install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE" \
+		|| return 1
 
-    # update config 
-    # * basically change log dir to /var/log/yaws
-    # * on of <server localhost> definitions commented, because conflict
-    install -Dm644 "$srcdir"/yaws.conf.alpine "$pkgdir/etc/yaws/yaws.conf"
+	# update config
+	# * basically change log dir to /var/log/yaws
+	# * on of <server localhost> definitions commented, because conflict
+	install -Dm644 "$srcdir"/yaws.conf.alpine "$pkgdir/etc/yaws/yaws.conf" \
+		|| return 1
+
+	install -d "$pkgdir"/var/log/yaws
 }
 
 web() {
-    arch="noarch"
-    depends="yaws"
-    pkgdesc="Yet Another Web Server, pure Erlang HTTP server/framework (examples)"
+	arch="noarch"
+	depends="yaws"
+	pkgdesc="Yet Another Web Server, pure Erlang HTTP server/framework (examples)"
 
-    mkdir -p "$subpkgdir"/var
-    mv "$pkgdir"/var/yaws "$subpkgdir"/var/
+	mkdir -p "$subpkgdir"/var
+	mv "$pkgdir"/var/yaws "$subpkgdir"/var/
 
-    # cleanup unnecessary Makefiles
-    find "$subpkgdir"/var/yaws/www -type f -name 'Makefile' -exec rm -f {} \;
+	# cleanup unnecessary Makefiles
+	find "$subpkgdir"/var/yaws/www -type f -name 'Makefile' \
+		-exec rm -f {} \;
 }
 
 md5sums="7c9231b7d9880033c9d3bfba2aa3c901  yaws-1.96.tar.gz
-3a1445696bd25ae71631d13457980693  yaws.init.d
+3a1445696bd25ae71631d13457980693  yaws.initd
 2b71d01e0837aff6798e602c74ae6a2c  yaws.conf.alpine
 988d08b3501aa80d2f6ba5513f8a70af  yaws-1.96-etc.patch"
 sha256sums="8d4f16d18937335ac021ca4c65c8ee81dc4d71f133718c7148856cc6bf1f55e2  yaws-1.96.tar.gz
-313ce8cacd25e8eed5717dfd9e79d1683a4038a64cffff6e93aacfd2fb11c261  yaws.init.d
+313ce8cacd25e8eed5717dfd9e79d1683a4038a64cffff6e93aacfd2fb11c261  yaws.initd
 ebff598ac47a0185a81ca5fb45b1c843b184390d85c630686aa2579b6d51e3af  yaws.conf.alpine
 cc76022bd81302724ec169f14b6fa167fe66cc18b47e8990a25b4bca0406969c  yaws-1.96-etc.patch"
 sha512sums="821ffe530a265462df083a9408e1798616bf11f8c891955500f8de170f77de831defc65c2341d0552471dde253df16ae3d27d59eaa0ccd79b117f3070f49fb2c  yaws-1.96.tar.gz
-07ff290eb98be729445d797361503d01dfba29f050639632d251202267aa485655fd04798f4de8d66a83bb0a798280116f8b06d5b9e8810d3cb2d20c1c1bd1d6  yaws.init.d
+07ff290eb98be729445d797361503d01dfba29f050639632d251202267aa485655fd04798f4de8d66a83bb0a798280116f8b06d5b9e8810d3cb2d20c1c1bd1d6  yaws.initd
 7f4bf1a099337cf53a2492cc2e295108adcb9ab26b27089303429542c5097ed357623f6d448c5b0b9c9e4d0e8517350ab9d8bf1b6d51a529c45b264f810c688d  yaws.conf.alpine
 b0b056c44d92eb2d1f7486f8113dc07be9a958b73a354dc993c210f4d53d6997e8b93e6c17d1eaeeb3e4899be3c337d9e7b953bd1bad40d63e851c5f5981fa2c  yaws-1.96-etc.patch"
