community/roc-toolkit: run check

diff --git a/community/roc-toolkit/APKBUILD b/community/roc-toolkit/APKBUILD
--- a/community/roc-toolkit/APKBUILD
+++ b/community/roc-toolkit/APKBUILD
@@ -15,29 +15,41 @@ makedepends="
 	ragel
 	scons
 	"
-
+checkdepends="
+	cpputest
+	python3
+	"
 subpackages="$pkgname-libs $pkgname-dev"
 source="https://github.com/roc-streaming/roc-toolkit/archive/v$pkgver/roc-toolkit-$pkgver.tar.gz
 	0001-Remove-deprecated-scons-call.patch
 	0002-Fix-compatibility-with-new-SCons.patch
 	0003-libunwind-aarch64.patch
 	"
-options="!check" # Tests fail to build
+
+case "$CARCH" in
+arm*|x86)
+	# fail on 32-bit
+	# original: -0.999969,	received: -0.993927
+	options="$options !check"
+esac
 
 _run_scons() {
+	local _check=""
+	if ! want_check; then
+		_check="--disable-tests"
+	fi
 	scons \
 		--prefix="$pkgdir"/usr \
 		--with-libraries=/usr/lib \
 		--disable-examples \
-		--disable-tests \
 		--disable-sox \
 		--disable-openfec \
 		--disable-pulseaudio \
+		$_check \
 		$@
 }
 
 build() {
-	# tests disabled due to failure to find cpputest
 	_run_scons
 }
 
