community/bird: migrate initd to supervise-daemon

diff --git a/community/bird/bird.initd b/community/bird/bird.initd
--- a/community/bird/bird.initd
+++ b/community/bird/bird.initd
@@ -1,22 +1,20 @@
 #!/sbin/openrc-run
-# Copyright 1999-2019 Gentoo Authors
-# Copyright 2019 Alarig Le Lay <alarig@grifon.fr>
-# Distributed under the terms of the GNU General Public License v2
 
-extra_started_commands="reload"
+name="${RC_SVCNAME}"
+command="/usr/sbin/bird"
 
-pidfile="/run/bird/${RC_SVCNAME}.pid"
-# See https://bird.network.cz/?get_doc&v=20&f=bird-1.html#ss1.4 for priveleges
-# requirements.
-command="/usr/sbin/${RC_SVCNAME}"
-retry=15
-
+: ${supervisor:="supervise-daemon"}
 : ${CONF_FILE:="/etc/${RC_SVCNAME}.conf"}
-SOCK="/run/${RC_SVCNAME}.ctl"
+: ${SOCK_PATH:="/var/run/${RC_SVCNAME}.ctl"}
+: ${USER:="bird"}
+: ${GROUP:="bird"}
 
-client_args="-s ${SOCK}"
-command_args="-u bird -g bird ${client_args} -R -c ${CONF_FILE} -P ${pidfile}"
-client_args="${client_args} -r"
+command_args="-u ${USER} -g ${GROUP} -s ${SOCK_PATH} -c ${CONF_FILE} ${BIRD_ARGS}"
+command_args_foreground="-f"
+command_background=true
+
+extra_commands="configtest"
+extra_started_commands="reload"
 
 depend() {
 	need net
@@ -25,37 +23,31 @@ depend() {
 }
 
 start_pre() {
-	# Used to store bird's PID file, which iscreated after privilege drop.
-	checkpath --directory --owner bird:bird --mode 0775 /run/bird
 	# Ensure permissions on configuration file are correct for upgrades.
-	checkpath --file --owner root:bird --mode 0640 ${CONF_FILE}
+	checkpath --file --owner root:${GROUP} --mode 0640 "${CONF_FILE}"
+	# Validate the config file before starting
+	/usr/sbin/bird -p -c "${CONF_FILE}"
 }
 
-check_run() {
-	BIRD_CHECK_CONF="birdc ${client_args} configure check \"${CONF_FILE}\""
-	# Check if the bird parser returns what we want
-	# We can’t use $? because it’s always 0 if the sock works
-	STATE=$(${BIRD_CHECK_CONF} | grep 'Configuration OK')
-
-	if [ -n "${STATE}" ]; then
-		return 0
-	else
-		# We remove the first three lines (garbage informations), the
-		# errors begin after that
-		eerror "$(${BIRD_CHECK_CONF} | sed '1,3d')"
-		return 1
+configtest() {
+	/usr/sbin/bird -p -c "${CONF_FILE}" 1>/dev/null 2>&1
+	ret=$?
+	if [ $ret -ne 0 ]; then
+		eerror "${RC_SVCNAME} has detected an error in your setup:"
+		/usr/sbin/bird -p -c "${CONF_FILE}"
 	fi
+	return $ret
 }
 
 reload() {
-	check_run || return 1
-	ebegin "Reloading BIRD"
-	start-stop-daemon --signal HUP --pidfile "${pidfile}"
-	eend $?
-}
-
-stop_pre() {
-	if [ "${RC_CMD}" = "restart" ] ; then
-		check_run || return 1
+	ebegin "Reloading ${RC_SVCNAME} configuration"
+	/usr/sbin/birdc -s "${SOCK_PATH}" "configure check" 1>/dev/null 2>&1
+	ret=$?
+	if [ $ret -eq 0 ]; then
+		/usr/sbin/birdc -s "${SOCK_PATH}" "configure"
+	else
+		eerror "${RC_SVCNAME} has detected an error in your setup:"
+		/usr/sbin/birdc -s "${SOCK_PATH}" "configure check"
 	fi
+	eend $?
 }
