main/alpine-mirrors: add brazilian mirror and add tests

diff --git a/main/alpine-mirrors/APKBUILD b/main/alpine-mirrors/APKBUILD
--- a/main/alpine-mirrors/APKBUILD
+++ b/main/alpine-mirrors/APKBUILD
@@ -1,14 +1,14 @@
 # Contributor: Matt Smith <mcs@darkregion.net>
 # Maintainer: Natanael Copa <ncopa@alpinelinux.org>
 pkgname=alpine-mirrors
-pkgver=3.4.5
+pkgver=3.4.6
 pkgrel=0
 pkgdesc="List of Alpine Linux Mirrors"
 url="http://alpinelinux.org/"
 arch="noarch"
 license="MIT"
 depends=""
-makedepends=""
+makedepends="curl"
 install=""
 subpackages=""
 source="mirrors.yaml"
@@ -18,6 +18,23 @@ build() {
 	awk '$1 == "-" && $2 ~ /^http:/ {print $2}' mirrors.yaml > MIRRORS.txt
 }
 
+check() {
+	cd "$srcdir"
+	local failed=""
+	for i in $(cat MIRRORS.txt); do
+		msg "testing $i"
+		curl --head --connect-timeout 10 $i >/dev/null \
+			|| failed="$failed $i"
+	done
+	if [ -n "$failed" ]; then
+		error "Following mirrors failed:"
+		for i in $failed; do
+			echo $i
+		done
+		return 1
+	fi
+}
+
 package() {
 	install -D -m644 "$srcdir"/mirrors.yaml \
 		"$pkgdir"/usr/share/alpine-mirrors/mirrors.yaml || return 1
@@ -25,4 +42,4 @@ package() {
 		"$pkgdir"/usr/share/alpine-mirrors/MIRRORS.txt || return 1
 }
 
-sha512sums="6e33d75e9d758bae5edae21d3f29f52ed45acb26a8df597f5374fa0316a665425c2e8b05197517a6073b2c47cdca390f77e5b9046218f853e2fa99896905a49e  mirrors.yaml"
+sha512sums="7c46b0c43a716e2268e893c6375116c7db0e2be1e653edb24e940901cc343d25170fab4d48f2189212f114a67909e9dee84d6bc538bfce6500230b1a2fcbc39f  mirrors.yaml"
