testing/wpa_supplicant: enable libnl
also move config to APKBUILD
ref #212

diff --git a/testing/wpa_supplicant/APKBUILD b/testing/wpa_supplicant/APKBUILD
--- a/testing/wpa_supplicant/APKBUILD
+++ b/testing/wpa_supplicant/APKBUILD
@@ -1,27 +1,98 @@
 # Maintainer: Natanael Copa <ncopa@alpinelinux.org>
 pkgname=wpa_supplicant
 pkgver=0.6.9
-pkgrel=0
+pkgrel=1
 pkgdesc="A utility providing key negotiation for WPA wireless networks"
 url="http://hostap.epitest.fi/wpa_supplicant"
 license="GPL"
 subpackages="$pkgname-doc"
 depends=
-makedepends="openssl-dev dbus-dev"
+makedepends="openssl-dev dbus-dev libnl-dev"
 source="http://hostap.epitest.fi/releases/$pkgname-$pkgver.tar.gz
-	defconfig
 	"
 
+_builddir="$srcdir"/$pkgname-$pkgver/$pkgname
+prepare() {
+	cd "$_builddir"
+	# Toolchain setup
+	echo "CC = $CC" > .config
+
+	# Basic setup
+	echo "CONFIG_CTRL_IFACE=y" >> .config
+	echo "CONFIG_BACKEND=file" >> .config
+
+	# Basic authentication methods
+	# NOTE: we don't set GPSK or SAKE as they conflict
+	# with the below options
+	echo "CONFIG_EAP_GTC=y"         >> .config
+	echo "CONFIG_EAP_MD5=y"         >> .config
+	echo "CONFIG_EAP_OTP=y"         >> .config
+	echo "CONFIG_EAP_PAX=y"         >> .config
+	echo "CONFIG_EAP_PSK=y"         >> .config
+	echo "CONFIG_EAP_TLV=y"         >> .config
+	echo "CONFIG_IEEE8021X_EAPOL=y" >> .config
+	echo "CONFIG_PKCS12=y"          >> .config
+	echo "CONFIG_PEERKEY=y"         >> .config
+	echo "CONFIG_EAP_LEAP=y"        >> .config
+	echo "CONFIG_EAP_MSCHAPV2=y"    >> .config
+	echo "CONFIG_EAP_PEAP=y"        >> .config
+	echo "CONFIG_EAP_TLS=y"         >> .config
+	echo "CONFIG_EAP_TTLS=y"        >> .config
+
+	# dbus support
+	echo "CONFIG_CTRL_IFACE_DBUS=y" >> .config
+
+	# debug
+	# echo "CONFIG_DEBUG_FILE=y" >> .config
+
+	# Smart card authentication
+	#echo "CONFIG_EAP_SIM=y"       >> .config
+	#echo "CONFIG_EAP_AKA=y"       >> .config
+	#echo "CONFIG_EAP_AKA_PRIME=y" >> .config
+	#echo "CONFIG_PCSC=y"          >> .config
+
+	# readline/history support for wpa_cli
+	#echo "CONFIG_READLINE=y" >> .config
+
+	# SSL authentication methods
+	echo "CONFIG_TLS=openssl"    >> .config
+	echo "CONFIG_SMARTCARD=y"    >> .config
+	# use gnutls
+	# echo "CONFIG_TLS=gnutls"     >> .config
+	# echo "CONFIG_GNUTLS_EXTRA=y" >> .config
+	#echo "CONFIG_TLS=internal"   >> .config
+
+	# Linux specific drivers
+	echo "CONFIG_DRIVER_ATMEL=y"       >> .config
+	#echo "CONFIG_DRIVER_BROADCOM=y"   >> .config
+	#echo "CONFIG_DRIVER_HERMES=y"	   >> .config
+	echo "CONFIG_DRIVER_HOSTAP=y"      >> .config
+	echo "CONFIG_DRIVER_IPW=y"         >> .config
+	echo "CONFIG_DRIVER_NDISWRAPPER=y" >> .config
+	echo "CONFIG_DRIVER_NL80211=y"     >> .config
+	#echo "CONFIG_DRIVER_PRISM54=y"    >> .config
+	echo "CONFIG_DRIVER_RALINK=y"      >> .config
+	echo "CONFIG_DRIVER_WEXT=y"        >> .config
+	echo "CONFIG_DRIVER_WIRED=y"       >> .config
+
+	# Add include path for madwifi-driver headers
+	#echo "CFLAGS += -I/usr/include/madwifi" >> .config
+	#echo "CONFIG_DRIVER_MADWIFI=y"          >> .config
+
+	# Wi-Fi Protected Setup (WPS)
+	echo "CONFIG_WPS=y" >> .config
+
+	# Enable mitigation against certain attacks against TKIP
+	echo "CONFIG_DELAYED_MIC_ERROR_REPORT=y" >> .config
+}
+
 build() { 
-	cd "$srcdir"/$pkgname-$pkgver/$pkgname
-	cp "$srcdir"/defconfig .config
-	sed -i 's@/usr/local@$(PREFIX)@g' Makefile
-	sed -i 's@dynamic_eap_methods@@g' Makefile
+	cd "$_builddir"
 	make || return 1
 }
 
 package() {
-	cd "$srcdir"/$pkgname-$pkgver/$pkgname
+	cd "$_builddir"
 	make PREFIX=/usr DESTDIR="$pkgdir" install || return 1
 	install -Dm644 wpa_supplicant.conf "$pkgdir"/etc/wpa_supplicant.conf
 	install -Dm644 doc/docbook/wpa_supplicant.conf.5 \
@@ -36,7 +107,7 @@ package() {
 	install -m644 dbus-wpa_supplicant.service \
 		"$pkgdir"/usr/share/dbus-1/system-services/fi.epitest.hostap.WPASupplicant.service || return 1
 	install -m755 -d "$pkgdir"/etc/dbus-1/system.d
-	install -m644 dbus-wpa_supplicant.conf "$pkgdir"/etc/dbus-1/system.d/fi.epitest.hostap.WPASupplicant.conf || return 1
+	install -m644 dbus-wpa_supplicant.conf \
+		"$pkgdir"/etc/dbus-1/system.d/fi.epitest.hostap.WPASupplicant.conf || return 1
 }
-md5sums="0efb8fcedf0a8acf6f423dfdb0658fdd  wpa_supplicant-0.6.9.tar.gz
-5bff1c58cf6c01cdf6274bf4392e714a  defconfig"
+md5sums="0efb8fcedf0a8acf6f423dfdb0658fdd  wpa_supplicant-0.6.9.tar.gz"
