community/darcs: upgrade to 2.18.3
https://hackage.haskell.org/package/darcs-2.18.3/src/CHANGELOG.md

diff --git a/community/darcs/APKBUILD b/community/darcs/APKBUILD
--- a/community/darcs/APKBUILD
+++ b/community/darcs/APKBUILD
@@ -1,7 +1,7 @@
 # Contributor: gay <gay@disroot.org>
 # Maintainer: Celeste <cielesti@protonmail.com>
 pkgname=darcs
-pkgver=2.18.2
+pkgver=2.18.3
 pkgrel=0
 pkgdesc="Patch-based revision control system"
 url="https://darcs.net/"
@@ -16,25 +16,45 @@ source="https://hackage.haskell.org/package/darcs-$pkgver/darcs-$pkgver.tar.gz
 	"
 
 # Directory where cabal files are stored.
-export CABAL_DIR="$srcdir/dist"
+export CABAL_DIR="${CABAL_DIR:-"$srcdir/dist"}"
 
 # Needed to fix build on aarch64.
 export PATH="$PATH:/usr/lib/llvm15/bin"
 
 cabal_update() {
-	cd $builddir
-	cabal v2-update
+	local repo="hackage.haskell.org"
+
+	# Default config uses HTTP, change it to HTTPS.
+	[ -f "$CABAL_DIR"/config ] || {
+		cabal user-config init
+		cabal user-config update -a \
+			"repository $repo {url: https://$repo/}"
+	}
+
+	[ -d "$builddir" ] || abuild unpack
+	msg "Freezing $pkgname dependencies"
+
+	# Resolve deps and generate fresh cabal.project.freeze with version constraints.
 	(
-		cd "$builddir"
+		cd "$builddir" || {
+			error 'Is $builddir set correctly?'
+			return 1
+		}
+		cabal v2-update
 		cabal v2-freeze --shadow-installed-packages
-		mv cabal.project.freeze "$startdir/"
+
+		mv -v cabal.project.freeze "$startdir"/
 	)
+
+	if ! abuild checksum; then
+		die "Failed to update checksum, run 'abuild checksum' manually"
+	fi
 }
 
 prepare() {
 	default_prepare
-	ln -sf "$srcdir/cabal.project.freeze" \
-		"$builddir/cabal.project.freeze"
+
+	ln -svf "$srcdir"/cabal.project.freeze "$builddir"/
 }
 
 build() {
@@ -57,6 +77,6 @@ package() {
 }
 
 sha512sums="
-f776b3b2efd73e9515a99bf154468aa4aef925d20c9de564a78f7a19bf302db31c6e4cdbca2c2c700a0d5cde1b62a426159554f543898712b1f603401c534a9c  darcs-2.18.2.tar.gz
-b177b661b37a907db1af30e6f796a5c2f600bc8b19411b3a741b071a45ee257a2371e160ea7c1cc31b07a288f2aa9966a14318ca1c0c0eede6aa11fe81798de9  cabal.project.freeze
+de70b87493ed9776a16d492ca1fb2f7e1a4a46bf3538ebe937adc8b548b1b4519cb7a737edd13b92253c797a04765832b37c9ef6d552705db6980454429da3d6  darcs-2.18.3.tar.gz
+aa94626e596cc0935d14baa874fac5430cf90f3967e5d5c43214151118cdefae8430ac523ef13e084fd1688b25b4bd825fa459a53d88f63b54be43f140a7fb13  cabal.project.freeze
 "
